// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/expenditure/supplier_contract_price_schedule_line/supplier_contract_price_schedule_line.proto

package expenditurev1

import (
	common "github.com/erniealice/esqyma/pkg/schema/v1/domain/common"
	supplier_contract_price_schedule "github.com/erniealice/esqyma/pkg/schema/v1/domain/expenditure/supplier_contract_price_schedule"
	_ "github.com/erniealice/esqyma/pkg/schema/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SupplierContractPriceScheduleLine is the per-line, per-window pricing
// override row. One row per (SupplierContractLine × SupplierContractPriceSchedule).
//
// Resolution rule (use-case layer): when ResolveActiveScheduleLine(
// contract_line_id, asOf) is called, the use case picks the active
// schedule whose half-open window contains asOf and joins on
// (schedule_id, contract_line_id). If a row exists, its unit_price is
// used; otherwise fall back to SupplierContractLine.unit_price. Mirrors
// the sales-side rate-card precedence (Model D refactor).
type SupplierContractPriceScheduleLine struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Audit
	DateCreated        *int64  `protobuf:"varint,3,opt,name=date_created,json=dateCreated,proto3,oneof" json:"date_created,omitempty"`
	DateCreatedString  *string `protobuf:"bytes,4,opt,name=date_created_string,json=dateCreatedString,proto3,oneof" json:"date_created_string,omitempty"`
	DateModified       *int64  `protobuf:"varint,5,opt,name=date_modified,json=dateModified,proto3,oneof" json:"date_modified,omitempty"`
	DateModifiedString *string `protobuf:"bytes,6,opt,name=date_modified_string,json=dateModifiedString,proto3,oneof" json:"date_modified_string,omitempty"`
	Active             bool    `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	// Parent schedule (the date window)
	SupplierContractPriceScheduleId string                                                          `protobuf:"bytes,10,opt,name=supplier_contract_price_schedule_id,json=supplierContractPriceScheduleId,proto3" json:"supplier_contract_price_schedule_id,omitempty"`
	SupplierContractPriceSchedule   *supplier_contract_price_schedule.SupplierContractPriceSchedule `protobuf:"bytes,11,opt,name=supplier_contract_price_schedule,json=supplierContractPriceSchedule,proto3,oneof" json:"supplier_contract_price_schedule,omitempty"`
	// The contract line being priced for this window
	SupplierContractLineId string `protobuf:"bytes,12,opt,name=supplier_contract_line_id,json=supplierContractLineId,proto3" json:"supplier_contract_line_id,omitempty"`
	// Money — overrides SupplierContractLine.unit_price for this window
	Currency      string   `protobuf:"bytes,20,opt,name=currency,proto3" json:"currency,omitempty"`
	UnitPrice     int64    `protobuf:"varint,21,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`                   // centavos
	MinimumAmount *int64   `protobuf:"varint,22,opt,name=minimum_amount,json=minimumAmount,proto3,oneof" json:"minimum_amount,omitempty"` // for MINIMUM_COMMITMENT treatment
	Quantity      *float64 `protobuf:"fixed64,23,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`                               // optional committed quantity (BLANKET / MINIMUM_COMMITMENT)
	// Cycle override — most lines inherit cycle from the parent contract.
	// Some lines (utility tiers, indexed escalators) need cycle-specific overrides.
	CycleValueOverride *int32  `protobuf:"varint,30,opt,name=cycle_value_override,json=cycleValueOverride,proto3,oneof" json:"cycle_value_override,omitempty"`
	CycleUnitOverride  *string `protobuf:"bytes,31,opt,name=cycle_unit_override,json=cycleUnitOverride,proto3,oneof" json:"cycle_unit_override,omitempty"`
	// Notes
	Notes         *string           `protobuf:"bytes,50,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,51,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplierContractPriceScheduleLine) Reset() {
	*x = SupplierContractPriceScheduleLine{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplierContractPriceScheduleLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierContractPriceScheduleLine) ProtoMessage() {}

func (x *SupplierContractPriceScheduleLine) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierContractPriceScheduleLine.ProtoReflect.Descriptor instead.
func (*SupplierContractPriceScheduleLine) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{0}
}

func (x *SupplierContractPriceScheduleLine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetDateCreated() int64 {
	if x != nil && x.DateCreated != nil {
		return *x.DateCreated
	}
	return 0
}

func (x *SupplierContractPriceScheduleLine) GetDateCreatedString() string {
	if x != nil && x.DateCreatedString != nil {
		return *x.DateCreatedString
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetDateModified() int64 {
	if x != nil && x.DateModified != nil {
		return *x.DateModified
	}
	return 0
}

func (x *SupplierContractPriceScheduleLine) GetDateModifiedString() string {
	if x != nil && x.DateModifiedString != nil {
		return *x.DateModifiedString
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *SupplierContractPriceScheduleLine) GetSupplierContractPriceScheduleId() string {
	if x != nil {
		return x.SupplierContractPriceScheduleId
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetSupplierContractPriceSchedule() *supplier_contract_price_schedule.SupplierContractPriceSchedule {
	if x != nil {
		return x.SupplierContractPriceSchedule
	}
	return nil
}

func (x *SupplierContractPriceScheduleLine) GetSupplierContractLineId() string {
	if x != nil {
		return x.SupplierContractLineId
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *SupplierContractPriceScheduleLine) GetMinimumAmount() int64 {
	if x != nil && x.MinimumAmount != nil {
		return *x.MinimumAmount
	}
	return 0
}

func (x *SupplierContractPriceScheduleLine) GetQuantity() float64 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *SupplierContractPriceScheduleLine) GetCycleValueOverride() int32 {
	if x != nil && x.CycleValueOverride != nil {
		return *x.CycleValueOverride
	}
	return 0
}

func (x *SupplierContractPriceScheduleLine) GetCycleUnitOverride() string {
	if x != nil && x.CycleUnitOverride != nil {
		return *x.CycleUnitOverride
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *SupplierContractPriceScheduleLine) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSupplierContractPriceScheduleLineRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Data          *SupplierContractPriceScheduleLine `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSupplierContractPriceScheduleLineRequest) Reset() {
	*x = CreateSupplierContractPriceScheduleLineRequest{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupplierContractPriceScheduleLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupplierContractPriceScheduleLineRequest) ProtoMessage() {}

func (x *CreateSupplierContractPriceScheduleLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupplierContractPriceScheduleLineRequest.ProtoReflect.Descriptor instead.
func (*CreateSupplierContractPriceScheduleLineRequest) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSupplierContractPriceScheduleLineRequest) GetData() *SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSupplierContractPriceScheduleLineResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Data          []*SupplierContractPriceScheduleLine `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error                        `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSupplierContractPriceScheduleLineResponse) Reset() {
	*x = CreateSupplierContractPriceScheduleLineResponse{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSupplierContractPriceScheduleLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSupplierContractPriceScheduleLineResponse) ProtoMessage() {}

func (x *CreateSupplierContractPriceScheduleLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSupplierContractPriceScheduleLineResponse.ProtoReflect.Descriptor instead.
func (*CreateSupplierContractPriceScheduleLineResponse) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSupplierContractPriceScheduleLineResponse) GetData() []*SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateSupplierContractPriceScheduleLineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSupplierContractPriceScheduleLineResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReadSupplierContractPriceScheduleLineRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Data          *SupplierContractPriceScheduleLine `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSupplierContractPriceScheduleLineRequest) Reset() {
	*x = ReadSupplierContractPriceScheduleLineRequest{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSupplierContractPriceScheduleLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSupplierContractPriceScheduleLineRequest) ProtoMessage() {}

func (x *ReadSupplierContractPriceScheduleLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSupplierContractPriceScheduleLineRequest.ProtoReflect.Descriptor instead.
func (*ReadSupplierContractPriceScheduleLineRequest) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{3}
}

func (x *ReadSupplierContractPriceScheduleLineRequest) GetData() *SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadSupplierContractPriceScheduleLineResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Data          []*SupplierContractPriceScheduleLine `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error                        `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSupplierContractPriceScheduleLineResponse) Reset() {
	*x = ReadSupplierContractPriceScheduleLineResponse{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSupplierContractPriceScheduleLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSupplierContractPriceScheduleLineResponse) ProtoMessage() {}

func (x *ReadSupplierContractPriceScheduleLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSupplierContractPriceScheduleLineResponse.ProtoReflect.Descriptor instead.
func (*ReadSupplierContractPriceScheduleLineResponse) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{4}
}

func (x *ReadSupplierContractPriceScheduleLineResponse) GetData() []*SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadSupplierContractPriceScheduleLineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadSupplierContractPriceScheduleLineResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateSupplierContractPriceScheduleLineRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Data          *SupplierContractPriceScheduleLine `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSupplierContractPriceScheduleLineRequest) Reset() {
	*x = UpdateSupplierContractPriceScheduleLineRequest{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSupplierContractPriceScheduleLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSupplierContractPriceScheduleLineRequest) ProtoMessage() {}

func (x *UpdateSupplierContractPriceScheduleLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSupplierContractPriceScheduleLineRequest.ProtoReflect.Descriptor instead.
func (*UpdateSupplierContractPriceScheduleLineRequest) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSupplierContractPriceScheduleLineRequest) GetData() *SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSupplierContractPriceScheduleLineResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Data          []*SupplierContractPriceScheduleLine `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error                        `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSupplierContractPriceScheduleLineResponse) Reset() {
	*x = UpdateSupplierContractPriceScheduleLineResponse{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSupplierContractPriceScheduleLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSupplierContractPriceScheduleLineResponse) ProtoMessage() {}

func (x *UpdateSupplierContractPriceScheduleLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSupplierContractPriceScheduleLineResponse.ProtoReflect.Descriptor instead.
func (*UpdateSupplierContractPriceScheduleLineResponse) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSupplierContractPriceScheduleLineResponse) GetData() []*SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateSupplierContractPriceScheduleLineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSupplierContractPriceScheduleLineResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteSupplierContractPriceScheduleLineRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Data          *SupplierContractPriceScheduleLine `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSupplierContractPriceScheduleLineRequest) Reset() {
	*x = DeleteSupplierContractPriceScheduleLineRequest{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSupplierContractPriceScheduleLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSupplierContractPriceScheduleLineRequest) ProtoMessage() {}

func (x *DeleteSupplierContractPriceScheduleLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSupplierContractPriceScheduleLineRequest.ProtoReflect.Descriptor instead.
func (*DeleteSupplierContractPriceScheduleLineRequest) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSupplierContractPriceScheduleLineRequest) GetData() *SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteSupplierContractPriceScheduleLineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSupplierContractPriceScheduleLineResponse) Reset() {
	*x = DeleteSupplierContractPriceScheduleLineResponse{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSupplierContractPriceScheduleLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSupplierContractPriceScheduleLineResponse) ProtoMessage() {}

func (x *DeleteSupplierContractPriceScheduleLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSupplierContractPriceScheduleLineResponse.ProtoReflect.Descriptor instead.
func (*DeleteSupplierContractPriceScheduleLineResponse) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSupplierContractPriceScheduleLineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSupplierContractPriceScheduleLineResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListSupplierContractPriceScheduleLinesRequest struct {
	state                           protoimpl.MessageState    `protogen:"open.v1"`
	SupplierContractPriceScheduleId *string                   `protobuf:"bytes,1,opt,name=supplier_contract_price_schedule_id,json=supplierContractPriceScheduleId,proto3,oneof" json:"supplier_contract_price_schedule_id,omitempty"`
	SupplierContractLineId          *string                   `protobuf:"bytes,2,opt,name=supplier_contract_line_id,json=supplierContractLineId,proto3,oneof" json:"supplier_contract_line_id,omitempty"`
	Search                          *common.SearchRequest     `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Filters                         *common.FilterRequest     `protobuf:"bytes,4,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	Sort                            *common.SortRequest       `protobuf:"bytes,5,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Pagination                      *common.PaginationRequest `protobuf:"bytes,6,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ListSupplierContractPriceScheduleLinesRequest) Reset() {
	*x = ListSupplierContractPriceScheduleLinesRequest{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupplierContractPriceScheduleLinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupplierContractPriceScheduleLinesRequest) ProtoMessage() {}

func (x *ListSupplierContractPriceScheduleLinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupplierContractPriceScheduleLinesRequest.ProtoReflect.Descriptor instead.
func (*ListSupplierContractPriceScheduleLinesRequest) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{9}
}

func (x *ListSupplierContractPriceScheduleLinesRequest) GetSupplierContractPriceScheduleId() string {
	if x != nil && x.SupplierContractPriceScheduleId != nil {
		return *x.SupplierContractPriceScheduleId
	}
	return ""
}

func (x *ListSupplierContractPriceScheduleLinesRequest) GetSupplierContractLineId() string {
	if x != nil && x.SupplierContractLineId != nil {
		return *x.SupplierContractLineId
	}
	return ""
}

func (x *ListSupplierContractPriceScheduleLinesRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ListSupplierContractPriceScheduleLinesRequest) GetFilters() *common.FilterRequest {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListSupplierContractPriceScheduleLinesRequest) GetSort() *common.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListSupplierContractPriceScheduleLinesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListSupplierContractPriceScheduleLinesResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Data          []*SupplierContractPriceScheduleLine `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error                        `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupplierContractPriceScheduleLinesResponse) Reset() {
	*x = ListSupplierContractPriceScheduleLinesResponse{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupplierContractPriceScheduleLinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupplierContractPriceScheduleLinesResponse) ProtoMessage() {}

func (x *ListSupplierContractPriceScheduleLinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupplierContractPriceScheduleLinesResponse.ProtoReflect.Descriptor instead.
func (*ListSupplierContractPriceScheduleLinesResponse) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{10}
}

func (x *ListSupplierContractPriceScheduleLinesResponse) GetData() []*SupplierContractPriceScheduleLine {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSupplierContractPriceScheduleLinesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListSupplierContractPriceScheduleLinesResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSupplierContractPriceScheduleLineListPageDataRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	Filters       *common.FilterRequest     `protobuf:"bytes,2,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	Sort          *common.SortRequest       `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Search        *common.SearchRequest     `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierContractPriceScheduleLineListPageDataRequest) Reset() {
	*x = GetSupplierContractPriceScheduleLineListPageDataRequest{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierContractPriceScheduleLineListPageDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierContractPriceScheduleLineListPageDataRequest) ProtoMessage() {}

func (x *GetSupplierContractPriceScheduleLineListPageDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierContractPriceScheduleLineListPageDataRequest.ProtoReflect.Descriptor instead.
func (*GetSupplierContractPriceScheduleLineListPageDataRequest) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{11}
}

func (x *GetSupplierContractPriceScheduleLineListPageDataRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetSupplierContractPriceScheduleLineListPageDataRequest) GetFilters() *common.FilterRequest {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetSupplierContractPriceScheduleLineListPageDataRequest) GetSort() *common.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *GetSupplierContractPriceScheduleLineListPageDataRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type GetSupplierContractPriceScheduleLineListPageDataResponse struct {
	state                                 protoimpl.MessageState               `protogen:"open.v1"`
	SupplierContractPriceScheduleLineList []*SupplierContractPriceScheduleLine `protobuf:"bytes,1,rep,name=supplier_contract_price_schedule_line_list,json=supplierContractPriceScheduleLineList,proto3" json:"supplier_contract_price_schedule_line_list,omitempty"`
	Pagination                            *common.PaginationResponse           `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	SearchResults                         []*common.SearchResult               `protobuf:"bytes,3,rep,name=search_results,json=searchResults,proto3" json:"search_results,omitempty"`
	Success                               bool                                 `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error                                 *common.Error                        `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) Reset() {
	*x = GetSupplierContractPriceScheduleLineListPageDataResponse{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierContractPriceScheduleLineListPageDataResponse) ProtoMessage() {}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierContractPriceScheduleLineListPageDataResponse.ProtoReflect.Descriptor instead.
func (*GetSupplierContractPriceScheduleLineListPageDataResponse) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{12}
}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) GetSupplierContractPriceScheduleLineList() []*SupplierContractPriceScheduleLine {
	if x != nil {
		return x.SupplierContractPriceScheduleLineList
	}
	return nil
}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) GetSearchResults() []*common.SearchResult {
	if x != nil {
		return x.SearchResults
	}
	return nil
}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSupplierContractPriceScheduleLineListPageDataResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSupplierContractPriceScheduleLineItemPageDataRequest struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	SupplierContractPriceScheduleLineId string                 `protobuf:"bytes,1,opt,name=supplier_contract_price_schedule_line_id,json=supplierContractPriceScheduleLineId,proto3" json:"supplier_contract_price_schedule_line_id,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataRequest) Reset() {
	*x = GetSupplierContractPriceScheduleLineItemPageDataRequest{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierContractPriceScheduleLineItemPageDataRequest) ProtoMessage() {}

func (x *GetSupplierContractPriceScheduleLineItemPageDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierContractPriceScheduleLineItemPageDataRequest.ProtoReflect.Descriptor instead.
func (*GetSupplierContractPriceScheduleLineItemPageDataRequest) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{13}
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataRequest) GetSupplierContractPriceScheduleLineId() string {
	if x != nil {
		return x.SupplierContractPriceScheduleLineId
	}
	return ""
}

type GetSupplierContractPriceScheduleLineItemPageDataResponse struct {
	state                             protoimpl.MessageState             `protogen:"open.v1"`
	SupplierContractPriceScheduleLine *SupplierContractPriceScheduleLine `protobuf:"bytes,1,opt,name=supplier_contract_price_schedule_line,json=supplierContractPriceScheduleLine,proto3,oneof" json:"supplier_contract_price_schedule_line,omitempty"`
	Success                           bool                               `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                             *common.Error                      `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataResponse) Reset() {
	*x = GetSupplierContractPriceScheduleLineItemPageDataResponse{}
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierContractPriceScheduleLineItemPageDataResponse) ProtoMessage() {}

func (x *GetSupplierContractPriceScheduleLineItemPageDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierContractPriceScheduleLineItemPageDataResponse.ProtoReflect.Descriptor instead.
func (*GetSupplierContractPriceScheduleLineItemPageDataResponse) Descriptor() ([]byte, []int) {
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP(), []int{14}
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataResponse) GetSupplierContractPriceScheduleLine() *SupplierContractPriceScheduleLine {
	if x != nil {
		return x.SupplierContractPriceScheduleLine
	}
	return nil
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSupplierContractPriceScheduleLineItemPageDataResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto protoreflect.FileDescriptor

const file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDesc = "" +
	"\n" +
	"ddomain/expenditure/supplier_contract_price_schedule_line/supplier_contract_price_schedule_line.proto\x12\x15domain.expenditure.v1\x1a\x19domain/common/error.proto\x1a\x1edomain/common/pagination.proto\x1a\x1adomain/common/search.proto\x1a\x1adomain/common/filter.proto\x1a\x18domain/common/sort.proto\x1aZdomain/expenditure/supplier_contract_price_schedule/supplier_contract_price_schedule.proto\x1a\x10options/db.proto\"\xaf\n" +
	"\n" +
	"!SupplierContractPriceScheduleLine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\fworkspace_id\x18\x02 \x01(\tB\x11\x82\xb5\x18\r\n" +
	"\tworkspace\x18\x01R\vworkspaceId\x12&\n" +
	"\fdate_created\x18\x03 \x01(\x03H\x00R\vdateCreated\x88\x01\x01\x123\n" +
	"\x13date_created_string\x18\x04 \x01(\tH\x01R\x11dateCreatedString\x88\x01\x01\x12(\n" +
	"\rdate_modified\x18\x05 \x01(\x03H\x02R\fdateModified\x88\x01\x01\x125\n" +
	"\x14date_modified_string\x18\x06 \x01(\tH\x03R\x12dateModifiedString\x88\x01\x01\x12\"\n" +
	"\x06active\x18\a \x01(\bB\n" +
	"\x82\xb5\x18\x06\"\x04trueR\x06active\x12v\n" +
	"#supplier_contract_price_schedule_id\x18\n" +
	" \x01(\tB(\x82\xb5\x18$\n" +
	" supplier_contract_price_schedule\x18\x01R\x1fsupplierContractPriceScheduleId\x12\x82\x01\n" +
	" supplier_contract_price_schedule\x18\v \x01(\v24.domain.expenditure.v1.SupplierContractPriceScheduleH\x04R\x1dsupplierContractPriceSchedule\x88\x01\x01\x12Y\n" +
	"\x19supplier_contract_line_id\x18\f \x01(\tB\x1e\x82\xb5\x18\x1a\n" +
	"\x16supplier_contract_line\x18\x01R\x16supplierContractLineId\x12\x1a\n" +
	"\bcurrency\x18\x14 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x15 \x01(\x03R\tunitPrice\x12*\n" +
	"\x0eminimum_amount\x18\x16 \x01(\x03H\x05R\rminimumAmount\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\x17 \x01(\x01H\x06R\bquantity\x88\x01\x01\x125\n" +
	"\x14cycle_value_override\x18\x1e \x01(\x05H\aR\x12cycleValueOverride\x88\x01\x01\x123\n" +
	"\x13cycle_unit_override\x18\x1f \x01(\tH\bR\x11cycleUnitOverride\x88\x01\x01\x12\x19\n" +
	"\x05notes\x182 \x01(\tH\tR\x05notes\x88\x01\x01\x12b\n" +
	"\bmetadata\x183 \x03(\v2F.domain.expenditure.v1.SupplierContractPriceScheduleLine.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x06\x8a\xb5\x18\x02\b\x01B\x0f\n" +
	"\r_date_createdB\x16\n" +
	"\x14_date_created_stringB\x10\n" +
	"\x0e_date_modifiedB\x17\n" +
	"\x15_date_modified_stringB#\n" +
	"!_supplier_contract_price_scheduleB\x11\n" +
	"\x0f_minimum_amountB\v\n" +
	"\t_quantityB\x17\n" +
	"\x15_cycle_value_overrideB\x16\n" +
	"\x14_cycle_unit_overrideB\b\n" +
	"\x06_notes\"~\n" +
	".CreateSupplierContractPriceScheduleLineRequest\x12L\n" +
	"\x04data\x18\x01 \x01(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\"\xd7\x01\n" +
	"/CreateSupplierContractPriceScheduleLineResponse\x12L\n" +
	"\x04data\x18\x01 \x03(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"|\n" +
	",ReadSupplierContractPriceScheduleLineRequest\x12L\n" +
	"\x04data\x18\x01 \x01(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\"\xd5\x01\n" +
	"-ReadSupplierContractPriceScheduleLineResponse\x12L\n" +
	"\x04data\x18\x01 \x03(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"~\n" +
	".UpdateSupplierContractPriceScheduleLineRequest\x12L\n" +
	"\x04data\x18\x01 \x01(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\"\xd7\x01\n" +
	"/UpdateSupplierContractPriceScheduleLineResponse\x12L\n" +
	"\x04data\x18\x01 \x03(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"~\n" +
	".DeleteSupplierContractPriceScheduleLineRequest\x12L\n" +
	"\x04data\x18\x01 \x01(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\"\x89\x01\n" +
	"/DeleteSupplierContractPriceScheduleLineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xb7\x04\n" +
	"-ListSupplierContractPriceScheduleLinesRequest\x12Q\n" +
	"#supplier_contract_price_schedule_id\x18\x01 \x01(\tH\x00R\x1fsupplierContractPriceScheduleId\x88\x01\x01\x12>\n" +
	"\x19supplier_contract_line_id\x18\x02 \x01(\tH\x01R\x16supplierContractLineId\x88\x01\x01\x12<\n" +
	"\x06search\x18\x03 \x01(\v2\x1f.domain.common.v1.SearchRequestH\x02R\x06search\x88\x01\x01\x12>\n" +
	"\afilters\x18\x04 \x01(\v2\x1f.domain.common.v1.FilterRequestH\x03R\afilters\x88\x01\x01\x126\n" +
	"\x04sort\x18\x05 \x01(\v2\x1d.domain.common.v1.SortRequestH\x04R\x04sort\x88\x01\x01\x12H\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2#.domain.common.v1.PaginationRequestH\x05R\n" +
	"pagination\x88\x01\x01B&\n" +
	"$_supplier_contract_price_schedule_idB\x1c\n" +
	"\x1a_supplier_contract_line_idB\t\n" +
	"\a_searchB\n" +
	"\n" +
	"\b_filtersB\a\n" +
	"\x05_sortB\r\n" +
	"\v_pagination\"\xd6\x01\n" +
	".ListSupplierContractPriceScheduleLinesResponse\x12L\n" +
	"\x04data\x18\x01 \x03(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xe8\x02\n" +
	"7GetSupplierContractPriceScheduleLineListPageDataRequest\x12H\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.domain.common.v1.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01\x12>\n" +
	"\afilters\x18\x02 \x01(\v2\x1f.domain.common.v1.FilterRequestH\x01R\afilters\x88\x01\x01\x126\n" +
	"\x04sort\x18\x03 \x01(\v2\x1d.domain.common.v1.SortRequestH\x02R\x04sort\x88\x01\x01\x12<\n" +
	"\x06search\x18\x04 \x01(\v2\x1f.domain.common.v1.SearchRequestH\x03R\x06search\x88\x01\x01B\r\n" +
	"\v_paginationB\n" +
	"\n" +
	"\b_filtersB\a\n" +
	"\x05_sortB\t\n" +
	"\a_search\"\xc9\x03\n" +
	"8GetSupplierContractPriceScheduleLineListPageDataResponse\x12\x93\x01\n" +
	"*supplier_contract_price_schedule_line_list\x18\x01 \x03(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineR%supplierContractPriceScheduleLineList\x12I\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.domain.common.v1.PaginationResponseH\x00R\n" +
	"pagination\x88\x01\x01\x12E\n" +
	"\x0esearch_results\x18\x03 \x03(\v2\x1e.domain.common.v1.SearchResultR\rsearchResults\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x17.domain.common.v1.ErrorH\x01R\x05error\x88\x01\x01B\r\n" +
	"\v_paginationB\b\n" +
	"\x06_error\"\x90\x01\n" +
	"7GetSupplierContractPriceScheduleLineItemPageDataRequest\x12U\n" +
	"(supplier_contract_price_schedule_line_id\x18\x01 \x01(\tR#supplierContractPriceScheduleLineId\"\xce\x02\n" +
	"8GetSupplierContractPriceScheduleLineItemPageDataResponse\x12\x8f\x01\n" +
	"%supplier_contract_price_schedule_line\x18\x01 \x01(\v28.domain.expenditure.v1.SupplierContractPriceScheduleLineH\x00R!supplierContractPriceScheduleLine\x88\x01\x01\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x01R\x05error\x88\x01\x01B(\n" +
	"&_supplier_contract_price_schedule_lineB\b\n" +
	"\x06_error2\xfa\n" +
	"\n" +
	".SupplierContractPriceScheduleLineDomainService\x12\xb8\x01\n" +
	"'CreateSupplierContractPriceScheduleLine\x12E.domain.expenditure.v1.CreateSupplierContractPriceScheduleLineRequest\x1aF.domain.expenditure.v1.CreateSupplierContractPriceScheduleLineResponse\x12\xb2\x01\n" +
	"%ReadSupplierContractPriceScheduleLine\x12C.domain.expenditure.v1.ReadSupplierContractPriceScheduleLineRequest\x1aD.domain.expenditure.v1.ReadSupplierContractPriceScheduleLineResponse\x12\xb8\x01\n" +
	"'UpdateSupplierContractPriceScheduleLine\x12E.domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineRequest\x1aF.domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineResponse\x12\xb8\x01\n" +
	"'DeleteSupplierContractPriceScheduleLine\x12E.domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineRequest\x1aF.domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineResponse\x12\xb5\x01\n" +
	"&ListSupplierContractPriceScheduleLines\x12D.domain.expenditure.v1.ListSupplierContractPriceScheduleLinesRequest\x1aE.domain.expenditure.v1.ListSupplierContractPriceScheduleLinesResponse\x12\xd3\x01\n" +
	"0GetSupplierContractPriceScheduleLineListPageData\x12N.domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataRequest\x1aO.domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataResponse\x12\xd3\x01\n" +
	"0GetSupplierContractPriceScheduleLineItemPageData\x12N.domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataRequest\x1aO.domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataResponseB\xac\x02\n" +
	"\x19com.domain.expenditure.v1B&SupplierContractPriceScheduleLineProtoP\x01Zqgithub.com/erniealice/esqyma/pkg/schema/v1/domain/expenditure/supplier_contract_price_schedule_line;expenditurev1\xa2\x02\x03DEX\xaa\x02\x15Domain.Expenditure.V1\xca\x02\x15Domain\\Expenditure\\V1\xe2\x02!Domain\\Expenditure\\V1\\GPBMetadata\xea\x02\x17Domain::Expenditure::V1b\x06proto3"

var (
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescOnce sync.Once
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescData []byte
)

func file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescGZIP() []byte {
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescOnce.Do(func() {
		file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDesc), len(file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDesc)))
	})
	return file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDescData
}

var file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_goTypes = []any{
	(*SupplierContractPriceScheduleLine)(nil),                        // 0: domain.expenditure.v1.SupplierContractPriceScheduleLine
	(*CreateSupplierContractPriceScheduleLineRequest)(nil),           // 1: domain.expenditure.v1.CreateSupplierContractPriceScheduleLineRequest
	(*CreateSupplierContractPriceScheduleLineResponse)(nil),          // 2: domain.expenditure.v1.CreateSupplierContractPriceScheduleLineResponse
	(*ReadSupplierContractPriceScheduleLineRequest)(nil),             // 3: domain.expenditure.v1.ReadSupplierContractPriceScheduleLineRequest
	(*ReadSupplierContractPriceScheduleLineResponse)(nil),            // 4: domain.expenditure.v1.ReadSupplierContractPriceScheduleLineResponse
	(*UpdateSupplierContractPriceScheduleLineRequest)(nil),           // 5: domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineRequest
	(*UpdateSupplierContractPriceScheduleLineResponse)(nil),          // 6: domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineResponse
	(*DeleteSupplierContractPriceScheduleLineRequest)(nil),           // 7: domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineRequest
	(*DeleteSupplierContractPriceScheduleLineResponse)(nil),          // 8: domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineResponse
	(*ListSupplierContractPriceScheduleLinesRequest)(nil),            // 9: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesRequest
	(*ListSupplierContractPriceScheduleLinesResponse)(nil),           // 10: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesResponse
	(*GetSupplierContractPriceScheduleLineListPageDataRequest)(nil),  // 11: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataRequest
	(*GetSupplierContractPriceScheduleLineListPageDataResponse)(nil), // 12: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataResponse
	(*GetSupplierContractPriceScheduleLineItemPageDataRequest)(nil),  // 13: domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataRequest
	(*GetSupplierContractPriceScheduleLineItemPageDataResponse)(nil), // 14: domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataResponse
	nil, // 15: domain.expenditure.v1.SupplierContractPriceScheduleLine.MetadataEntry
	(*supplier_contract_price_schedule.SupplierContractPriceSchedule)(nil), // 16: domain.expenditure.v1.SupplierContractPriceSchedule
	(*common.Error)(nil),              // 17: domain.common.v1.Error
	(*common.SearchRequest)(nil),      // 18: domain.common.v1.SearchRequest
	(*common.FilterRequest)(nil),      // 19: domain.common.v1.FilterRequest
	(*common.SortRequest)(nil),        // 20: domain.common.v1.SortRequest
	(*common.PaginationRequest)(nil),  // 21: domain.common.v1.PaginationRequest
	(*common.PaginationResponse)(nil), // 22: domain.common.v1.PaginationResponse
	(*common.SearchResult)(nil),       // 23: domain.common.v1.SearchResult
}
var file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_depIdxs = []int32{
	16, // 0: domain.expenditure.v1.SupplierContractPriceScheduleLine.supplier_contract_price_schedule:type_name -> domain.expenditure.v1.SupplierContractPriceSchedule
	15, // 1: domain.expenditure.v1.SupplierContractPriceScheduleLine.metadata:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine.MetadataEntry
	0,  // 2: domain.expenditure.v1.CreateSupplierContractPriceScheduleLineRequest.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	0,  // 3: domain.expenditure.v1.CreateSupplierContractPriceScheduleLineResponse.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	17, // 4: domain.expenditure.v1.CreateSupplierContractPriceScheduleLineResponse.error:type_name -> domain.common.v1.Error
	0,  // 5: domain.expenditure.v1.ReadSupplierContractPriceScheduleLineRequest.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	0,  // 6: domain.expenditure.v1.ReadSupplierContractPriceScheduleLineResponse.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	17, // 7: domain.expenditure.v1.ReadSupplierContractPriceScheduleLineResponse.error:type_name -> domain.common.v1.Error
	0,  // 8: domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineRequest.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	0,  // 9: domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineResponse.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	17, // 10: domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineResponse.error:type_name -> domain.common.v1.Error
	0,  // 11: domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineRequest.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	17, // 12: domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineResponse.error:type_name -> domain.common.v1.Error
	18, // 13: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesRequest.search:type_name -> domain.common.v1.SearchRequest
	19, // 14: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesRequest.filters:type_name -> domain.common.v1.FilterRequest
	20, // 15: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesRequest.sort:type_name -> domain.common.v1.SortRequest
	21, // 16: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesRequest.pagination:type_name -> domain.common.v1.PaginationRequest
	0,  // 17: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesResponse.data:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	17, // 18: domain.expenditure.v1.ListSupplierContractPriceScheduleLinesResponse.error:type_name -> domain.common.v1.Error
	21, // 19: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataRequest.pagination:type_name -> domain.common.v1.PaginationRequest
	19, // 20: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataRequest.filters:type_name -> domain.common.v1.FilterRequest
	20, // 21: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataRequest.sort:type_name -> domain.common.v1.SortRequest
	18, // 22: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataRequest.search:type_name -> domain.common.v1.SearchRequest
	0,  // 23: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataResponse.supplier_contract_price_schedule_line_list:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	22, // 24: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataResponse.pagination:type_name -> domain.common.v1.PaginationResponse
	23, // 25: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataResponse.search_results:type_name -> domain.common.v1.SearchResult
	17, // 26: domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataResponse.error:type_name -> domain.common.v1.Error
	0,  // 27: domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataResponse.supplier_contract_price_schedule_line:type_name -> domain.expenditure.v1.SupplierContractPriceScheduleLine
	17, // 28: domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataResponse.error:type_name -> domain.common.v1.Error
	1,  // 29: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.CreateSupplierContractPriceScheduleLine:input_type -> domain.expenditure.v1.CreateSupplierContractPriceScheduleLineRequest
	3,  // 30: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.ReadSupplierContractPriceScheduleLine:input_type -> domain.expenditure.v1.ReadSupplierContractPriceScheduleLineRequest
	5,  // 31: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.UpdateSupplierContractPriceScheduleLine:input_type -> domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineRequest
	7,  // 32: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.DeleteSupplierContractPriceScheduleLine:input_type -> domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineRequest
	9,  // 33: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.ListSupplierContractPriceScheduleLines:input_type -> domain.expenditure.v1.ListSupplierContractPriceScheduleLinesRequest
	11, // 34: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.GetSupplierContractPriceScheduleLineListPageData:input_type -> domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataRequest
	13, // 35: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.GetSupplierContractPriceScheduleLineItemPageData:input_type -> domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataRequest
	2,  // 36: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.CreateSupplierContractPriceScheduleLine:output_type -> domain.expenditure.v1.CreateSupplierContractPriceScheduleLineResponse
	4,  // 37: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.ReadSupplierContractPriceScheduleLine:output_type -> domain.expenditure.v1.ReadSupplierContractPriceScheduleLineResponse
	6,  // 38: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.UpdateSupplierContractPriceScheduleLine:output_type -> domain.expenditure.v1.UpdateSupplierContractPriceScheduleLineResponse
	8,  // 39: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.DeleteSupplierContractPriceScheduleLine:output_type -> domain.expenditure.v1.DeleteSupplierContractPriceScheduleLineResponse
	10, // 40: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.ListSupplierContractPriceScheduleLines:output_type -> domain.expenditure.v1.ListSupplierContractPriceScheduleLinesResponse
	12, // 41: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.GetSupplierContractPriceScheduleLineListPageData:output_type -> domain.expenditure.v1.GetSupplierContractPriceScheduleLineListPageDataResponse
	14, // 42: domain.expenditure.v1.SupplierContractPriceScheduleLineDomainService.GetSupplierContractPriceScheduleLineItemPageData:output_type -> domain.expenditure.v1.GetSupplierContractPriceScheduleLineItemPageDataResponse
	36, // [36:43] is the sub-list for method output_type
	29, // [29:36] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() {
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_init()
}
func file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_init() {
	if File_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto != nil {
		return
	}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[0].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[2].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[4].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[6].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[8].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[9].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[10].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[11].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[12].OneofWrappers = []any{}
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDesc), len(file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_goTypes,
		DependencyIndexes: file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_depIdxs,
		MessageInfos:      file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_msgTypes,
	}.Build()
	File_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto = out.File
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_goTypes = nil
	file_domain_expenditure_supplier_contract_price_schedule_line_supplier_contract_price_schedule_line_proto_depIdxs = nil
}
