// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/entity/admin/dashboard/dashboard.proto

package dashboardv1

import (
	common "github.com/erniealice/esqyma/pkg/schema/v1/domain/common"
	workspace_user_role "github.com/erniealice/esqyma/pkg/schema/v1/domain/entity/workspace_user_role"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminStats are the four stat cards: Workspace Users / Roles / Permissions
// / Recent Role Changes (7d).
type AdminStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceUsers      int64                  `protobuf:"varint,1,opt,name=workspace_users,json=workspaceUsers,proto3" json:"workspace_users,omitempty"`
	Roles               int64                  `protobuf:"varint,2,opt,name=roles,proto3" json:"roles,omitempty"`
	Permissions         int64                  `protobuf:"varint,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	RecentRoleChanges7D int64                  `protobuf:"varint,4,opt,name=recent_role_changes7d,json=recentRoleChanges7d,proto3" json:"recent_role_changes7d,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminStats) Reset() {
	*x = AdminStats{}
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStats) ProtoMessage() {}

func (x *AdminStats) ProtoReflect() protoreflect.Message {
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStats.ProtoReflect.Descriptor instead.
func (*AdminStats) Descriptor() ([]byte, []int) {
	return file_domain_entity_admin_dashboard_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *AdminStats) GetWorkspaceUsers() int64 {
	if x != nil {
		return x.WorkspaceUsers
	}
	return 0
}

func (x *AdminStats) GetRoles() int64 {
	if x != nil {
		return x.Roles
	}
	return 0
}

func (x *AdminStats) GetPermissions() int64 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

func (x *AdminStats) GetRecentRoleChanges7D() int64 {
	if x != nil {
		return x.RecentRoleChanges7D
	}
	return 0
}

// RolePermissionCount is one row of the "roles by permission count" table widget.
type RolePermissionCount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoleId          string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName        string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	PermissionCount int64                  `protobuf:"varint,3,opt,name=permission_count,json=permissionCount,proto3" json:"permission_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RolePermissionCount) Reset() {
	*x = RolePermissionCount{}
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionCount) ProtoMessage() {}

func (x *RolePermissionCount) ProtoReflect() protoreflect.Message {
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionCount.ProtoReflect.Descriptor instead.
func (*RolePermissionCount) Descriptor() ([]byte, []int) {
	return file_domain_entity_admin_dashboard_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *RolePermissionCount) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RolePermissionCount) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RolePermissionCount) GetPermissionCount() int64 {
	if x != nil {
		return x.PermissionCount
	}
	return 0
}

// GetAdminDashboardRequest is the input for the admin dashboard use case.
type GetAdminDashboardRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// now_millis is used for time-relative stats (e.g. 7-day activity counts).
	// Zero means "use server time".
	NowMillis     *int64 `protobuf:"varint,2,opt,name=now_millis,json=nowMillis,proto3,oneof" json:"now_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminDashboardRequest) Reset() {
	*x = GetAdminDashboardRequest{}
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminDashboardRequest) ProtoMessage() {}

func (x *GetAdminDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetAdminDashboardRequest) Descriptor() ([]byte, []int) {
	return file_domain_entity_admin_dashboard_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdminDashboardRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetAdminDashboardRequest) GetNowMillis() int64 {
	if x != nil && x.NowMillis != nil {
		return *x.NowMillis
	}
	return 0
}

// GetAdminDashboardResponse is the projected aggregate set the view layer renders.
type GetAdminDashboardResponse struct {
	state             protoimpl.MessageState                   `protogen:"open.v1"`
	Success           bool                                     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error             *common.Error                            `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Stats             *AdminStats                              `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	UsersPerRole      map[string]int64                         `protobuf:"bytes,4,rep,name=users_per_role,json=usersPerRole,proto3" json:"users_per_role,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopRolesByPerms   []*RolePermissionCount                   `protobuf:"bytes,5,rep,name=top_roles_by_perms,json=topRolesByPerms,proto3" json:"top_roles_by_perms,omitempty"`
	RecentAssignments []*workspace_user_role.WorkspaceUserRole `protobuf:"bytes,6,rep,name=recent_assignments,json=recentAssignments,proto3" json:"recent_assignments,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAdminDashboardResponse) Reset() {
	*x = GetAdminDashboardResponse{}
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminDashboardResponse) ProtoMessage() {}

func (x *GetAdminDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetAdminDashboardResponse) Descriptor() ([]byte, []int) {
	return file_domain_entity_admin_dashboard_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminDashboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAdminDashboardResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetAdminDashboardResponse) GetStats() *AdminStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetAdminDashboardResponse) GetUsersPerRole() map[string]int64 {
	if x != nil {
		return x.UsersPerRole
	}
	return nil
}

func (x *GetAdminDashboardResponse) GetTopRolesByPerms() []*RolePermissionCount {
	if x != nil {
		return x.TopRolesByPerms
	}
	return nil
}

func (x *GetAdminDashboardResponse) GetRecentAssignments() []*workspace_user_role.WorkspaceUserRole {
	if x != nil {
		return x.RecentAssignments
	}
	return nil
}

var File_domain_entity_admin_dashboard_dashboard_proto protoreflect.FileDescriptor

const file_domain_entity_admin_dashboard_dashboard_proto_rawDesc = "" +
	"\n" +
	"-domain/entity/admin/dashboard/dashboard.proto\x12 domain.entity.admin.dashboard.v1\x1a\x19domain/common/error.proto\x1a;domain/entity/workspace_user_role/workspace_user_role.proto\"\xa1\x01\n" +
	"\n" +
	"AdminStats\x12'\n" +
	"\x0fworkspace_users\x18\x01 \x01(\x03R\x0eworkspaceUsers\x12\x14\n" +
	"\x05roles\x18\x02 \x01(\x03R\x05roles\x12 \n" +
	"\vpermissions\x18\x03 \x01(\x03R\vpermissions\x122\n" +
	"\x15recent_role_changes7d\x18\x04 \x01(\x03R\x13recentRoleChanges7d\"v\n" +
	"\x13RolePermissionCount\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12)\n" +
	"\x10permission_count\x18\x03 \x01(\x03R\x0fpermissionCount\"p\n" +
	"\x18GetAdminDashboardRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\"\n" +
	"\n" +
	"now_millis\x18\x02 \x01(\x03H\x00R\tnowMillis\x88\x01\x01B\r\n" +
	"\v_now_millis\"\xa5\x04\n" +
	"\x19GetAdminDashboardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01\x12B\n" +
	"\x05stats\x18\x03 \x01(\v2,.domain.entity.admin.dashboard.v1.AdminStatsR\x05stats\x12s\n" +
	"\x0eusers_per_role\x18\x04 \x03(\v2M.domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.UsersPerRoleEntryR\fusersPerRole\x12b\n" +
	"\x12top_roles_by_perms\x18\x05 \x03(\v25.domain.entity.admin.dashboard.v1.RolePermissionCountR\x0ftopRolesByPerms\x12R\n" +
	"\x12recent_assignments\x18\x06 \x03(\v2#.domain.entity.v1.WorkspaceUserRoleR\x11recentAssignments\x1a?\n" +
	"\x11UsersPerRoleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\b\n" +
	"\x06_errorB\xb1\x02\n" +
	"$com.domain.entity.admin.dashboard.v1B\x0eDashboardProtoP\x01ZTgithub.com/erniealice/esqyma/pkg/schema/v1/domain/entity/admin/dashboard;dashboardv1\xa2\x02\x04DEAD\xaa\x02 Domain.Entity.Admin.Dashboard.V1\xca\x02 Domain\\Entity\\Admin\\Dashboard\\V1\xe2\x02,Domain\\Entity\\Admin\\Dashboard\\V1\\GPBMetadata\xea\x02$Domain::Entity::Admin::Dashboard::V1b\x06proto3"

var (
	file_domain_entity_admin_dashboard_dashboard_proto_rawDescOnce sync.Once
	file_domain_entity_admin_dashboard_dashboard_proto_rawDescData []byte
)

func file_domain_entity_admin_dashboard_dashboard_proto_rawDescGZIP() []byte {
	file_domain_entity_admin_dashboard_dashboard_proto_rawDescOnce.Do(func() {
		file_domain_entity_admin_dashboard_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_entity_admin_dashboard_dashboard_proto_rawDesc), len(file_domain_entity_admin_dashboard_dashboard_proto_rawDesc)))
	})
	return file_domain_entity_admin_dashboard_dashboard_proto_rawDescData
}

var file_domain_entity_admin_dashboard_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_domain_entity_admin_dashboard_dashboard_proto_goTypes = []any{
	(*AdminStats)(nil),                // 0: domain.entity.admin.dashboard.v1.AdminStats
	(*RolePermissionCount)(nil),       // 1: domain.entity.admin.dashboard.v1.RolePermissionCount
	(*GetAdminDashboardRequest)(nil),  // 2: domain.entity.admin.dashboard.v1.GetAdminDashboardRequest
	(*GetAdminDashboardResponse)(nil), // 3: domain.entity.admin.dashboard.v1.GetAdminDashboardResponse
	nil,                               // 4: domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.UsersPerRoleEntry
	(*common.Error)(nil),              // 5: domain.common.v1.Error
	(*workspace_user_role.WorkspaceUserRole)(nil), // 6: domain.entity.v1.WorkspaceUserRole
}
var file_domain_entity_admin_dashboard_dashboard_proto_depIdxs = []int32{
	5, // 0: domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.error:type_name -> domain.common.v1.Error
	0, // 1: domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.stats:type_name -> domain.entity.admin.dashboard.v1.AdminStats
	4, // 2: domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.users_per_role:type_name -> domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.UsersPerRoleEntry
	1, // 3: domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.top_roles_by_perms:type_name -> domain.entity.admin.dashboard.v1.RolePermissionCount
	6, // 4: domain.entity.admin.dashboard.v1.GetAdminDashboardResponse.recent_assignments:type_name -> domain.entity.v1.WorkspaceUserRole
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_domain_entity_admin_dashboard_dashboard_proto_init() }
func file_domain_entity_admin_dashboard_dashboard_proto_init() {
	if File_domain_entity_admin_dashboard_dashboard_proto != nil {
		return
	}
	file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[2].OneofWrappers = []any{}
	file_domain_entity_admin_dashboard_dashboard_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_entity_admin_dashboard_dashboard_proto_rawDesc), len(file_domain_entity_admin_dashboard_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_entity_admin_dashboard_dashboard_proto_goTypes,
		DependencyIndexes: file_domain_entity_admin_dashboard_dashboard_proto_depIdxs,
		MessageInfos:      file_domain_entity_admin_dashboard_dashboard_proto_msgTypes,
	}.Build()
	File_domain_entity_admin_dashboard_dashboard_proto = out.File
	file_domain_entity_admin_dashboard_dashboard_proto_goTypes = nil
	file_domain_entity_admin_dashboard_dashboard_proto_depIdxs = nil
}
