-- Migration: initial (down)
-- Dialect: mysql
-- Drop tables in reverse dependency order

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `invoice_attribute`;
DROP TABLE IF EXISTS `invoice`;
DROP TABLE IF EXISTS `payment_attribute`;
DROP TABLE IF EXISTS `payment`;
DROP TABLE IF EXISTS `balance_attribute`;
DROP TABLE IF EXISTS `balance`;
DROP TABLE IF EXISTS `license_history`;
DROP TABLE IF EXISTS `license`;
DROP TABLE IF EXISTS `subscription_attribute`;
DROP TABLE IF EXISTS `subscription`;
DROP TABLE IF EXISTS `payment_profile_payment_method`;
DROP TABLE IF EXISTS `payment_profile`;
DROP TABLE IF EXISTS `event_product`;
DROP TABLE IF EXISTS `event_client`;
DROP TABLE IF EXISTS `delegate_client`;
DROP TABLE IF EXISTS `client_attribute`;
DROP TABLE IF EXISTS `client_category`;
DROP TABLE IF EXISTS `client`;
DROP TABLE IF EXISTS `activity_execution_log`;
DROP TABLE IF EXISTS `activity`;
DROP TABLE IF EXISTS `activity_template`;
DROP TABLE IF EXISTS `stage`;
DROP TABLE IF EXISTS `stage_template`;
DROP TABLE IF EXISTS `workspace_user_role`;
DROP TABLE IF EXISTS `role_permission`;
DROP TABLE IF EXISTS `workspace_user`;
DROP TABLE IF EXISTS `permission`;
DROP TABLE IF EXISTS `role`;
DROP TABLE IF EXISTS `workflow`;
DROP TABLE IF EXISTS `workflow_template`;
DROP TABLE IF EXISTS `workspace`;
DROP TABLE IF EXISTS `staff_attribute`;
DROP TABLE IF EXISTS `delegate_attribute`;
DROP TABLE IF EXISTS `group_attribute`;
DROP TABLE IF EXISTS `location_attribute`;
DROP TABLE IF EXISTS `collection_plan`;
DROP TABLE IF EXISTS `collection_parent`;
DROP TABLE IF EXISTS `collection_attribute`;
DROP TABLE IF EXISTS `price_plan`;
DROP TABLE IF EXISTS `plan_location`;
DROP TABLE IF EXISTS `plan_settings`;
DROP TABLE IF EXISTS `plan_attribute`;
DROP TABLE IF EXISTS `product_collection`;
DROP TABLE IF EXISTS `resource`;
DROP TABLE IF EXISTS `product_plan`;
DROP TABLE IF EXISTS `price_product`;
DROP TABLE IF EXISTS `product_attribute`;
DROP TABLE IF EXISTS `event_settings`;
DROP TABLE IF EXISTS `event_attribute`;
DROP TABLE IF EXISTS `staff`;
DROP TABLE IF EXISTS `delegate`;
DROP TABLE IF EXISTS `admin`;
DROP TABLE IF EXISTS `event_recurrence`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `payment_method`;
DROP TABLE IF EXISTS `location`;
DROP TABLE IF EXISTS `collection`;
DROP TABLE IF EXISTS `event`;
DROP TABLE IF EXISTS `product`;
DROP TABLE IF EXISTS `plan`;
DROP TABLE IF EXISTS `group`;
DROP TABLE IF EXISTS `attribute`;
DROP TABLE IF EXISTS `user`;

SET FOREIGN_KEY_CHECKS = 1;
