// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: domain/procurement/supplier_product_plan/supplier_product_plan.proto

package procurementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupplierProductPlanDomainService_CreateSupplierProductPlan_FullMethodName          = "/domain.procurement.v1.SupplierProductPlanDomainService/CreateSupplierProductPlan"
	SupplierProductPlanDomainService_ReadSupplierProductPlan_FullMethodName            = "/domain.procurement.v1.SupplierProductPlanDomainService/ReadSupplierProductPlan"
	SupplierProductPlanDomainService_UpdateSupplierProductPlan_FullMethodName          = "/domain.procurement.v1.SupplierProductPlanDomainService/UpdateSupplierProductPlan"
	SupplierProductPlanDomainService_DeleteSupplierProductPlan_FullMethodName          = "/domain.procurement.v1.SupplierProductPlanDomainService/DeleteSupplierProductPlan"
	SupplierProductPlanDomainService_ListSupplierProductPlans_FullMethodName           = "/domain.procurement.v1.SupplierProductPlanDomainService/ListSupplierProductPlans"
	SupplierProductPlanDomainService_GetSupplierProductPlanListPageData_FullMethodName = "/domain.procurement.v1.SupplierProductPlanDomainService/GetSupplierProductPlanListPageData"
	SupplierProductPlanDomainService_GetSupplierProductPlanItemPageData_FullMethodName = "/domain.procurement.v1.SupplierProductPlanDomainService/GetSupplierProductPlanItemPageData"
	SupplierProductPlanDomainService_ListBySupplierPlan_FullMethodName                 = "/domain.procurement.v1.SupplierProductPlanDomainService/ListBySupplierPlan"
)

// SupplierProductPlanDomainServiceClient is the client API for SupplierProductPlanDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupplierProductPlanDomainServiceClient interface {
	CreateSupplierProductPlan(ctx context.Context, in *CreateSupplierProductPlanRequest, opts ...grpc.CallOption) (*CreateSupplierProductPlanResponse, error)
	ReadSupplierProductPlan(ctx context.Context, in *ReadSupplierProductPlanRequest, opts ...grpc.CallOption) (*ReadSupplierProductPlanResponse, error)
	UpdateSupplierProductPlan(ctx context.Context, in *UpdateSupplierProductPlanRequest, opts ...grpc.CallOption) (*UpdateSupplierProductPlanResponse, error)
	DeleteSupplierProductPlan(ctx context.Context, in *DeleteSupplierProductPlanRequest, opts ...grpc.CallOption) (*DeleteSupplierProductPlanResponse, error)
	ListSupplierProductPlans(ctx context.Context, in *ListSupplierProductPlansRequest, opts ...grpc.CallOption) (*ListSupplierProductPlansResponse, error)
	GetSupplierProductPlanListPageData(ctx context.Context, in *GetSupplierProductPlanListPageDataRequest, opts ...grpc.CallOption) (*GetSupplierProductPlanListPageDataResponse, error)
	GetSupplierProductPlanItemPageData(ctx context.Context, in *GetSupplierProductPlanItemPageDataRequest, opts ...grpc.CallOption) (*GetSupplierProductPlanItemPageDataResponse, error)
	// Reverse index: product plans for a given supplier plan.
	ListBySupplierPlan(ctx context.Context, in *ListSupplierProductPlansBySupplierPlanRequest, opts ...grpc.CallOption) (*ListSupplierProductPlansBySupplierPlanResponse, error)
}

type supplierProductPlanDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupplierProductPlanDomainServiceClient(cc grpc.ClientConnInterface) SupplierProductPlanDomainServiceClient {
	return &supplierProductPlanDomainServiceClient{cc}
}

func (c *supplierProductPlanDomainServiceClient) CreateSupplierProductPlan(ctx context.Context, in *CreateSupplierProductPlanRequest, opts ...grpc.CallOption) (*CreateSupplierProductPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupplierProductPlanResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_CreateSupplierProductPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierProductPlanDomainServiceClient) ReadSupplierProductPlan(ctx context.Context, in *ReadSupplierProductPlanRequest, opts ...grpc.CallOption) (*ReadSupplierProductPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSupplierProductPlanResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_ReadSupplierProductPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierProductPlanDomainServiceClient) UpdateSupplierProductPlan(ctx context.Context, in *UpdateSupplierProductPlanRequest, opts ...grpc.CallOption) (*UpdateSupplierProductPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSupplierProductPlanResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_UpdateSupplierProductPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierProductPlanDomainServiceClient) DeleteSupplierProductPlan(ctx context.Context, in *DeleteSupplierProductPlanRequest, opts ...grpc.CallOption) (*DeleteSupplierProductPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSupplierProductPlanResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_DeleteSupplierProductPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierProductPlanDomainServiceClient) ListSupplierProductPlans(ctx context.Context, in *ListSupplierProductPlansRequest, opts ...grpc.CallOption) (*ListSupplierProductPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupplierProductPlansResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_ListSupplierProductPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierProductPlanDomainServiceClient) GetSupplierProductPlanListPageData(ctx context.Context, in *GetSupplierProductPlanListPageDataRequest, opts ...grpc.CallOption) (*GetSupplierProductPlanListPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupplierProductPlanListPageDataResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_GetSupplierProductPlanListPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierProductPlanDomainServiceClient) GetSupplierProductPlanItemPageData(ctx context.Context, in *GetSupplierProductPlanItemPageDataRequest, opts ...grpc.CallOption) (*GetSupplierProductPlanItemPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupplierProductPlanItemPageDataResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_GetSupplierProductPlanItemPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierProductPlanDomainServiceClient) ListBySupplierPlan(ctx context.Context, in *ListSupplierProductPlansBySupplierPlanRequest, opts ...grpc.CallOption) (*ListSupplierProductPlansBySupplierPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupplierProductPlansBySupplierPlanResponse)
	err := c.cc.Invoke(ctx, SupplierProductPlanDomainService_ListBySupplierPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupplierProductPlanDomainServiceServer is the server API for SupplierProductPlanDomainService service.
// All implementations must embed UnimplementedSupplierProductPlanDomainServiceServer
// for forward compatibility.
type SupplierProductPlanDomainServiceServer interface {
	CreateSupplierProductPlan(context.Context, *CreateSupplierProductPlanRequest) (*CreateSupplierProductPlanResponse, error)
	ReadSupplierProductPlan(context.Context, *ReadSupplierProductPlanRequest) (*ReadSupplierProductPlanResponse, error)
	UpdateSupplierProductPlan(context.Context, *UpdateSupplierProductPlanRequest) (*UpdateSupplierProductPlanResponse, error)
	DeleteSupplierProductPlan(context.Context, *DeleteSupplierProductPlanRequest) (*DeleteSupplierProductPlanResponse, error)
	ListSupplierProductPlans(context.Context, *ListSupplierProductPlansRequest) (*ListSupplierProductPlansResponse, error)
	GetSupplierProductPlanListPageData(context.Context, *GetSupplierProductPlanListPageDataRequest) (*GetSupplierProductPlanListPageDataResponse, error)
	GetSupplierProductPlanItemPageData(context.Context, *GetSupplierProductPlanItemPageDataRequest) (*GetSupplierProductPlanItemPageDataResponse, error)
	// Reverse index: product plans for a given supplier plan.
	ListBySupplierPlan(context.Context, *ListSupplierProductPlansBySupplierPlanRequest) (*ListSupplierProductPlansBySupplierPlanResponse, error)
	mustEmbedUnimplementedSupplierProductPlanDomainServiceServer()
}

// UnimplementedSupplierProductPlanDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupplierProductPlanDomainServiceServer struct{}

func (UnimplementedSupplierProductPlanDomainServiceServer) CreateSupplierProductPlan(context.Context, *CreateSupplierProductPlanRequest) (*CreateSupplierProductPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSupplierProductPlan not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) ReadSupplierProductPlan(context.Context, *ReadSupplierProductPlanRequest) (*ReadSupplierProductPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSupplierProductPlan not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) UpdateSupplierProductPlan(context.Context, *UpdateSupplierProductPlanRequest) (*UpdateSupplierProductPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSupplierProductPlan not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) DeleteSupplierProductPlan(context.Context, *DeleteSupplierProductPlanRequest) (*DeleteSupplierProductPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSupplierProductPlan not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) ListSupplierProductPlans(context.Context, *ListSupplierProductPlansRequest) (*ListSupplierProductPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSupplierProductPlans not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) GetSupplierProductPlanListPageData(context.Context, *GetSupplierProductPlanListPageDataRequest) (*GetSupplierProductPlanListPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupplierProductPlanListPageData not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) GetSupplierProductPlanItemPageData(context.Context, *GetSupplierProductPlanItemPageDataRequest) (*GetSupplierProductPlanItemPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupplierProductPlanItemPageData not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) ListBySupplierPlan(context.Context, *ListSupplierProductPlansBySupplierPlanRequest) (*ListSupplierProductPlansBySupplierPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBySupplierPlan not implemented")
}
func (UnimplementedSupplierProductPlanDomainServiceServer) mustEmbedUnimplementedSupplierProductPlanDomainServiceServer() {
}
func (UnimplementedSupplierProductPlanDomainServiceServer) testEmbeddedByValue() {}

// UnsafeSupplierProductPlanDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupplierProductPlanDomainServiceServer will
// result in compilation errors.
type UnsafeSupplierProductPlanDomainServiceServer interface {
	mustEmbedUnimplementedSupplierProductPlanDomainServiceServer()
}

func RegisterSupplierProductPlanDomainServiceServer(s grpc.ServiceRegistrar, srv SupplierProductPlanDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedSupplierProductPlanDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupplierProductPlanDomainService_ServiceDesc, srv)
}

func _SupplierProductPlanDomainService_CreateSupplierProductPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierProductPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).CreateSupplierProductPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_CreateSupplierProductPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).CreateSupplierProductPlan(ctx, req.(*CreateSupplierProductPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierProductPlanDomainService_ReadSupplierProductPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSupplierProductPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).ReadSupplierProductPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_ReadSupplierProductPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).ReadSupplierProductPlan(ctx, req.(*ReadSupplierProductPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierProductPlanDomainService_UpdateSupplierProductPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSupplierProductPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).UpdateSupplierProductPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_UpdateSupplierProductPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).UpdateSupplierProductPlan(ctx, req.(*UpdateSupplierProductPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierProductPlanDomainService_DeleteSupplierProductPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSupplierProductPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).DeleteSupplierProductPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_DeleteSupplierProductPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).DeleteSupplierProductPlan(ctx, req.(*DeleteSupplierProductPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierProductPlanDomainService_ListSupplierProductPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupplierProductPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).ListSupplierProductPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_ListSupplierProductPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).ListSupplierProductPlans(ctx, req.(*ListSupplierProductPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierProductPlanDomainService_GetSupplierProductPlanListPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplierProductPlanListPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).GetSupplierProductPlanListPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_GetSupplierProductPlanListPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).GetSupplierProductPlanListPageData(ctx, req.(*GetSupplierProductPlanListPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierProductPlanDomainService_GetSupplierProductPlanItemPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupplierProductPlanItemPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).GetSupplierProductPlanItemPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_GetSupplierProductPlanItemPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).GetSupplierProductPlanItemPageData(ctx, req.(*GetSupplierProductPlanItemPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierProductPlanDomainService_ListBySupplierPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupplierProductPlansBySupplierPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierProductPlanDomainServiceServer).ListBySupplierPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierProductPlanDomainService_ListBySupplierPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierProductPlanDomainServiceServer).ListBySupplierPlan(ctx, req.(*ListSupplierProductPlansBySupplierPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupplierProductPlanDomainService_ServiceDesc is the grpc.ServiceDesc for SupplierProductPlanDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupplierProductPlanDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.procurement.v1.SupplierProductPlanDomainService",
	HandlerType: (*SupplierProductPlanDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSupplierProductPlan",
			Handler:    _SupplierProductPlanDomainService_CreateSupplierProductPlan_Handler,
		},
		{
			MethodName: "ReadSupplierProductPlan",
			Handler:    _SupplierProductPlanDomainService_ReadSupplierProductPlan_Handler,
		},
		{
			MethodName: "UpdateSupplierProductPlan",
			Handler:    _SupplierProductPlanDomainService_UpdateSupplierProductPlan_Handler,
		},
		{
			MethodName: "DeleteSupplierProductPlan",
			Handler:    _SupplierProductPlanDomainService_DeleteSupplierProductPlan_Handler,
		},
		{
			MethodName: "ListSupplierProductPlans",
			Handler:    _SupplierProductPlanDomainService_ListSupplierProductPlans_Handler,
		},
		{
			MethodName: "GetSupplierProductPlanListPageData",
			Handler:    _SupplierProductPlanDomainService_GetSupplierProductPlanListPageData_Handler,
		},
		{
			MethodName: "GetSupplierProductPlanItemPageData",
			Handler:    _SupplierProductPlanDomainService_GetSupplierProductPlanItemPageData_Handler,
		},
		{
			MethodName: "ListBySupplierPlan",
			Handler:    _SupplierProductPlanDomainService_ListBySupplierPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/procurement/supplier_product_plan/supplier_product_plan.proto",
}
