syntax = "proto3";

package domain.product.v1;


option go_package = "github.com/erniealice/esqyma/golang/v1/domain/product/plan_group_plan";

import "domain/common/error.proto";
import "domain/common/pagination.proto";
import "domain/common/filter.proto";
import "domain/common/sort.proto";
import "domain/common/search.proto";
import "options/db.proto";

message PlanGroupPlan {
  option (options.v1.table).table = true;
  option (options.v1.table).unique_together = "plan_group_id,plan_id";
  string id = 1;
  string plan_group_id = 2 [(options.v1.db).references = "plan_group", (options.v1.db).index = true];
  string plan_id = 3 [(options.v1.db).references = "plan", (options.v1.db).index = true];
  optional int64 date_created = 4;
  optional string date_created_string = 5 [(options.v1.db).ignore = true];
  optional int64 date_modified = 6;
  optional string date_modified_string = 7 [(options.v1.db).ignore = true];
  bool active = 8 [(options.v1.db).default = "true"];
  string workspace_id = 9 [(options.v1.db).references = "workspace", (options.v1.db).index = true];
  optional int32 sequence_order = 10;
}

service PlanGroupPlanDomainService {
  rpc CreatePlanGroupPlan(CreatePlanGroupPlanRequest) returns (CreatePlanGroupPlanResponse);
  rpc ReadPlanGroupPlan(ReadPlanGroupPlanRequest) returns (ReadPlanGroupPlanResponse);
  rpc UpdatePlanGroupPlan(UpdatePlanGroupPlanRequest) returns (UpdatePlanGroupPlanResponse);
  rpc DeletePlanGroupPlan(DeletePlanGroupPlanRequest) returns (DeletePlanGroupPlanResponse);
  rpc ListPlanGroupPlans(ListPlanGroupPlansRequest) returns (ListPlanGroupPlansResponse);
  rpc GetPlanGroupPlanListPageData(GetPlanGroupPlanListPageDataRequest)
    returns (GetPlanGroupPlanListPageDataResponse);
  rpc GetPlanGroupPlanItemPageData(GetPlanGroupPlanItemPageDataRequest)
    returns (GetPlanGroupPlanItemPageDataResponse);
}

message CreatePlanGroupPlanRequest {
  PlanGroupPlan data = 1;
}

message CreatePlanGroupPlanResponse {
  repeated PlanGroupPlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message ReadPlanGroupPlanRequest {
  PlanGroupPlan data = 1;
}

message ReadPlanGroupPlanResponse {
  repeated PlanGroupPlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message UpdatePlanGroupPlanRequest {
  PlanGroupPlan data = 1;
}

message UpdatePlanGroupPlanResponse {
  repeated PlanGroupPlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message DeletePlanGroupPlanRequest {
  PlanGroupPlan data = 1;
}

message DeletePlanGroupPlanResponse {
  bool success = 1;
  optional domain.common.v1.Error error = 2;
}

message ListPlanGroupPlansRequest {
  optional domain.common.v1.SearchRequest search = 1;
  optional domain.common.v1.FilterRequest filters = 2;
  optional domain.common.v1.SortRequest sort = 3;
  optional domain.common.v1.PaginationRequest pagination = 4;
}

message ListPlanGroupPlansResponse {
  repeated PlanGroupPlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message GetPlanGroupPlanListPageDataRequest {
  optional domain.common.v1.SearchRequest search = 1;
  optional domain.common.v1.FilterRequest filters = 2;
  optional domain.common.v1.SortRequest sort = 3;
  optional domain.common.v1.PaginationRequest pagination = 4;
}

message GetPlanGroupPlanListPageDataResponse {
  repeated PlanGroupPlan plan_group_plan_list = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
  optional domain.common.v1.PaginationResponse pagination = 4;
  repeated domain.common.v1.SearchResult search_results = 5;
}

message GetPlanGroupPlanItemPageDataRequest {
  string plan_group_plan_id = 1;
}

message GetPlanGroupPlanItemPageDataResponse {
  PlanGroupPlan plan_group_plan = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}
