// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: domain/entity/role_permission/role_permission.proto

package entityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RolePermissionDomainService_CreateRolePermission_FullMethodName          = "/domain.entity.v1.RolePermissionDomainService/CreateRolePermission"
	RolePermissionDomainService_ReadRolePermission_FullMethodName            = "/domain.entity.v1.RolePermissionDomainService/ReadRolePermission"
	RolePermissionDomainService_UpdateRolePermission_FullMethodName          = "/domain.entity.v1.RolePermissionDomainService/UpdateRolePermission"
	RolePermissionDomainService_DeleteRolePermission_FullMethodName          = "/domain.entity.v1.RolePermissionDomainService/DeleteRolePermission"
	RolePermissionDomainService_ListRolePermissions_FullMethodName           = "/domain.entity.v1.RolePermissionDomainService/ListRolePermissions"
	RolePermissionDomainService_GetRolePermissionListPageData_FullMethodName = "/domain.entity.v1.RolePermissionDomainService/GetRolePermissionListPageData"
	RolePermissionDomainService_GetRolePermissionItemPageData_FullMethodName = "/domain.entity.v1.RolePermissionDomainService/GetRolePermissionItemPageData"
)

// RolePermissionDomainServiceClient is the client API for RolePermissionDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RolePermissionDomainServiceClient interface {
	CreateRolePermission(ctx context.Context, in *CreateRolePermissionRequest, opts ...grpc.CallOption) (*CreateRolePermissionResponse, error)
	ReadRolePermission(ctx context.Context, in *ReadRolePermissionRequest, opts ...grpc.CallOption) (*ReadRolePermissionResponse, error)
	UpdateRolePermission(ctx context.Context, in *UpdateRolePermissionRequest, opts ...grpc.CallOption) (*UpdateRolePermissionResponse, error)
	DeleteRolePermission(ctx context.Context, in *DeleteRolePermissionRequest, opts ...grpc.CallOption) (*DeleteRolePermissionResponse, error)
	ListRolePermissions(ctx context.Context, in *ListRolePermissionsRequest, opts ...grpc.CallOption) (*ListRolePermissionsResponse, error)
	// NEW: Enhanced list with pagination, filtering, sorting, search
	GetRolePermissionListPageData(ctx context.Context, in *GetRolePermissionListPageDataRequest, opts ...grpc.CallOption) (*GetRolePermissionListPageDataResponse, error)
	// NEW: Enhanced item view with related data
	GetRolePermissionItemPageData(ctx context.Context, in *GetRolePermissionItemPageDataRequest, opts ...grpc.CallOption) (*GetRolePermissionItemPageDataResponse, error)
}

type rolePermissionDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRolePermissionDomainServiceClient(cc grpc.ClientConnInterface) RolePermissionDomainServiceClient {
	return &rolePermissionDomainServiceClient{cc}
}

func (c *rolePermissionDomainServiceClient) CreateRolePermission(ctx context.Context, in *CreateRolePermissionRequest, opts ...grpc.CallOption) (*CreateRolePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRolePermissionResponse)
	err := c.cc.Invoke(ctx, RolePermissionDomainService_CreateRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionDomainServiceClient) ReadRolePermission(ctx context.Context, in *ReadRolePermissionRequest, opts ...grpc.CallOption) (*ReadRolePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadRolePermissionResponse)
	err := c.cc.Invoke(ctx, RolePermissionDomainService_ReadRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionDomainServiceClient) UpdateRolePermission(ctx context.Context, in *UpdateRolePermissionRequest, opts ...grpc.CallOption) (*UpdateRolePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRolePermissionResponse)
	err := c.cc.Invoke(ctx, RolePermissionDomainService_UpdateRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionDomainServiceClient) DeleteRolePermission(ctx context.Context, in *DeleteRolePermissionRequest, opts ...grpc.CallOption) (*DeleteRolePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRolePermissionResponse)
	err := c.cc.Invoke(ctx, RolePermissionDomainService_DeleteRolePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionDomainServiceClient) ListRolePermissions(ctx context.Context, in *ListRolePermissionsRequest, opts ...grpc.CallOption) (*ListRolePermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolePermissionsResponse)
	err := c.cc.Invoke(ctx, RolePermissionDomainService_ListRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionDomainServiceClient) GetRolePermissionListPageData(ctx context.Context, in *GetRolePermissionListPageDataRequest, opts ...grpc.CallOption) (*GetRolePermissionListPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionListPageDataResponse)
	err := c.cc.Invoke(ctx, RolePermissionDomainService_GetRolePermissionListPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolePermissionDomainServiceClient) GetRolePermissionItemPageData(ctx context.Context, in *GetRolePermissionItemPageDataRequest, opts ...grpc.CallOption) (*GetRolePermissionItemPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionItemPageDataResponse)
	err := c.cc.Invoke(ctx, RolePermissionDomainService_GetRolePermissionItemPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolePermissionDomainServiceServer is the server API for RolePermissionDomainService service.
// All implementations must embed UnimplementedRolePermissionDomainServiceServer
// for forward compatibility.
type RolePermissionDomainServiceServer interface {
	CreateRolePermission(context.Context, *CreateRolePermissionRequest) (*CreateRolePermissionResponse, error)
	ReadRolePermission(context.Context, *ReadRolePermissionRequest) (*ReadRolePermissionResponse, error)
	UpdateRolePermission(context.Context, *UpdateRolePermissionRequest) (*UpdateRolePermissionResponse, error)
	DeleteRolePermission(context.Context, *DeleteRolePermissionRequest) (*DeleteRolePermissionResponse, error)
	ListRolePermissions(context.Context, *ListRolePermissionsRequest) (*ListRolePermissionsResponse, error)
	// NEW: Enhanced list with pagination, filtering, sorting, search
	GetRolePermissionListPageData(context.Context, *GetRolePermissionListPageDataRequest) (*GetRolePermissionListPageDataResponse, error)
	// NEW: Enhanced item view with related data
	GetRolePermissionItemPageData(context.Context, *GetRolePermissionItemPageDataRequest) (*GetRolePermissionItemPageDataResponse, error)
	mustEmbedUnimplementedRolePermissionDomainServiceServer()
}

// UnimplementedRolePermissionDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRolePermissionDomainServiceServer struct{}

func (UnimplementedRolePermissionDomainServiceServer) CreateRolePermission(context.Context, *CreateRolePermissionRequest) (*CreateRolePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRolePermission not implemented")
}
func (UnimplementedRolePermissionDomainServiceServer) ReadRolePermission(context.Context, *ReadRolePermissionRequest) (*ReadRolePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadRolePermission not implemented")
}
func (UnimplementedRolePermissionDomainServiceServer) UpdateRolePermission(context.Context, *UpdateRolePermissionRequest) (*UpdateRolePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRolePermission not implemented")
}
func (UnimplementedRolePermissionDomainServiceServer) DeleteRolePermission(context.Context, *DeleteRolePermissionRequest) (*DeleteRolePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRolePermission not implemented")
}
func (UnimplementedRolePermissionDomainServiceServer) ListRolePermissions(context.Context, *ListRolePermissionsRequest) (*ListRolePermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRolePermissions not implemented")
}
func (UnimplementedRolePermissionDomainServiceServer) GetRolePermissionListPageData(context.Context, *GetRolePermissionListPageDataRequest) (*GetRolePermissionListPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissionListPageData not implemented")
}
func (UnimplementedRolePermissionDomainServiceServer) GetRolePermissionItemPageData(context.Context, *GetRolePermissionItemPageDataRequest) (*GetRolePermissionItemPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissionItemPageData not implemented")
}
func (UnimplementedRolePermissionDomainServiceServer) mustEmbedUnimplementedRolePermissionDomainServiceServer() {
}
func (UnimplementedRolePermissionDomainServiceServer) testEmbeddedByValue() {}

// UnsafeRolePermissionDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RolePermissionDomainServiceServer will
// result in compilation errors.
type UnsafeRolePermissionDomainServiceServer interface {
	mustEmbedUnimplementedRolePermissionDomainServiceServer()
}

func RegisterRolePermissionDomainServiceServer(s grpc.ServiceRegistrar, srv RolePermissionDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedRolePermissionDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RolePermissionDomainService_ServiceDesc, srv)
}

func _RolePermissionDomainService_CreateRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionDomainServiceServer).CreateRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionDomainService_CreateRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionDomainServiceServer).CreateRolePermission(ctx, req.(*CreateRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermissionDomainService_ReadRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionDomainServiceServer).ReadRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionDomainService_ReadRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionDomainServiceServer).ReadRolePermission(ctx, req.(*ReadRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermissionDomainService_UpdateRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionDomainServiceServer).UpdateRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionDomainService_UpdateRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionDomainServiceServer).UpdateRolePermission(ctx, req.(*UpdateRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermissionDomainService_DeleteRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionDomainServiceServer).DeleteRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionDomainService_DeleteRolePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionDomainServiceServer).DeleteRolePermission(ctx, req.(*DeleteRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermissionDomainService_ListRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionDomainServiceServer).ListRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionDomainService_ListRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionDomainServiceServer).ListRolePermissions(ctx, req.(*ListRolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermissionDomainService_GetRolePermissionListPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionListPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionDomainServiceServer).GetRolePermissionListPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionDomainService_GetRolePermissionListPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionDomainServiceServer).GetRolePermissionListPageData(ctx, req.(*GetRolePermissionListPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RolePermissionDomainService_GetRolePermissionItemPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionItemPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolePermissionDomainServiceServer).GetRolePermissionItemPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RolePermissionDomainService_GetRolePermissionItemPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolePermissionDomainServiceServer).GetRolePermissionItemPageData(ctx, req.(*GetRolePermissionItemPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RolePermissionDomainService_ServiceDesc is the grpc.ServiceDesc for RolePermissionDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RolePermissionDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.entity.v1.RolePermissionDomainService",
	HandlerType: (*RolePermissionDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRolePermission",
			Handler:    _RolePermissionDomainService_CreateRolePermission_Handler,
		},
		{
			MethodName: "ReadRolePermission",
			Handler:    _RolePermissionDomainService_ReadRolePermission_Handler,
		},
		{
			MethodName: "UpdateRolePermission",
			Handler:    _RolePermissionDomainService_UpdateRolePermission_Handler,
		},
		{
			MethodName: "DeleteRolePermission",
			Handler:    _RolePermissionDomainService_DeleteRolePermission_Handler,
		},
		{
			MethodName: "ListRolePermissions",
			Handler:    _RolePermissionDomainService_ListRolePermissions_Handler,
		},
		{
			MethodName: "GetRolePermissionListPageData",
			Handler:    _RolePermissionDomainService_GetRolePermissionListPageData_Handler,
		},
		{
			MethodName: "GetRolePermissionItemPageData",
			Handler:    _RolePermissionDomainService_GetRolePermissionItemPageData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/entity/role_permission/role_permission.proto",
}
