BEGIN;
ALTER TABLE job ADD COLUMN IF NOT EXISTS cycle_index INTEGER;
ALTER TABLE job ADD COLUMN IF NOT EXISTS cycle_period_start TEXT;
ALTER TABLE job ADD COLUMN IF NOT EXISTS cycle_period_end TEXT;
COMMIT;
