BEGIN;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS password_reset_token TEXT;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS password_reset_expires TIMESTAMPTZ;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;
COMMIT;
