// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/tax/tax_registration_kind/tax_registration_kind.proto

package taxv1

import (
	common "github.com/erniealice/esqyma/pkg/schema/v1/domain/common"
	_ "github.com/erniealice/esqyma/pkg/schema/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PartyRole describes whether this registration kind belongs to the seller
// (workspace / supplier) or the buyer (client). Compute gates on this.
type TaxRegistrationKindPartyRole int32

const (
	TaxRegistrationKindPartyRole_TAX_REGISTRATION_KIND_PARTY_ROLE_UNSPECIFIED TaxRegistrationKindPartyRole = 0
	TaxRegistrationKindPartyRole_TAX_REGISTRATION_KIND_PARTY_ROLE_SELLER      TaxRegistrationKindPartyRole = 1
	TaxRegistrationKindPartyRole_TAX_REGISTRATION_KIND_PARTY_ROLE_BUYER       TaxRegistrationKindPartyRole = 2
)

// Enum value maps for TaxRegistrationKindPartyRole.
var (
	TaxRegistrationKindPartyRole_name = map[int32]string{
		0: "TAX_REGISTRATION_KIND_PARTY_ROLE_UNSPECIFIED",
		1: "TAX_REGISTRATION_KIND_PARTY_ROLE_SELLER",
		2: "TAX_REGISTRATION_KIND_PARTY_ROLE_BUYER",
	}
	TaxRegistrationKindPartyRole_value = map[string]int32{
		"TAX_REGISTRATION_KIND_PARTY_ROLE_UNSPECIFIED": 0,
		"TAX_REGISTRATION_KIND_PARTY_ROLE_SELLER":      1,
		"TAX_REGISTRATION_KIND_PARTY_ROLE_BUYER":       2,
	}
)

func (x TaxRegistrationKindPartyRole) Enum() *TaxRegistrationKindPartyRole {
	p := new(TaxRegistrationKindPartyRole)
	*p = x
	return p
}

func (x TaxRegistrationKindPartyRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxRegistrationKindPartyRole) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes[0].Descriptor()
}

func (TaxRegistrationKindPartyRole) Type() protoreflect.EnumType {
	return &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes[0]
}

func (x TaxRegistrationKindPartyRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxRegistrationKindPartyRole.Descriptor instead.
func (TaxRegistrationKindPartyRole) EnumDescriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{0}
}

// ComputePath describes what happens at revenue-recognition time when a party
// holds an ACTIVE registration of this kind.
//
//	SURCHARGE      → adds a tax line on the invoice (increases cash_amount_expected)
//	WITHHOLDING    → deducts a tax line (decreases cash_amount_expected)
//	PERIODIC_ONLY  → filed on a periodic basis; does NOT produce a RevenueTaxLine
//	NONE           → recorded for audit/status only; no compute effect
type TaxRegistrationKindComputePath int32

const (
	TaxRegistrationKindComputePath_TAX_REGISTRATION_KIND_COMPUTE_PATH_UNSPECIFIED   TaxRegistrationKindComputePath = 0
	TaxRegistrationKindComputePath_TAX_REGISTRATION_KIND_COMPUTE_PATH_SURCHARGE     TaxRegistrationKindComputePath = 1
	TaxRegistrationKindComputePath_TAX_REGISTRATION_KIND_COMPUTE_PATH_WITHHOLDING   TaxRegistrationKindComputePath = 2
	TaxRegistrationKindComputePath_TAX_REGISTRATION_KIND_COMPUTE_PATH_PERIODIC_ONLY TaxRegistrationKindComputePath = 3
	TaxRegistrationKindComputePath_TAX_REGISTRATION_KIND_COMPUTE_PATH_NONE          TaxRegistrationKindComputePath = 4
)

// Enum value maps for TaxRegistrationKindComputePath.
var (
	TaxRegistrationKindComputePath_name = map[int32]string{
		0: "TAX_REGISTRATION_KIND_COMPUTE_PATH_UNSPECIFIED",
		1: "TAX_REGISTRATION_KIND_COMPUTE_PATH_SURCHARGE",
		2: "TAX_REGISTRATION_KIND_COMPUTE_PATH_WITHHOLDING",
		3: "TAX_REGISTRATION_KIND_COMPUTE_PATH_PERIODIC_ONLY",
		4: "TAX_REGISTRATION_KIND_COMPUTE_PATH_NONE",
	}
	TaxRegistrationKindComputePath_value = map[string]int32{
		"TAX_REGISTRATION_KIND_COMPUTE_PATH_UNSPECIFIED":   0,
		"TAX_REGISTRATION_KIND_COMPUTE_PATH_SURCHARGE":     1,
		"TAX_REGISTRATION_KIND_COMPUTE_PATH_WITHHOLDING":   2,
		"TAX_REGISTRATION_KIND_COMPUTE_PATH_PERIODIC_ONLY": 3,
		"TAX_REGISTRATION_KIND_COMPUTE_PATH_NONE":          4,
	}
)

func (x TaxRegistrationKindComputePath) Enum() *TaxRegistrationKindComputePath {
	p := new(TaxRegistrationKindComputePath)
	*p = x
	return p
}

func (x TaxRegistrationKindComputePath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxRegistrationKindComputePath) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes[1].Descriptor()
}

func (TaxRegistrationKindComputePath) Type() protoreflect.EnumType {
	return &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes[1]
}

func (x TaxRegistrationKindComputePath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxRegistrationKindComputePath.Descriptor instead.
func (TaxRegistrationKindComputePath) EnumDescriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{1}
}

// PartyType is the set of entity types a registration kind can be applied to.
// Used to filter the Kind dropdown when creating a TaxRegistration.
type TaxRegistrationKindPartyType int32

const (
	TaxRegistrationKindPartyType_TAX_REGISTRATION_KIND_PARTY_TYPE_UNSPECIFIED TaxRegistrationKindPartyType = 0
	TaxRegistrationKindPartyType_TAX_REGISTRATION_KIND_PARTY_TYPE_CLIENT      TaxRegistrationKindPartyType = 1
	TaxRegistrationKindPartyType_TAX_REGISTRATION_KIND_PARTY_TYPE_WORKSPACE   TaxRegistrationKindPartyType = 2
	TaxRegistrationKindPartyType_TAX_REGISTRATION_KIND_PARTY_TYPE_SUPPLIER    TaxRegistrationKindPartyType = 3
	TaxRegistrationKindPartyType_TAX_REGISTRATION_KIND_PARTY_TYPE_EMPLOYEE    TaxRegistrationKindPartyType = 4
)

// Enum value maps for TaxRegistrationKindPartyType.
var (
	TaxRegistrationKindPartyType_name = map[int32]string{
		0: "TAX_REGISTRATION_KIND_PARTY_TYPE_UNSPECIFIED",
		1: "TAX_REGISTRATION_KIND_PARTY_TYPE_CLIENT",
		2: "TAX_REGISTRATION_KIND_PARTY_TYPE_WORKSPACE",
		3: "TAX_REGISTRATION_KIND_PARTY_TYPE_SUPPLIER",
		4: "TAX_REGISTRATION_KIND_PARTY_TYPE_EMPLOYEE",
	}
	TaxRegistrationKindPartyType_value = map[string]int32{
		"TAX_REGISTRATION_KIND_PARTY_TYPE_UNSPECIFIED": 0,
		"TAX_REGISTRATION_KIND_PARTY_TYPE_CLIENT":      1,
		"TAX_REGISTRATION_KIND_PARTY_TYPE_WORKSPACE":   2,
		"TAX_REGISTRATION_KIND_PARTY_TYPE_SUPPLIER":    3,
		"TAX_REGISTRATION_KIND_PARTY_TYPE_EMPLOYEE":    4,
	}
)

func (x TaxRegistrationKindPartyType) Enum() *TaxRegistrationKindPartyType {
	p := new(TaxRegistrationKindPartyType)
	*p = x
	return p
}

func (x TaxRegistrationKindPartyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxRegistrationKindPartyType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes[2].Descriptor()
}

func (TaxRegistrationKindPartyType) Type() protoreflect.EnumType {
	return &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes[2]
}

func (x TaxRegistrationKindPartyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxRegistrationKindPartyType.Descriptor instead.
func (TaxRegistrationKindPartyType) EnumDescriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{2}
}

// TaxRegistrationKind is a lookup table describing the behavior of a
// registration type in a given jurisdiction. Rows are seed-only (no operator
// CRUD in v1). Adding a new jurisdiction = adding a CSV row.
type TaxRegistrationKind struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DateCreated        *int64                 `protobuf:"varint,2,opt,name=date_created,json=dateCreated,proto3,oneof" json:"date_created,omitempty"`
	DateCreatedString  *string                `protobuf:"bytes,3,opt,name=date_created_string,json=dateCreatedString,proto3,oneof" json:"date_created_string,omitempty"`
	DateModified       *int64                 `protobuf:"varint,4,opt,name=date_modified,json=dateModified,proto3,oneof" json:"date_modified,omitempty"`
	DateModifiedString *string                `protobuf:"bytes,5,opt,name=date_modified_string,json=dateModifiedString,proto3,oneof" json:"date_modified_string,omitempty"`
	Active             bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	// Short unique code identifying this kind (e.g. "PH_VAT_REGISTERED", "PH_TWA")
	Code string `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	// FK to tax_authority — which authority issues this registration
	TaxAuthorityId string `protobuf:"bytes,9,opt,name=tax_authority_id,json=taxAuthorityId,proto3" json:"tax_authority_id,omitempty"`
	// Jurisdiction scope this kind applies to (e.g. "PH-NATIONAL", "UK")
	Jurisdiction string `protobuf:"bytes,10,opt,name=jurisdiction,proto3" json:"jurisdiction,omitempty"`
	// Axis 1: which party role does this apply to?
	PartyRole TaxRegistrationKindPartyRole `protobuf:"varint,11,opt,name=party_role,json=partyRole,proto3,enum=domain.tax.v1.TaxRegistrationKindPartyRole" json:"party_role,omitempty"`
	// Axis 2: what compute behavior does this produce?
	ComputePath TaxRegistrationKindComputePath `protobuf:"varint,12,opt,name=compute_path,json=computePath,proto3,enum=domain.tax.v1.TaxRegistrationKindComputePath" json:"compute_path,omitempty"`
	// Kind of tax rate to look up in tax_rate for the SURCHARGE pass.
	// NULL for WITHHOLDING/PERIODIC_ONLY/NONE kinds (rate comes from TaxClass).
	DefaultRateKind *string `protobuf:"bytes,13,opt,name=default_rate_kind,json=defaultRateKind,proto3,oneof" json:"default_rate_kind,omitempty"`
	// Which party types can hold a registration of this kind.
	// Stored as TEXT[] in the DB. Drives the Kind dropdown filter.
	ApplicablePartyTypes []TaxRegistrationKindPartyType `protobuf:"varint,14,rep,packed,name=applicable_party_types,json=applicablePartyTypes,proto3,enum=domain.tax.v1.TaxRegistrationKindPartyType" json:"applicable_party_types,omitempty"`
	Description          *string                        `protobuf:"bytes,15,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaxRegistrationKind) Reset() {
	*x = TaxRegistrationKind{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaxRegistrationKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaxRegistrationKind) ProtoMessage() {}

func (x *TaxRegistrationKind) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaxRegistrationKind.ProtoReflect.Descriptor instead.
func (*TaxRegistrationKind) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{0}
}

func (x *TaxRegistrationKind) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaxRegistrationKind) GetDateCreated() int64 {
	if x != nil && x.DateCreated != nil {
		return *x.DateCreated
	}
	return 0
}

func (x *TaxRegistrationKind) GetDateCreatedString() string {
	if x != nil && x.DateCreatedString != nil {
		return *x.DateCreatedString
	}
	return ""
}

func (x *TaxRegistrationKind) GetDateModified() int64 {
	if x != nil && x.DateModified != nil {
		return *x.DateModified
	}
	return 0
}

func (x *TaxRegistrationKind) GetDateModifiedString() string {
	if x != nil && x.DateModifiedString != nil {
		return *x.DateModifiedString
	}
	return ""
}

func (x *TaxRegistrationKind) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TaxRegistrationKind) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TaxRegistrationKind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaxRegistrationKind) GetTaxAuthorityId() string {
	if x != nil {
		return x.TaxAuthorityId
	}
	return ""
}

func (x *TaxRegistrationKind) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *TaxRegistrationKind) GetPartyRole() TaxRegistrationKindPartyRole {
	if x != nil {
		return x.PartyRole
	}
	return TaxRegistrationKindPartyRole_TAX_REGISTRATION_KIND_PARTY_ROLE_UNSPECIFIED
}

func (x *TaxRegistrationKind) GetComputePath() TaxRegistrationKindComputePath {
	if x != nil {
		return x.ComputePath
	}
	return TaxRegistrationKindComputePath_TAX_REGISTRATION_KIND_COMPUTE_PATH_UNSPECIFIED
}

func (x *TaxRegistrationKind) GetDefaultRateKind() string {
	if x != nil && x.DefaultRateKind != nil {
		return *x.DefaultRateKind
	}
	return ""
}

func (x *TaxRegistrationKind) GetApplicablePartyTypes() []TaxRegistrationKindPartyType {
	if x != nil {
		return x.ApplicablePartyTypes
	}
	return nil
}

func (x *TaxRegistrationKind) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type ReadTaxRegistrationKindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TaxRegistrationKind   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaxRegistrationKindRequest) Reset() {
	*x = ReadTaxRegistrationKindRequest{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaxRegistrationKindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaxRegistrationKindRequest) ProtoMessage() {}

func (x *ReadTaxRegistrationKindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaxRegistrationKindRequest.ProtoReflect.Descriptor instead.
func (*ReadTaxRegistrationKindRequest) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{1}
}

func (x *ReadTaxRegistrationKindRequest) GetData() *TaxRegistrationKind {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadTaxRegistrationKindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TaxRegistrationKind `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaxRegistrationKindResponse) Reset() {
	*x = ReadTaxRegistrationKindResponse{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaxRegistrationKindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaxRegistrationKindResponse) ProtoMessage() {}

func (x *ReadTaxRegistrationKindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaxRegistrationKindResponse.ProtoReflect.Descriptor instead.
func (*ReadTaxRegistrationKindResponse) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{2}
}

func (x *ReadTaxRegistrationKindResponse) GetData() []*TaxRegistrationKind {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadTaxRegistrationKindResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadTaxRegistrationKindResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListTaxRegistrationKindsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Search        *common.SearchRequest     `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Filters       *common.FilterRequest     `protobuf:"bytes,2,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	Sort          *common.SortRequest       `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaxRegistrationKindsRequest) Reset() {
	*x = ListTaxRegistrationKindsRequest{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaxRegistrationKindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaxRegistrationKindsRequest) ProtoMessage() {}

func (x *ListTaxRegistrationKindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaxRegistrationKindsRequest.ProtoReflect.Descriptor instead.
func (*ListTaxRegistrationKindsRequest) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{3}
}

func (x *ListTaxRegistrationKindsRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ListTaxRegistrationKindsRequest) GetFilters() *common.FilterRequest {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListTaxRegistrationKindsRequest) GetSort() *common.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListTaxRegistrationKindsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListTaxRegistrationKindsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TaxRegistrationKind `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error          `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaxRegistrationKindsResponse) Reset() {
	*x = ListTaxRegistrationKindsResponse{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaxRegistrationKindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaxRegistrationKindsResponse) ProtoMessage() {}

func (x *ListTaxRegistrationKindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaxRegistrationKindsResponse.ProtoReflect.Descriptor instead.
func (*ListTaxRegistrationKindsResponse) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{4}
}

func (x *ListTaxRegistrationKindsResponse) GetData() []*TaxRegistrationKind {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTaxRegistrationKindsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListTaxRegistrationKindsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetTaxRegistrationKindListPageDataRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	Filters       *common.FilterRequest     `protobuf:"bytes,2,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	Sort          *common.SortRequest       `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Search        *common.SearchRequest     `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaxRegistrationKindListPageDataRequest) Reset() {
	*x = GetTaxRegistrationKindListPageDataRequest{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaxRegistrationKindListPageDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaxRegistrationKindListPageDataRequest) ProtoMessage() {}

func (x *GetTaxRegistrationKindListPageDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaxRegistrationKindListPageDataRequest.ProtoReflect.Descriptor instead.
func (*GetTaxRegistrationKindListPageDataRequest) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaxRegistrationKindListPageDataRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTaxRegistrationKindListPageDataRequest) GetFilters() *common.FilterRequest {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetTaxRegistrationKindListPageDataRequest) GetSort() *common.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *GetTaxRegistrationKindListPageDataRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type GetTaxRegistrationKindListPageDataResponse struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	TaxRegistrationKindList []*TaxRegistrationKind     `protobuf:"bytes,1,rep,name=tax_registration_kind_list,json=taxRegistrationKindList,proto3" json:"tax_registration_kind_list,omitempty"`
	Pagination              *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	SearchResults           []*common.SearchResult     `protobuf:"bytes,3,rep,name=search_results,json=searchResults,proto3" json:"search_results,omitempty"`
	Success                 bool                       `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error                   *common.Error              `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetTaxRegistrationKindListPageDataResponse) Reset() {
	*x = GetTaxRegistrationKindListPageDataResponse{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaxRegistrationKindListPageDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaxRegistrationKindListPageDataResponse) ProtoMessage() {}

func (x *GetTaxRegistrationKindListPageDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaxRegistrationKindListPageDataResponse.ProtoReflect.Descriptor instead.
func (*GetTaxRegistrationKindListPageDataResponse) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaxRegistrationKindListPageDataResponse) GetTaxRegistrationKindList() []*TaxRegistrationKind {
	if x != nil {
		return x.TaxRegistrationKindList
	}
	return nil
}

func (x *GetTaxRegistrationKindListPageDataResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetTaxRegistrationKindListPageDataResponse) GetSearchResults() []*common.SearchResult {
	if x != nil {
		return x.SearchResults
	}
	return nil
}

func (x *GetTaxRegistrationKindListPageDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTaxRegistrationKindListPageDataResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetTaxRegistrationKindItemPageDataRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TaxRegistrationKindId string                 `protobuf:"bytes,1,opt,name=tax_registration_kind_id,json=taxRegistrationKindId,proto3" json:"tax_registration_kind_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetTaxRegistrationKindItemPageDataRequest) Reset() {
	*x = GetTaxRegistrationKindItemPageDataRequest{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaxRegistrationKindItemPageDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaxRegistrationKindItemPageDataRequest) ProtoMessage() {}

func (x *GetTaxRegistrationKindItemPageDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaxRegistrationKindItemPageDataRequest.ProtoReflect.Descriptor instead.
func (*GetTaxRegistrationKindItemPageDataRequest) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaxRegistrationKindItemPageDataRequest) GetTaxRegistrationKindId() string {
	if x != nil {
		return x.TaxRegistrationKindId
	}
	return ""
}

type GetTaxRegistrationKindItemPageDataResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TaxRegistrationKind *TaxRegistrationKind   `protobuf:"bytes,1,opt,name=tax_registration_kind,json=taxRegistrationKind,proto3,oneof" json:"tax_registration_kind,omitempty"`
	Success             bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error               *common.Error          `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTaxRegistrationKindItemPageDataResponse) Reset() {
	*x = GetTaxRegistrationKindItemPageDataResponse{}
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaxRegistrationKindItemPageDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaxRegistrationKindItemPageDataResponse) ProtoMessage() {}

func (x *GetTaxRegistrationKindItemPageDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaxRegistrationKindItemPageDataResponse.ProtoReflect.Descriptor instead.
func (*GetTaxRegistrationKindItemPageDataResponse) Descriptor() ([]byte, []int) {
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaxRegistrationKindItemPageDataResponse) GetTaxRegistrationKind() *TaxRegistrationKind {
	if x != nil {
		return x.TaxRegistrationKind
	}
	return nil
}

func (x *GetTaxRegistrationKindItemPageDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTaxRegistrationKindItemPageDataResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_domain_tax_tax_registration_kind_tax_registration_kind_proto protoreflect.FileDescriptor

const file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDesc = "" +
	"\n" +
	"<domain/tax/tax_registration_kind/tax_registration_kind.proto\x12\rdomain.tax.v1\x1a\x19domain/common/error.proto\x1a\x1edomain/common/pagination.proto\x1a\x1adomain/common/filter.proto\x1a\x18domain/common/sort.proto\x1a\x1adomain/common/search.proto\x1a\x10options/db.proto\"\xf7\x06\n" +
	"\x13TaxRegistrationKind\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\fdate_created\x18\x02 \x01(\x03H\x00R\vdateCreated\x88\x01\x01\x123\n" +
	"\x13date_created_string\x18\x03 \x01(\tH\x01R\x11dateCreatedString\x88\x01\x01\x12(\n" +
	"\rdate_modified\x18\x04 \x01(\x03H\x02R\fdateModified\x88\x01\x01\x125\n" +
	"\x14date_modified_string\x18\x05 \x01(\tH\x03R\x12dateModifiedString\x88\x01\x01\x12\"\n" +
	"\x06active\x18\x06 \x01(\bB\n" +
	"\x82\xb5\x18\x06\"\x04trueR\x06active\x12\x1a\n" +
	"\x04code\x18\a \x01(\tB\x06\x82\xb5\x18\x02\x10\x01R\x04code\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12?\n" +
	"\x10tax_authority_id\x18\t \x01(\tB\x15\x82\xb5\x18\x11\n" +
	"\rtax_authority\x18\x01R\x0etaxAuthorityId\x12\"\n" +
	"\fjurisdiction\x18\n" +
	" \x01(\tR\fjurisdiction\x12J\n" +
	"\n" +
	"party_role\x18\v \x01(\x0e2+.domain.tax.v1.TaxRegistrationKindPartyRoleR\tpartyRole\x12P\n" +
	"\fcompute_path\x18\f \x01(\x0e2-.domain.tax.v1.TaxRegistrationKindComputePathR\vcomputePath\x12/\n" +
	"\x11default_rate_kind\x18\r \x01(\tH\x04R\x0fdefaultRateKind\x88\x01\x01\x12a\n" +
	"\x16applicable_party_types\x18\x0e \x03(\x0e2+.domain.tax.v1.TaxRegistrationKindPartyTypeR\x14applicablePartyTypes\x12%\n" +
	"\vdescription\x18\x0f \x01(\tH\x05R\vdescription\x88\x01\x01:\x06\x8a\xb5\x18\x02\b\x01B\x0f\n" +
	"\r_date_createdB\x16\n" +
	"\x14_date_created_stringB\x10\n" +
	"\x0e_date_modifiedB\x17\n" +
	"\x15_date_modified_stringB\x14\n" +
	"\x12_default_rate_kindB\x0e\n" +
	"\f_description\"X\n" +
	"\x1eReadTaxRegistrationKindRequest\x126\n" +
	"\x04data\x18\x01 \x01(\v2\".domain.tax.v1.TaxRegistrationKindR\x04data\"\xb1\x01\n" +
	"\x1fReadTaxRegistrationKindResponse\x126\n" +
	"\x04data\x18\x01 \x03(\v2\".domain.tax.v1.TaxRegistrationKindR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xd0\x02\n" +
	"\x1fListTaxRegistrationKindsRequest\x12<\n" +
	"\x06search\x18\x01 \x01(\v2\x1f.domain.common.v1.SearchRequestH\x00R\x06search\x88\x01\x01\x12>\n" +
	"\afilters\x18\x02 \x01(\v2\x1f.domain.common.v1.FilterRequestH\x01R\afilters\x88\x01\x01\x126\n" +
	"\x04sort\x18\x03 \x01(\v2\x1d.domain.common.v1.SortRequestH\x02R\x04sort\x88\x01\x01\x12H\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2#.domain.common.v1.PaginationRequestH\x03R\n" +
	"pagination\x88\x01\x01B\t\n" +
	"\a_searchB\n" +
	"\n" +
	"\b_filtersB\a\n" +
	"\x05_sortB\r\n" +
	"\v_pagination\"\xb2\x01\n" +
	" ListTaxRegistrationKindsResponse\x126\n" +
	"\x04data\x18\x01 \x03(\v2\".domain.tax.v1.TaxRegistrationKindR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xda\x02\n" +
	")GetTaxRegistrationKindListPageDataRequest\x12H\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.domain.common.v1.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01\x12>\n" +
	"\afilters\x18\x02 \x01(\v2\x1f.domain.common.v1.FilterRequestH\x01R\afilters\x88\x01\x01\x126\n" +
	"\x04sort\x18\x03 \x01(\v2\x1d.domain.common.v1.SortRequestH\x02R\x04sort\x88\x01\x01\x12<\n" +
	"\x06search\x18\x04 \x01(\v2\x1f.domain.common.v1.SearchRequestH\x03R\x06search\x88\x01\x01B\r\n" +
	"\v_paginationB\n" +
	"\n" +
	"\b_filtersB\a\n" +
	"\x05_sortB\t\n" +
	"\a_search\"\x86\x03\n" +
	"*GetTaxRegistrationKindListPageDataResponse\x12_\n" +
	"\x1atax_registration_kind_list\x18\x01 \x03(\v2\".domain.tax.v1.TaxRegistrationKindR\x17taxRegistrationKindList\x12I\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.domain.common.v1.PaginationResponseH\x00R\n" +
	"pagination\x88\x01\x01\x12E\n" +
	"\x0esearch_results\x18\x03 \x03(\v2\x1e.domain.common.v1.SearchResultR\rsearchResults\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x17.domain.common.v1.ErrorH\x01R\x05error\x88\x01\x01B\r\n" +
	"\v_paginationB\b\n" +
	"\x06_error\"d\n" +
	")GetTaxRegistrationKindItemPageDataRequest\x127\n" +
	"\x18tax_registration_kind_id\x18\x01 \x01(\tR\x15taxRegistrationKindId\"\xfb\x01\n" +
	"*GetTaxRegistrationKindItemPageDataResponse\x12[\n" +
	"\x15tax_registration_kind\x18\x01 \x01(\v2\".domain.tax.v1.TaxRegistrationKindH\x00R\x13taxRegistrationKind\x88\x01\x01\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x01R\x05error\x88\x01\x01B\x18\n" +
	"\x16_tax_registration_kindB\b\n" +
	"\x06_error*\xa9\x01\n" +
	"\x1cTaxRegistrationKindPartyRole\x120\n" +
	",TAX_REGISTRATION_KIND_PARTY_ROLE_UNSPECIFIED\x10\x00\x12+\n" +
	"'TAX_REGISTRATION_KIND_PARTY_ROLE_SELLER\x10\x01\x12*\n" +
	"&TAX_REGISTRATION_KIND_PARTY_ROLE_BUYER\x10\x02*\x9d\x02\n" +
	"\x1eTaxRegistrationKindComputePath\x122\n" +
	".TAX_REGISTRATION_KIND_COMPUTE_PATH_UNSPECIFIED\x10\x00\x120\n" +
	",TAX_REGISTRATION_KIND_COMPUTE_PATH_SURCHARGE\x10\x01\x122\n" +
	".TAX_REGISTRATION_KIND_COMPUTE_PATH_WITHHOLDING\x10\x02\x124\n" +
	"0TAX_REGISTRATION_KIND_COMPUTE_PATH_PERIODIC_ONLY\x10\x03\x12+\n" +
	"'TAX_REGISTRATION_KIND_COMPUTE_PATH_NONE\x10\x04*\x8b\x02\n" +
	"\x1cTaxRegistrationKindPartyType\x120\n" +
	",TAX_REGISTRATION_KIND_PARTY_TYPE_UNSPECIFIED\x10\x00\x12+\n" +
	"'TAX_REGISTRATION_KIND_PARTY_TYPE_CLIENT\x10\x01\x12.\n" +
	"*TAX_REGISTRATION_KIND_PARTY_TYPE_WORKSPACE\x10\x02\x12-\n" +
	")TAX_REGISTRATION_KIND_PARTY_TYPE_SUPPLIER\x10\x03\x12-\n" +
	")TAX_REGISTRATION_KIND_PARTY_TYPE_EMPLOYEE\x10\x042\xd1\x04\n" +
	" TaxRegistrationKindDomainService\x12x\n" +
	"\x17ReadTaxRegistrationKind\x12-.domain.tax.v1.ReadTaxRegistrationKindRequest\x1a..domain.tax.v1.ReadTaxRegistrationKindResponse\x12{\n" +
	"\x18ListTaxRegistrationKinds\x12..domain.tax.v1.ListTaxRegistrationKindsRequest\x1a/.domain.tax.v1.ListTaxRegistrationKindsResponse\x12\x99\x01\n" +
	"\"GetTaxRegistrationKindListPageData\x128.domain.tax.v1.GetTaxRegistrationKindListPageDataRequest\x1a9.domain.tax.v1.GetTaxRegistrationKindListPageDataResponse\x12\x99\x01\n" +
	"\"GetTaxRegistrationKindItemPageData\x128.domain.tax.v1.GetTaxRegistrationKindItemPageDataRequest\x1a9.domain.tax.v1.GetTaxRegistrationKindItemPageDataResponseB\xd6\x01\n" +
	"\x11com.domain.tax.v1B\x18TaxRegistrationKindProtoP\x01ZQgithub.com/erniealice/esqyma/pkg/schema/v1/domain/tax/tax_registration_kind;taxv1\xa2\x02\x03DTX\xaa\x02\rDomain.Tax.V1\xca\x02\rDomain\\Tax\\V1\xe2\x02\x19Domain\\Tax\\V1\\GPBMetadata\xea\x02\x0fDomain::Tax::V1b\x06proto3"

var (
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescOnce sync.Once
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescData []byte
)

func file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescGZIP() []byte {
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescOnce.Do(func() {
		file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDesc), len(file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDesc)))
	})
	return file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDescData
}

var file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_domain_tax_tax_registration_kind_tax_registration_kind_proto_goTypes = []any{
	(TaxRegistrationKindPartyRole)(0),                  // 0: domain.tax.v1.TaxRegistrationKindPartyRole
	(TaxRegistrationKindComputePath)(0),                // 1: domain.tax.v1.TaxRegistrationKindComputePath
	(TaxRegistrationKindPartyType)(0),                  // 2: domain.tax.v1.TaxRegistrationKindPartyType
	(*TaxRegistrationKind)(nil),                        // 3: domain.tax.v1.TaxRegistrationKind
	(*ReadTaxRegistrationKindRequest)(nil),             // 4: domain.tax.v1.ReadTaxRegistrationKindRequest
	(*ReadTaxRegistrationKindResponse)(nil),            // 5: domain.tax.v1.ReadTaxRegistrationKindResponse
	(*ListTaxRegistrationKindsRequest)(nil),            // 6: domain.tax.v1.ListTaxRegistrationKindsRequest
	(*ListTaxRegistrationKindsResponse)(nil),           // 7: domain.tax.v1.ListTaxRegistrationKindsResponse
	(*GetTaxRegistrationKindListPageDataRequest)(nil),  // 8: domain.tax.v1.GetTaxRegistrationKindListPageDataRequest
	(*GetTaxRegistrationKindListPageDataResponse)(nil), // 9: domain.tax.v1.GetTaxRegistrationKindListPageDataResponse
	(*GetTaxRegistrationKindItemPageDataRequest)(nil),  // 10: domain.tax.v1.GetTaxRegistrationKindItemPageDataRequest
	(*GetTaxRegistrationKindItemPageDataResponse)(nil), // 11: domain.tax.v1.GetTaxRegistrationKindItemPageDataResponse
	(*common.Error)(nil),                               // 12: domain.common.v1.Error
	(*common.SearchRequest)(nil),                       // 13: domain.common.v1.SearchRequest
	(*common.FilterRequest)(nil),                       // 14: domain.common.v1.FilterRequest
	(*common.SortRequest)(nil),                         // 15: domain.common.v1.SortRequest
	(*common.PaginationRequest)(nil),                   // 16: domain.common.v1.PaginationRequest
	(*common.PaginationResponse)(nil),                  // 17: domain.common.v1.PaginationResponse
	(*common.SearchResult)(nil),                        // 18: domain.common.v1.SearchResult
}
var file_domain_tax_tax_registration_kind_tax_registration_kind_proto_depIdxs = []int32{
	0,  // 0: domain.tax.v1.TaxRegistrationKind.party_role:type_name -> domain.tax.v1.TaxRegistrationKindPartyRole
	1,  // 1: domain.tax.v1.TaxRegistrationKind.compute_path:type_name -> domain.tax.v1.TaxRegistrationKindComputePath
	2,  // 2: domain.tax.v1.TaxRegistrationKind.applicable_party_types:type_name -> domain.tax.v1.TaxRegistrationKindPartyType
	3,  // 3: domain.tax.v1.ReadTaxRegistrationKindRequest.data:type_name -> domain.tax.v1.TaxRegistrationKind
	3,  // 4: domain.tax.v1.ReadTaxRegistrationKindResponse.data:type_name -> domain.tax.v1.TaxRegistrationKind
	12, // 5: domain.tax.v1.ReadTaxRegistrationKindResponse.error:type_name -> domain.common.v1.Error
	13, // 6: domain.tax.v1.ListTaxRegistrationKindsRequest.search:type_name -> domain.common.v1.SearchRequest
	14, // 7: domain.tax.v1.ListTaxRegistrationKindsRequest.filters:type_name -> domain.common.v1.FilterRequest
	15, // 8: domain.tax.v1.ListTaxRegistrationKindsRequest.sort:type_name -> domain.common.v1.SortRequest
	16, // 9: domain.tax.v1.ListTaxRegistrationKindsRequest.pagination:type_name -> domain.common.v1.PaginationRequest
	3,  // 10: domain.tax.v1.ListTaxRegistrationKindsResponse.data:type_name -> domain.tax.v1.TaxRegistrationKind
	12, // 11: domain.tax.v1.ListTaxRegistrationKindsResponse.error:type_name -> domain.common.v1.Error
	16, // 12: domain.tax.v1.GetTaxRegistrationKindListPageDataRequest.pagination:type_name -> domain.common.v1.PaginationRequest
	14, // 13: domain.tax.v1.GetTaxRegistrationKindListPageDataRequest.filters:type_name -> domain.common.v1.FilterRequest
	15, // 14: domain.tax.v1.GetTaxRegistrationKindListPageDataRequest.sort:type_name -> domain.common.v1.SortRequest
	13, // 15: domain.tax.v1.GetTaxRegistrationKindListPageDataRequest.search:type_name -> domain.common.v1.SearchRequest
	3,  // 16: domain.tax.v1.GetTaxRegistrationKindListPageDataResponse.tax_registration_kind_list:type_name -> domain.tax.v1.TaxRegistrationKind
	17, // 17: domain.tax.v1.GetTaxRegistrationKindListPageDataResponse.pagination:type_name -> domain.common.v1.PaginationResponse
	18, // 18: domain.tax.v1.GetTaxRegistrationKindListPageDataResponse.search_results:type_name -> domain.common.v1.SearchResult
	12, // 19: domain.tax.v1.GetTaxRegistrationKindListPageDataResponse.error:type_name -> domain.common.v1.Error
	3,  // 20: domain.tax.v1.GetTaxRegistrationKindItemPageDataResponse.tax_registration_kind:type_name -> domain.tax.v1.TaxRegistrationKind
	12, // 21: domain.tax.v1.GetTaxRegistrationKindItemPageDataResponse.error:type_name -> domain.common.v1.Error
	4,  // 22: domain.tax.v1.TaxRegistrationKindDomainService.ReadTaxRegistrationKind:input_type -> domain.tax.v1.ReadTaxRegistrationKindRequest
	6,  // 23: domain.tax.v1.TaxRegistrationKindDomainService.ListTaxRegistrationKinds:input_type -> domain.tax.v1.ListTaxRegistrationKindsRequest
	8,  // 24: domain.tax.v1.TaxRegistrationKindDomainService.GetTaxRegistrationKindListPageData:input_type -> domain.tax.v1.GetTaxRegistrationKindListPageDataRequest
	10, // 25: domain.tax.v1.TaxRegistrationKindDomainService.GetTaxRegistrationKindItemPageData:input_type -> domain.tax.v1.GetTaxRegistrationKindItemPageDataRequest
	5,  // 26: domain.tax.v1.TaxRegistrationKindDomainService.ReadTaxRegistrationKind:output_type -> domain.tax.v1.ReadTaxRegistrationKindResponse
	7,  // 27: domain.tax.v1.TaxRegistrationKindDomainService.ListTaxRegistrationKinds:output_type -> domain.tax.v1.ListTaxRegistrationKindsResponse
	9,  // 28: domain.tax.v1.TaxRegistrationKindDomainService.GetTaxRegistrationKindListPageData:output_type -> domain.tax.v1.GetTaxRegistrationKindListPageDataResponse
	11, // 29: domain.tax.v1.TaxRegistrationKindDomainService.GetTaxRegistrationKindItemPageData:output_type -> domain.tax.v1.GetTaxRegistrationKindItemPageDataResponse
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_domain_tax_tax_registration_kind_tax_registration_kind_proto_init() }
func file_domain_tax_tax_registration_kind_tax_registration_kind_proto_init() {
	if File_domain_tax_tax_registration_kind_tax_registration_kind_proto != nil {
		return
	}
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[0].OneofWrappers = []any{}
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[2].OneofWrappers = []any{}
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[3].OneofWrappers = []any{}
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[4].OneofWrappers = []any{}
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[5].OneofWrappers = []any{}
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[6].OneofWrappers = []any{}
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDesc), len(file_domain_tax_tax_registration_kind_tax_registration_kind_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_tax_tax_registration_kind_tax_registration_kind_proto_goTypes,
		DependencyIndexes: file_domain_tax_tax_registration_kind_tax_registration_kind_proto_depIdxs,
		EnumInfos:         file_domain_tax_tax_registration_kind_tax_registration_kind_proto_enumTypes,
		MessageInfos:      file_domain_tax_tax_registration_kind_tax_registration_kind_proto_msgTypes,
	}.Build()
	File_domain_tax_tax_registration_kind_tax_registration_kind_proto = out.File
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_goTypes = nil
	file_domain_tax_tax_registration_kind_tax_registration_kind_proto_depIdxs = nil
}
