// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: domain/tax/tax_rate/tax_rate.proto

package taxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaxRateDomainService_ReadTaxRate_FullMethodName            = "/domain.tax.v1.TaxRateDomainService/ReadTaxRate"
	TaxRateDomainService_ListTaxRates_FullMethodName           = "/domain.tax.v1.TaxRateDomainService/ListTaxRates"
	TaxRateDomainService_GetTaxRateListPageData_FullMethodName = "/domain.tax.v1.TaxRateDomainService/GetTaxRateListPageData"
	TaxRateDomainService_GetTaxRateItemPageData_FullMethodName = "/domain.tax.v1.TaxRateDomainService/GetTaxRateItemPageData"
)

// TaxRateDomainServiceClient is the client API for TaxRateDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaxRateDomainServiceClient interface {
	ReadTaxRate(ctx context.Context, in *ReadTaxRateRequest, opts ...grpc.CallOption) (*ReadTaxRateResponse, error)
	ListTaxRates(ctx context.Context, in *ListTaxRatesRequest, opts ...grpc.CallOption) (*ListTaxRatesResponse, error)
	GetTaxRateListPageData(ctx context.Context, in *GetTaxRateListPageDataRequest, opts ...grpc.CallOption) (*GetTaxRateListPageDataResponse, error)
	GetTaxRateItemPageData(ctx context.Context, in *GetTaxRateItemPageDataRequest, opts ...grpc.CallOption) (*GetTaxRateItemPageDataResponse, error)
}

type taxRateDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaxRateDomainServiceClient(cc grpc.ClientConnInterface) TaxRateDomainServiceClient {
	return &taxRateDomainServiceClient{cc}
}

func (c *taxRateDomainServiceClient) ReadTaxRate(ctx context.Context, in *ReadTaxRateRequest, opts ...grpc.CallOption) (*ReadTaxRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadTaxRateResponse)
	err := c.cc.Invoke(ctx, TaxRateDomainService_ReadTaxRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxRateDomainServiceClient) ListTaxRates(ctx context.Context, in *ListTaxRatesRequest, opts ...grpc.CallOption) (*ListTaxRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaxRatesResponse)
	err := c.cc.Invoke(ctx, TaxRateDomainService_ListTaxRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxRateDomainServiceClient) GetTaxRateListPageData(ctx context.Context, in *GetTaxRateListPageDataRequest, opts ...grpc.CallOption) (*GetTaxRateListPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaxRateListPageDataResponse)
	err := c.cc.Invoke(ctx, TaxRateDomainService_GetTaxRateListPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxRateDomainServiceClient) GetTaxRateItemPageData(ctx context.Context, in *GetTaxRateItemPageDataRequest, opts ...grpc.CallOption) (*GetTaxRateItemPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaxRateItemPageDataResponse)
	err := c.cc.Invoke(ctx, TaxRateDomainService_GetTaxRateItemPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaxRateDomainServiceServer is the server API for TaxRateDomainService service.
// All implementations must embed UnimplementedTaxRateDomainServiceServer
// for forward compatibility.
type TaxRateDomainServiceServer interface {
	ReadTaxRate(context.Context, *ReadTaxRateRequest) (*ReadTaxRateResponse, error)
	ListTaxRates(context.Context, *ListTaxRatesRequest) (*ListTaxRatesResponse, error)
	GetTaxRateListPageData(context.Context, *GetTaxRateListPageDataRequest) (*GetTaxRateListPageDataResponse, error)
	GetTaxRateItemPageData(context.Context, *GetTaxRateItemPageDataRequest) (*GetTaxRateItemPageDataResponse, error)
	mustEmbedUnimplementedTaxRateDomainServiceServer()
}

// UnimplementedTaxRateDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaxRateDomainServiceServer struct{}

func (UnimplementedTaxRateDomainServiceServer) ReadTaxRate(context.Context, *ReadTaxRateRequest) (*ReadTaxRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadTaxRate not implemented")
}
func (UnimplementedTaxRateDomainServiceServer) ListTaxRates(context.Context, *ListTaxRatesRequest) (*ListTaxRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaxRates not implemented")
}
func (UnimplementedTaxRateDomainServiceServer) GetTaxRateListPageData(context.Context, *GetTaxRateListPageDataRequest) (*GetTaxRateListPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaxRateListPageData not implemented")
}
func (UnimplementedTaxRateDomainServiceServer) GetTaxRateItemPageData(context.Context, *GetTaxRateItemPageDataRequest) (*GetTaxRateItemPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaxRateItemPageData not implemented")
}
func (UnimplementedTaxRateDomainServiceServer) mustEmbedUnimplementedTaxRateDomainServiceServer() {}
func (UnimplementedTaxRateDomainServiceServer) testEmbeddedByValue()                              {}

// UnsafeTaxRateDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaxRateDomainServiceServer will
// result in compilation errors.
type UnsafeTaxRateDomainServiceServer interface {
	mustEmbedUnimplementedTaxRateDomainServiceServer()
}

func RegisterTaxRateDomainServiceServer(s grpc.ServiceRegistrar, srv TaxRateDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedTaxRateDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaxRateDomainService_ServiceDesc, srv)
}

func _TaxRateDomainService_ReadTaxRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTaxRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxRateDomainServiceServer).ReadTaxRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxRateDomainService_ReadTaxRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxRateDomainServiceServer).ReadTaxRate(ctx, req.(*ReadTaxRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxRateDomainService_ListTaxRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaxRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxRateDomainServiceServer).ListTaxRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxRateDomainService_ListTaxRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxRateDomainServiceServer).ListTaxRates(ctx, req.(*ListTaxRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxRateDomainService_GetTaxRateListPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxRateListPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxRateDomainServiceServer).GetTaxRateListPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxRateDomainService_GetTaxRateListPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxRateDomainServiceServer).GetTaxRateListPageData(ctx, req.(*GetTaxRateListPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxRateDomainService_GetTaxRateItemPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxRateItemPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxRateDomainServiceServer).GetTaxRateItemPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxRateDomainService_GetTaxRateItemPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxRateDomainServiceServer).GetTaxRateItemPageData(ctx, req.(*GetTaxRateItemPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaxRateDomainService_ServiceDesc is the grpc.ServiceDesc for TaxRateDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaxRateDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.tax.v1.TaxRateDomainService",
	HandlerType: (*TaxRateDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadTaxRate",
			Handler:    _TaxRateDomainService_ReadTaxRate_Handler,
		},
		{
			MethodName: "ListTaxRates",
			Handler:    _TaxRateDomainService_ListTaxRates_Handler,
		},
		{
			MethodName: "GetTaxRateListPageData",
			Handler:    _TaxRateDomainService_GetTaxRateListPageData_Handler,
		},
		{
			MethodName: "GetTaxRateItemPageData",
			Handler:    _TaxRateDomainService_GetTaxRateItemPageData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/tax/tax_rate/tax_rate.proto",
}
