// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: domain/treasury/collection_application/collection_application.proto

package treasuryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectionApplicationDomainService_CreateCollectionApplication_FullMethodName          = "/domain.treasury.v1.CollectionApplicationDomainService/CreateCollectionApplication"
	CollectionApplicationDomainService_ReadCollectionApplication_FullMethodName            = "/domain.treasury.v1.CollectionApplicationDomainService/ReadCollectionApplication"
	CollectionApplicationDomainService_UpdateCollectionApplication_FullMethodName          = "/domain.treasury.v1.CollectionApplicationDomainService/UpdateCollectionApplication"
	CollectionApplicationDomainService_DeleteCollectionApplication_FullMethodName          = "/domain.treasury.v1.CollectionApplicationDomainService/DeleteCollectionApplication"
	CollectionApplicationDomainService_ListCollectionApplications_FullMethodName           = "/domain.treasury.v1.CollectionApplicationDomainService/ListCollectionApplications"
	CollectionApplicationDomainService_GetCollectionApplicationListPageData_FullMethodName = "/domain.treasury.v1.CollectionApplicationDomainService/GetCollectionApplicationListPageData"
	CollectionApplicationDomainService_GetCollectionApplicationItemPageData_FullMethodName = "/domain.treasury.v1.CollectionApplicationDomainService/GetCollectionApplicationItemPageData"
	CollectionApplicationDomainService_ReceiveAndApplyCollection_FullMethodName            = "/domain.treasury.v1.CollectionApplicationDomainService/ReceiveAndApplyCollection"
	CollectionApplicationDomainService_PreviewCollectionApplication_FullMethodName         = "/domain.treasury.v1.CollectionApplicationDomainService/PreviewCollectionApplication"
	CollectionApplicationDomainService_ReverseCollectionApplication_FullMethodName         = "/domain.treasury.v1.CollectionApplicationDomainService/ReverseCollectionApplication"
)

// CollectionApplicationDomainServiceClient is the client API for CollectionApplicationDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionApplicationDomainServiceClient interface {
	CreateCollectionApplication(ctx context.Context, in *CreateCollectionApplicationRequest, opts ...grpc.CallOption) (*CreateCollectionApplicationResponse, error)
	ReadCollectionApplication(ctx context.Context, in *ReadCollectionApplicationRequest, opts ...grpc.CallOption) (*ReadCollectionApplicationResponse, error)
	UpdateCollectionApplication(ctx context.Context, in *UpdateCollectionApplicationRequest, opts ...grpc.CallOption) (*UpdateCollectionApplicationResponse, error)
	DeleteCollectionApplication(ctx context.Context, in *DeleteCollectionApplicationRequest, opts ...grpc.CallOption) (*DeleteCollectionApplicationResponse, error)
	ListCollectionApplications(ctx context.Context, in *ListCollectionApplicationsRequest, opts ...grpc.CallOption) (*ListCollectionApplicationsResponse, error)
	GetCollectionApplicationListPageData(ctx context.Context, in *GetCollectionApplicationListPageDataRequest, opts ...grpc.CallOption) (*GetCollectionApplicationListPageDataResponse, error)
	GetCollectionApplicationItemPageData(ctx context.Context, in *GetCollectionApplicationItemPageDataRequest, opts ...grpc.CallOption) (*GetCollectionApplicationItemPageDataResponse, error)
	ReceiveAndApplyCollection(ctx context.Context, in *ReceiveAndApplyCollectionRequest, opts ...grpc.CallOption) (*ReceiveAndApplyCollectionResponse, error)
	PreviewCollectionApplication(ctx context.Context, in *PreviewCollectionApplicationRequest, opts ...grpc.CallOption) (*PreviewCollectionApplicationResponse, error)
	ReverseCollectionApplication(ctx context.Context, in *ReverseCollectionApplicationRequest, opts ...grpc.CallOption) (*ReverseCollectionApplicationResponse, error)
}

type collectionApplicationDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionApplicationDomainServiceClient(cc grpc.ClientConnInterface) CollectionApplicationDomainServiceClient {
	return &collectionApplicationDomainServiceClient{cc}
}

func (c *collectionApplicationDomainServiceClient) CreateCollectionApplication(ctx context.Context, in *CreateCollectionApplicationRequest, opts ...grpc.CallOption) (*CreateCollectionApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionApplicationResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_CreateCollectionApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) ReadCollectionApplication(ctx context.Context, in *ReadCollectionApplicationRequest, opts ...grpc.CallOption) (*ReadCollectionApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCollectionApplicationResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_ReadCollectionApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) UpdateCollectionApplication(ctx context.Context, in *UpdateCollectionApplicationRequest, opts ...grpc.CallOption) (*UpdateCollectionApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCollectionApplicationResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_UpdateCollectionApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) DeleteCollectionApplication(ctx context.Context, in *DeleteCollectionApplicationRequest, opts ...grpc.CallOption) (*DeleteCollectionApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCollectionApplicationResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_DeleteCollectionApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) ListCollectionApplications(ctx context.Context, in *ListCollectionApplicationsRequest, opts ...grpc.CallOption) (*ListCollectionApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionApplicationsResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_ListCollectionApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) GetCollectionApplicationListPageData(ctx context.Context, in *GetCollectionApplicationListPageDataRequest, opts ...grpc.CallOption) (*GetCollectionApplicationListPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionApplicationListPageDataResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_GetCollectionApplicationListPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) GetCollectionApplicationItemPageData(ctx context.Context, in *GetCollectionApplicationItemPageDataRequest, opts ...grpc.CallOption) (*GetCollectionApplicationItemPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionApplicationItemPageDataResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_GetCollectionApplicationItemPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) ReceiveAndApplyCollection(ctx context.Context, in *ReceiveAndApplyCollectionRequest, opts ...grpc.CallOption) (*ReceiveAndApplyCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveAndApplyCollectionResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_ReceiveAndApplyCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) PreviewCollectionApplication(ctx context.Context, in *PreviewCollectionApplicationRequest, opts ...grpc.CallOption) (*PreviewCollectionApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewCollectionApplicationResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_PreviewCollectionApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionApplicationDomainServiceClient) ReverseCollectionApplication(ctx context.Context, in *ReverseCollectionApplicationRequest, opts ...grpc.CallOption) (*ReverseCollectionApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReverseCollectionApplicationResponse)
	err := c.cc.Invoke(ctx, CollectionApplicationDomainService_ReverseCollectionApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionApplicationDomainServiceServer is the server API for CollectionApplicationDomainService service.
// All implementations must embed UnimplementedCollectionApplicationDomainServiceServer
// for forward compatibility.
type CollectionApplicationDomainServiceServer interface {
	CreateCollectionApplication(context.Context, *CreateCollectionApplicationRequest) (*CreateCollectionApplicationResponse, error)
	ReadCollectionApplication(context.Context, *ReadCollectionApplicationRequest) (*ReadCollectionApplicationResponse, error)
	UpdateCollectionApplication(context.Context, *UpdateCollectionApplicationRequest) (*UpdateCollectionApplicationResponse, error)
	DeleteCollectionApplication(context.Context, *DeleteCollectionApplicationRequest) (*DeleteCollectionApplicationResponse, error)
	ListCollectionApplications(context.Context, *ListCollectionApplicationsRequest) (*ListCollectionApplicationsResponse, error)
	GetCollectionApplicationListPageData(context.Context, *GetCollectionApplicationListPageDataRequest) (*GetCollectionApplicationListPageDataResponse, error)
	GetCollectionApplicationItemPageData(context.Context, *GetCollectionApplicationItemPageDataRequest) (*GetCollectionApplicationItemPageDataResponse, error)
	ReceiveAndApplyCollection(context.Context, *ReceiveAndApplyCollectionRequest) (*ReceiveAndApplyCollectionResponse, error)
	PreviewCollectionApplication(context.Context, *PreviewCollectionApplicationRequest) (*PreviewCollectionApplicationResponse, error)
	ReverseCollectionApplication(context.Context, *ReverseCollectionApplicationRequest) (*ReverseCollectionApplicationResponse, error)
	mustEmbedUnimplementedCollectionApplicationDomainServiceServer()
}

// UnimplementedCollectionApplicationDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectionApplicationDomainServiceServer struct{}

func (UnimplementedCollectionApplicationDomainServiceServer) CreateCollectionApplication(context.Context, *CreateCollectionApplicationRequest) (*CreateCollectionApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollectionApplication not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) ReadCollectionApplication(context.Context, *ReadCollectionApplicationRequest) (*ReadCollectionApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadCollectionApplication not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) UpdateCollectionApplication(context.Context, *UpdateCollectionApplicationRequest) (*UpdateCollectionApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCollectionApplication not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) DeleteCollectionApplication(context.Context, *DeleteCollectionApplicationRequest) (*DeleteCollectionApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCollectionApplication not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) ListCollectionApplications(context.Context, *ListCollectionApplicationsRequest) (*ListCollectionApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollectionApplications not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) GetCollectionApplicationListPageData(context.Context, *GetCollectionApplicationListPageDataRequest) (*GetCollectionApplicationListPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionApplicationListPageData not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) GetCollectionApplicationItemPageData(context.Context, *GetCollectionApplicationItemPageDataRequest) (*GetCollectionApplicationItemPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionApplicationItemPageData not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) ReceiveAndApplyCollection(context.Context, *ReceiveAndApplyCollectionRequest) (*ReceiveAndApplyCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveAndApplyCollection not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) PreviewCollectionApplication(context.Context, *PreviewCollectionApplicationRequest) (*PreviewCollectionApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewCollectionApplication not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) ReverseCollectionApplication(context.Context, *ReverseCollectionApplicationRequest) (*ReverseCollectionApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReverseCollectionApplication not implemented")
}
func (UnimplementedCollectionApplicationDomainServiceServer) mustEmbedUnimplementedCollectionApplicationDomainServiceServer() {
}
func (UnimplementedCollectionApplicationDomainServiceServer) testEmbeddedByValue() {}

// UnsafeCollectionApplicationDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionApplicationDomainServiceServer will
// result in compilation errors.
type UnsafeCollectionApplicationDomainServiceServer interface {
	mustEmbedUnimplementedCollectionApplicationDomainServiceServer()
}

func RegisterCollectionApplicationDomainServiceServer(s grpc.ServiceRegistrar, srv CollectionApplicationDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectionApplicationDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectionApplicationDomainService_ServiceDesc, srv)
}

func _CollectionApplicationDomainService_CreateCollectionApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).CreateCollectionApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_CreateCollectionApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).CreateCollectionApplication(ctx, req.(*CreateCollectionApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_ReadCollectionApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCollectionApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).ReadCollectionApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_ReadCollectionApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).ReadCollectionApplication(ctx, req.(*ReadCollectionApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_UpdateCollectionApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollectionApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).UpdateCollectionApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_UpdateCollectionApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).UpdateCollectionApplication(ctx, req.(*UpdateCollectionApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_DeleteCollectionApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).DeleteCollectionApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_DeleteCollectionApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).DeleteCollectionApplication(ctx, req.(*DeleteCollectionApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_ListCollectionApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).ListCollectionApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_ListCollectionApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).ListCollectionApplications(ctx, req.(*ListCollectionApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_GetCollectionApplicationListPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionApplicationListPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).GetCollectionApplicationListPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_GetCollectionApplicationListPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).GetCollectionApplicationListPageData(ctx, req.(*GetCollectionApplicationListPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_GetCollectionApplicationItemPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionApplicationItemPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).GetCollectionApplicationItemPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_GetCollectionApplicationItemPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).GetCollectionApplicationItemPageData(ctx, req.(*GetCollectionApplicationItemPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_ReceiveAndApplyCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveAndApplyCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).ReceiveAndApplyCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_ReceiveAndApplyCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).ReceiveAndApplyCollection(ctx, req.(*ReceiveAndApplyCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_PreviewCollectionApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewCollectionApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).PreviewCollectionApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_PreviewCollectionApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).PreviewCollectionApplication(ctx, req.(*PreviewCollectionApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionApplicationDomainService_ReverseCollectionApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseCollectionApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionApplicationDomainServiceServer).ReverseCollectionApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectionApplicationDomainService_ReverseCollectionApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionApplicationDomainServiceServer).ReverseCollectionApplication(ctx, req.(*ReverseCollectionApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectionApplicationDomainService_ServiceDesc is the grpc.ServiceDesc for CollectionApplicationDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectionApplicationDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.treasury.v1.CollectionApplicationDomainService",
	HandlerType: (*CollectionApplicationDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollectionApplication",
			Handler:    _CollectionApplicationDomainService_CreateCollectionApplication_Handler,
		},
		{
			MethodName: "ReadCollectionApplication",
			Handler:    _CollectionApplicationDomainService_ReadCollectionApplication_Handler,
		},
		{
			MethodName: "UpdateCollectionApplication",
			Handler:    _CollectionApplicationDomainService_UpdateCollectionApplication_Handler,
		},
		{
			MethodName: "DeleteCollectionApplication",
			Handler:    _CollectionApplicationDomainService_DeleteCollectionApplication_Handler,
		},
		{
			MethodName: "ListCollectionApplications",
			Handler:    _CollectionApplicationDomainService_ListCollectionApplications_Handler,
		},
		{
			MethodName: "GetCollectionApplicationListPageData",
			Handler:    _CollectionApplicationDomainService_GetCollectionApplicationListPageData_Handler,
		},
		{
			MethodName: "GetCollectionApplicationItemPageData",
			Handler:    _CollectionApplicationDomainService_GetCollectionApplicationItemPageData_Handler,
		},
		{
			MethodName: "ReceiveAndApplyCollection",
			Handler:    _CollectionApplicationDomainService_ReceiveAndApplyCollection_Handler,
		},
		{
			MethodName: "PreviewCollectionApplication",
			Handler:    _CollectionApplicationDomainService_PreviewCollectionApplication_Handler,
		},
		{
			MethodName: "ReverseCollectionApplication",
			Handler:    _CollectionApplicationDomainService_ReverseCollectionApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/treasury/collection_application/collection_application.proto",
}
