syntax = "proto3";

package domain.product.v1;


option go_package = "github.com/erniealice/esqyma/golang/v1/domain/product/line_plan";

import "domain/common/error.proto";
import "domain/common/pagination.proto";
import "domain/common/filter.proto";
import "domain/common/sort.proto";
import "domain/common/search.proto";
import "options/db.proto";

message LinePlan {
  option (options.v1.table).table = true;
  option (options.v1.table).unique_together = "line_id,plan_id";
  string id = 1;
  string line_id = 2 [(options.v1.db).references = "line", (options.v1.db).index = true];
  string plan_id = 3 [(options.v1.db).references = "plan", (options.v1.db).index = true];
  optional int64 date_created = 4;
  optional string date_created_string = 5 [(options.v1.db).ignore = true];
  optional int64 date_modified = 6;
  optional string date_modified_string = 7 [(options.v1.db).ignore = true];
  bool active = 8 [(options.v1.db).default = "true"];
  string workspace_id = 9 [(options.v1.db).references = "workspace", (options.v1.db).index = true];
}

service LinePlanDomainService {
  rpc CreateLinePlan(CreateLinePlanRequest) returns (CreateLinePlanResponse);
  rpc ReadLinePlan(ReadLinePlanRequest) returns (ReadLinePlanResponse);
  rpc UpdateLinePlan(UpdateLinePlanRequest) returns (UpdateLinePlanResponse);
  rpc DeleteLinePlan(DeleteLinePlanRequest) returns (DeleteLinePlanResponse);
  rpc ListLinePlans(ListLinePlansRequest) returns (ListLinePlansResponse);
  rpc GetLinePlanListPageData(GetLinePlanListPageDataRequest)
    returns (GetLinePlanListPageDataResponse);
  rpc GetLinePlanItemPageData(GetLinePlanItemPageDataRequest)
    returns (GetLinePlanItemPageDataResponse);
}

message CreateLinePlanRequest {
  LinePlan data = 1;
}

message CreateLinePlanResponse {
  repeated LinePlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message ReadLinePlanRequest {
  LinePlan data = 1;
}

message ReadLinePlanResponse {
  repeated LinePlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message UpdateLinePlanRequest {
  LinePlan data = 1;
}

message UpdateLinePlanResponse {
  repeated LinePlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message DeleteLinePlanRequest {
  LinePlan data = 1;
}

message DeleteLinePlanResponse {
  bool success = 1;
  optional domain.common.v1.Error error = 2;
}

message ListLinePlansRequest {
  optional domain.common.v1.SearchRequest search = 1;
  optional domain.common.v1.FilterRequest filters = 2;
  optional domain.common.v1.SortRequest sort = 3;
  optional domain.common.v1.PaginationRequest pagination = 4;
}

message ListLinePlansResponse {
  repeated LinePlan data = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}

message GetLinePlanListPageDataRequest {
  optional domain.common.v1.SearchRequest search = 1;
  optional domain.common.v1.FilterRequest filters = 2;
  optional domain.common.v1.SortRequest sort = 3;
  optional domain.common.v1.PaginationRequest pagination = 4;
}

message GetLinePlanListPageDataResponse {
  repeated LinePlan line_plan_list = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
  optional domain.common.v1.PaginationResponse pagination = 4;
  repeated domain.common.v1.SearchResult search_results = 5;
}

message GetLinePlanItemPageDataRequest {
  string line_plan_id = 1;
}

message GetLinePlanItemPageDataResponse {
  LinePlan line_plan = 1;
  bool success = 2;
  optional domain.common.v1.Error error = 3;
}
