// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: domain/funding/fund_transaction/fund_transaction.proto

package fundingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FundTransactionDomainService_CreateFundTransaction_FullMethodName          = "/domain.funding.v1.FundTransactionDomainService/CreateFundTransaction"
	FundTransactionDomainService_ReadFundTransaction_FullMethodName            = "/domain.funding.v1.FundTransactionDomainService/ReadFundTransaction"
	FundTransactionDomainService_UpdateFundTransaction_FullMethodName          = "/domain.funding.v1.FundTransactionDomainService/UpdateFundTransaction"
	FundTransactionDomainService_DeleteFundTransaction_FullMethodName          = "/domain.funding.v1.FundTransactionDomainService/DeleteFundTransaction"
	FundTransactionDomainService_ListFundTransactions_FullMethodName           = "/domain.funding.v1.FundTransactionDomainService/ListFundTransactions"
	FundTransactionDomainService_GetFundTransactionListPageData_FullMethodName = "/domain.funding.v1.FundTransactionDomainService/GetFundTransactionListPageData"
	FundTransactionDomainService_GetFundTransactionItemPageData_FullMethodName = "/domain.funding.v1.FundTransactionDomainService/GetFundTransactionItemPageData"
)

// FundTransactionDomainServiceClient is the client API for FundTransactionDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FundTransactionDomainServiceClient interface {
	CreateFundTransaction(ctx context.Context, in *CreateFundTransactionRequest, opts ...grpc.CallOption) (*CreateFundTransactionResponse, error)
	ReadFundTransaction(ctx context.Context, in *ReadFundTransactionRequest, opts ...grpc.CallOption) (*ReadFundTransactionResponse, error)
	UpdateFundTransaction(ctx context.Context, in *UpdateFundTransactionRequest, opts ...grpc.CallOption) (*UpdateFundTransactionResponse, error)
	DeleteFundTransaction(ctx context.Context, in *DeleteFundTransactionRequest, opts ...grpc.CallOption) (*DeleteFundTransactionResponse, error)
	ListFundTransactions(ctx context.Context, in *ListFundTransactionsRequest, opts ...grpc.CallOption) (*ListFundTransactionsResponse, error)
	GetFundTransactionListPageData(ctx context.Context, in *GetFundTransactionListPageDataRequest, opts ...grpc.CallOption) (*GetFundTransactionListPageDataResponse, error)
	GetFundTransactionItemPageData(ctx context.Context, in *GetFundTransactionItemPageDataRequest, opts ...grpc.CallOption) (*GetFundTransactionItemPageDataResponse, error)
}

type fundTransactionDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFundTransactionDomainServiceClient(cc grpc.ClientConnInterface) FundTransactionDomainServiceClient {
	return &fundTransactionDomainServiceClient{cc}
}

func (c *fundTransactionDomainServiceClient) CreateFundTransaction(ctx context.Context, in *CreateFundTransactionRequest, opts ...grpc.CallOption) (*CreateFundTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFundTransactionResponse)
	err := c.cc.Invoke(ctx, FundTransactionDomainService_CreateFundTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundTransactionDomainServiceClient) ReadFundTransaction(ctx context.Context, in *ReadFundTransactionRequest, opts ...grpc.CallOption) (*ReadFundTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFundTransactionResponse)
	err := c.cc.Invoke(ctx, FundTransactionDomainService_ReadFundTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundTransactionDomainServiceClient) UpdateFundTransaction(ctx context.Context, in *UpdateFundTransactionRequest, opts ...grpc.CallOption) (*UpdateFundTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFundTransactionResponse)
	err := c.cc.Invoke(ctx, FundTransactionDomainService_UpdateFundTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundTransactionDomainServiceClient) DeleteFundTransaction(ctx context.Context, in *DeleteFundTransactionRequest, opts ...grpc.CallOption) (*DeleteFundTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFundTransactionResponse)
	err := c.cc.Invoke(ctx, FundTransactionDomainService_DeleteFundTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundTransactionDomainServiceClient) ListFundTransactions(ctx context.Context, in *ListFundTransactionsRequest, opts ...grpc.CallOption) (*ListFundTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFundTransactionsResponse)
	err := c.cc.Invoke(ctx, FundTransactionDomainService_ListFundTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundTransactionDomainServiceClient) GetFundTransactionListPageData(ctx context.Context, in *GetFundTransactionListPageDataRequest, opts ...grpc.CallOption) (*GetFundTransactionListPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFundTransactionListPageDataResponse)
	err := c.cc.Invoke(ctx, FundTransactionDomainService_GetFundTransactionListPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundTransactionDomainServiceClient) GetFundTransactionItemPageData(ctx context.Context, in *GetFundTransactionItemPageDataRequest, opts ...grpc.CallOption) (*GetFundTransactionItemPageDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFundTransactionItemPageDataResponse)
	err := c.cc.Invoke(ctx, FundTransactionDomainService_GetFundTransactionItemPageData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundTransactionDomainServiceServer is the server API for FundTransactionDomainService service.
// All implementations must embed UnimplementedFundTransactionDomainServiceServer
// for forward compatibility.
type FundTransactionDomainServiceServer interface {
	CreateFundTransaction(context.Context, *CreateFundTransactionRequest) (*CreateFundTransactionResponse, error)
	ReadFundTransaction(context.Context, *ReadFundTransactionRequest) (*ReadFundTransactionResponse, error)
	UpdateFundTransaction(context.Context, *UpdateFundTransactionRequest) (*UpdateFundTransactionResponse, error)
	DeleteFundTransaction(context.Context, *DeleteFundTransactionRequest) (*DeleteFundTransactionResponse, error)
	ListFundTransactions(context.Context, *ListFundTransactionsRequest) (*ListFundTransactionsResponse, error)
	GetFundTransactionListPageData(context.Context, *GetFundTransactionListPageDataRequest) (*GetFundTransactionListPageDataResponse, error)
	GetFundTransactionItemPageData(context.Context, *GetFundTransactionItemPageDataRequest) (*GetFundTransactionItemPageDataResponse, error)
	mustEmbedUnimplementedFundTransactionDomainServiceServer()
}

// UnimplementedFundTransactionDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFundTransactionDomainServiceServer struct{}

func (UnimplementedFundTransactionDomainServiceServer) CreateFundTransaction(context.Context, *CreateFundTransactionRequest) (*CreateFundTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFundTransaction not implemented")
}
func (UnimplementedFundTransactionDomainServiceServer) ReadFundTransaction(context.Context, *ReadFundTransactionRequest) (*ReadFundTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFundTransaction not implemented")
}
func (UnimplementedFundTransactionDomainServiceServer) UpdateFundTransaction(context.Context, *UpdateFundTransactionRequest) (*UpdateFundTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFundTransaction not implemented")
}
func (UnimplementedFundTransactionDomainServiceServer) DeleteFundTransaction(context.Context, *DeleteFundTransactionRequest) (*DeleteFundTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFundTransaction not implemented")
}
func (UnimplementedFundTransactionDomainServiceServer) ListFundTransactions(context.Context, *ListFundTransactionsRequest) (*ListFundTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFundTransactions not implemented")
}
func (UnimplementedFundTransactionDomainServiceServer) GetFundTransactionListPageData(context.Context, *GetFundTransactionListPageDataRequest) (*GetFundTransactionListPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundTransactionListPageData not implemented")
}
func (UnimplementedFundTransactionDomainServiceServer) GetFundTransactionItemPageData(context.Context, *GetFundTransactionItemPageDataRequest) (*GetFundTransactionItemPageDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundTransactionItemPageData not implemented")
}
func (UnimplementedFundTransactionDomainServiceServer) mustEmbedUnimplementedFundTransactionDomainServiceServer() {
}
func (UnimplementedFundTransactionDomainServiceServer) testEmbeddedByValue() {}

// UnsafeFundTransactionDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundTransactionDomainServiceServer will
// result in compilation errors.
type UnsafeFundTransactionDomainServiceServer interface {
	mustEmbedUnimplementedFundTransactionDomainServiceServer()
}

func RegisterFundTransactionDomainServiceServer(s grpc.ServiceRegistrar, srv FundTransactionDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedFundTransactionDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FundTransactionDomainService_ServiceDesc, srv)
}

func _FundTransactionDomainService_CreateFundTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFundTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransactionDomainServiceServer).CreateFundTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransactionDomainService_CreateFundTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransactionDomainServiceServer).CreateFundTransaction(ctx, req.(*CreateFundTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundTransactionDomainService_ReadFundTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFundTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransactionDomainServiceServer).ReadFundTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransactionDomainService_ReadFundTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransactionDomainServiceServer).ReadFundTransaction(ctx, req.(*ReadFundTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundTransactionDomainService_UpdateFundTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFundTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransactionDomainServiceServer).UpdateFundTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransactionDomainService_UpdateFundTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransactionDomainServiceServer).UpdateFundTransaction(ctx, req.(*UpdateFundTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundTransactionDomainService_DeleteFundTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFundTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransactionDomainServiceServer).DeleteFundTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransactionDomainService_DeleteFundTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransactionDomainServiceServer).DeleteFundTransaction(ctx, req.(*DeleteFundTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundTransactionDomainService_ListFundTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFundTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransactionDomainServiceServer).ListFundTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransactionDomainService_ListFundTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransactionDomainServiceServer).ListFundTransactions(ctx, req.(*ListFundTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundTransactionDomainService_GetFundTransactionListPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundTransactionListPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransactionDomainServiceServer).GetFundTransactionListPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransactionDomainService_GetFundTransactionListPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransactionDomainServiceServer).GetFundTransactionListPageData(ctx, req.(*GetFundTransactionListPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundTransactionDomainService_GetFundTransactionItemPageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundTransactionItemPageDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundTransactionDomainServiceServer).GetFundTransactionItemPageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundTransactionDomainService_GetFundTransactionItemPageData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundTransactionDomainServiceServer).GetFundTransactionItemPageData(ctx, req.(*GetFundTransactionItemPageDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FundTransactionDomainService_ServiceDesc is the grpc.ServiceDesc for FundTransactionDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FundTransactionDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.funding.v1.FundTransactionDomainService",
	HandlerType: (*FundTransactionDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFundTransaction",
			Handler:    _FundTransactionDomainService_CreateFundTransaction_Handler,
		},
		{
			MethodName: "ReadFundTransaction",
			Handler:    _FundTransactionDomainService_ReadFundTransaction_Handler,
		},
		{
			MethodName: "UpdateFundTransaction",
			Handler:    _FundTransactionDomainService_UpdateFundTransaction_Handler,
		},
		{
			MethodName: "DeleteFundTransaction",
			Handler:    _FundTransactionDomainService_DeleteFundTransaction_Handler,
		},
		{
			MethodName: "ListFundTransactions",
			Handler:    _FundTransactionDomainService_ListFundTransactions_Handler,
		},
		{
			MethodName: "GetFundTransactionListPageData",
			Handler:    _FundTransactionDomainService_GetFundTransactionListPageData_Handler,
		},
		{
			MethodName: "GetFundTransactionItemPageData",
			Handler:    _FundTransactionDomainService_GetFundTransactionItemPageData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/funding/fund_transaction/fund_transaction.proto",
}
