// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: integration/datasheet/datasheet.proto

package datasheetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DatasheetProviderType represents the category of datasheet provider
type DatasheetProviderType int32

const (
	DatasheetProviderType_DATASHEET_PROVIDER_TYPE_UNSPECIFIED   DatasheetProviderType = 0
	DatasheetProviderType_DATASHEET_PROVIDER_TYPE_GOOGLE_SHEETS DatasheetProviderType = 1 // Google Sheets API
	DatasheetProviderType_DATASHEET_PROVIDER_TYPE_EXCEL_ONLINE  DatasheetProviderType = 2 // Microsoft Excel Online / Graph API
	DatasheetProviderType_DATASHEET_PROVIDER_TYPE_AIRTABLE      DatasheetProviderType = 3 // Airtable API
	DatasheetProviderType_DATASHEET_PROVIDER_TYPE_MOCK          DatasheetProviderType = 4 // Mock/test provider
)

// Enum value maps for DatasheetProviderType.
var (
	DatasheetProviderType_name = map[int32]string{
		0: "DATASHEET_PROVIDER_TYPE_UNSPECIFIED",
		1: "DATASHEET_PROVIDER_TYPE_GOOGLE_SHEETS",
		2: "DATASHEET_PROVIDER_TYPE_EXCEL_ONLINE",
		3: "DATASHEET_PROVIDER_TYPE_AIRTABLE",
		4: "DATASHEET_PROVIDER_TYPE_MOCK",
	}
	DatasheetProviderType_value = map[string]int32{
		"DATASHEET_PROVIDER_TYPE_UNSPECIFIED":   0,
		"DATASHEET_PROVIDER_TYPE_GOOGLE_SHEETS": 1,
		"DATASHEET_PROVIDER_TYPE_EXCEL_ONLINE":  2,
		"DATASHEET_PROVIDER_TYPE_AIRTABLE":      3,
		"DATASHEET_PROVIDER_TYPE_MOCK":          4,
	}
)

func (x DatasheetProviderType) Enum() *DatasheetProviderType {
	p := new(DatasheetProviderType)
	*p = x
	return p
}

func (x DatasheetProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatasheetProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[0].Descriptor()
}

func (DatasheetProviderType) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[0]
}

func (x DatasheetProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatasheetProviderType.Descriptor instead.
func (DatasheetProviderType) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{0}
}

// DatasheetCapability represents features supported by a provider
type DatasheetCapability int32

const (
	DatasheetCapability_DATASHEET_CAPABILITY_UNSPECIFIED            DatasheetCapability = 0
	DatasheetCapability_DATASHEET_CAPABILITY_READ                   DatasheetCapability = 1  // Read data from sheets
	DatasheetCapability_DATASHEET_CAPABILITY_WRITE                  DatasheetCapability = 2  // Write/append data to sheets
	DatasheetCapability_DATASHEET_CAPABILITY_BATCH_UPDATE           DatasheetCapability = 3  // Batch update operations
	DatasheetCapability_DATASHEET_CAPABILITY_FORMULAS               DatasheetCapability = 4  // Formula support
	DatasheetCapability_DATASHEET_CAPABILITY_FORMATTING             DatasheetCapability = 5  // Cell/row/column formatting
	DatasheetCapability_DATASHEET_CAPABILITY_CONDITIONAL_FORMATTING DatasheetCapability = 6  // Conditional formatting rules
	DatasheetCapability_DATASHEET_CAPABILITY_CHARTS                 DatasheetCapability = 7  // Chart creation and management
	DatasheetCapability_DATASHEET_CAPABILITY_PIVOT_TABLES           DatasheetCapability = 8  // Pivot table support
	DatasheetCapability_DATASHEET_CAPABILITY_FILTERING              DatasheetCapability = 9  // Data filtering
	DatasheetCapability_DATASHEET_CAPABILITY_SORTING                DatasheetCapability = 10 // Data sorting
	DatasheetCapability_DATASHEET_CAPABILITY_VALIDATION             DatasheetCapability = 11 // Data validation rules
	DatasheetCapability_DATASHEET_CAPABILITY_COMMENTS               DatasheetCapability = 12 // Cell comments/notes
	DatasheetCapability_DATASHEET_CAPABILITY_PROTECTION             DatasheetCapability = 13 // Sheet/range protection
	DatasheetCapability_DATASHEET_CAPABILITY_NAMED_RANGES           DatasheetCapability = 14 // Named range support
	DatasheetCapability_DATASHEET_CAPABILITY_MULTIPLE_SHEETS        DatasheetCapability = 15 // Multiple sheets in spreadsheet
)

// Enum value maps for DatasheetCapability.
var (
	DatasheetCapability_name = map[int32]string{
		0:  "DATASHEET_CAPABILITY_UNSPECIFIED",
		1:  "DATASHEET_CAPABILITY_READ",
		2:  "DATASHEET_CAPABILITY_WRITE",
		3:  "DATASHEET_CAPABILITY_BATCH_UPDATE",
		4:  "DATASHEET_CAPABILITY_FORMULAS",
		5:  "DATASHEET_CAPABILITY_FORMATTING",
		6:  "DATASHEET_CAPABILITY_CONDITIONAL_FORMATTING",
		7:  "DATASHEET_CAPABILITY_CHARTS",
		8:  "DATASHEET_CAPABILITY_PIVOT_TABLES",
		9:  "DATASHEET_CAPABILITY_FILTERING",
		10: "DATASHEET_CAPABILITY_SORTING",
		11: "DATASHEET_CAPABILITY_VALIDATION",
		12: "DATASHEET_CAPABILITY_COMMENTS",
		13: "DATASHEET_CAPABILITY_PROTECTION",
		14: "DATASHEET_CAPABILITY_NAMED_RANGES",
		15: "DATASHEET_CAPABILITY_MULTIPLE_SHEETS",
	}
	DatasheetCapability_value = map[string]int32{
		"DATASHEET_CAPABILITY_UNSPECIFIED":            0,
		"DATASHEET_CAPABILITY_READ":                   1,
		"DATASHEET_CAPABILITY_WRITE":                  2,
		"DATASHEET_CAPABILITY_BATCH_UPDATE":           3,
		"DATASHEET_CAPABILITY_FORMULAS":               4,
		"DATASHEET_CAPABILITY_FORMATTING":             5,
		"DATASHEET_CAPABILITY_CONDITIONAL_FORMATTING": 6,
		"DATASHEET_CAPABILITY_CHARTS":                 7,
		"DATASHEET_CAPABILITY_PIVOT_TABLES":           8,
		"DATASHEET_CAPABILITY_FILTERING":              9,
		"DATASHEET_CAPABILITY_SORTING":                10,
		"DATASHEET_CAPABILITY_VALIDATION":             11,
		"DATASHEET_CAPABILITY_COMMENTS":               12,
		"DATASHEET_CAPABILITY_PROTECTION":             13,
		"DATASHEET_CAPABILITY_NAMED_RANGES":           14,
		"DATASHEET_CAPABILITY_MULTIPLE_SHEETS":        15,
	}
)

func (x DatasheetCapability) Enum() *DatasheetCapability {
	p := new(DatasheetCapability)
	*p = x
	return p
}

func (x DatasheetCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatasheetCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[1].Descriptor()
}

func (DatasheetCapability) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[1]
}

func (x DatasheetCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DatasheetCapability.Descriptor instead.
func (DatasheetCapability) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{1}
}

// CellValueType represents the data type of a cell value
type CellValueType int32

const (
	CellValueType_CELL_VALUE_TYPE_UNSPECIFIED CellValueType = 0
	CellValueType_CELL_VALUE_TYPE_STRING      CellValueType = 1  // Text/string value
	CellValueType_CELL_VALUE_TYPE_NUMBER      CellValueType = 2  // Numeric value (integer or float)
	CellValueType_CELL_VALUE_TYPE_BOOLEAN     CellValueType = 3  // Boolean true/false
	CellValueType_CELL_VALUE_TYPE_DATE        CellValueType = 4  // Date only (no time component)
	CellValueType_CELL_VALUE_TYPE_DATETIME    CellValueType = 5  // Date and time
	CellValueType_CELL_VALUE_TYPE_FORMULA     CellValueType = 6  // Formula expression
	CellValueType_CELL_VALUE_TYPE_ERROR       CellValueType = 7  // Error value (e.g., #REF!, #DIV/0!)
	CellValueType_CELL_VALUE_TYPE_EMPTY       CellValueType = 8  // Empty/null cell
	CellValueType_CELL_VALUE_TYPE_CURRENCY    CellValueType = 9  // Currency value
	CellValueType_CELL_VALUE_TYPE_PERCENT     CellValueType = 10 // Percentage value
)

// Enum value maps for CellValueType.
var (
	CellValueType_name = map[int32]string{
		0:  "CELL_VALUE_TYPE_UNSPECIFIED",
		1:  "CELL_VALUE_TYPE_STRING",
		2:  "CELL_VALUE_TYPE_NUMBER",
		3:  "CELL_VALUE_TYPE_BOOLEAN",
		4:  "CELL_VALUE_TYPE_DATE",
		5:  "CELL_VALUE_TYPE_DATETIME",
		6:  "CELL_VALUE_TYPE_FORMULA",
		7:  "CELL_VALUE_TYPE_ERROR",
		8:  "CELL_VALUE_TYPE_EMPTY",
		9:  "CELL_VALUE_TYPE_CURRENCY",
		10: "CELL_VALUE_TYPE_PERCENT",
	}
	CellValueType_value = map[string]int32{
		"CELL_VALUE_TYPE_UNSPECIFIED": 0,
		"CELL_VALUE_TYPE_STRING":      1,
		"CELL_VALUE_TYPE_NUMBER":      2,
		"CELL_VALUE_TYPE_BOOLEAN":     3,
		"CELL_VALUE_TYPE_DATE":        4,
		"CELL_VALUE_TYPE_DATETIME":    5,
		"CELL_VALUE_TYPE_FORMULA":     6,
		"CELL_VALUE_TYPE_ERROR":       7,
		"CELL_VALUE_TYPE_EMPTY":       8,
		"CELL_VALUE_TYPE_CURRENCY":    9,
		"CELL_VALUE_TYPE_PERCENT":     10,
	}
)

func (x CellValueType) Enum() *CellValueType {
	p := new(CellValueType)
	*p = x
	return p
}

func (x CellValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[2].Descriptor()
}

func (CellValueType) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[2]
}

func (x CellValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellValueType.Descriptor instead.
func (CellValueType) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{2}
}

// ConditionOperator represents comparison operators for conditions
type ConditionOperator int32

const (
	ConditionOperator_CONDITION_OPERATOR_UNSPECIFIED  ConditionOperator = 0
	ConditionOperator_CONDITION_OPERATOR_EQ           ConditionOperator = 1  // Equal to
	ConditionOperator_CONDITION_OPERATOR_NEQ          ConditionOperator = 2  // Not equal to
	ConditionOperator_CONDITION_OPERATOR_GT           ConditionOperator = 3  // Greater than
	ConditionOperator_CONDITION_OPERATOR_LT           ConditionOperator = 4  // Less than
	ConditionOperator_CONDITION_OPERATOR_GTE          ConditionOperator = 5  // Greater than or equal to
	ConditionOperator_CONDITION_OPERATOR_LTE          ConditionOperator = 6  // Less than or equal to
	ConditionOperator_CONDITION_OPERATOR_CONTAINS     ConditionOperator = 7  // Contains substring
	ConditionOperator_CONDITION_OPERATOR_STARTS_WITH  ConditionOperator = 8  // Starts with prefix
	ConditionOperator_CONDITION_OPERATOR_ENDS_WITH    ConditionOperator = 9  // Ends with suffix
	ConditionOperator_CONDITION_OPERATOR_REGEX        ConditionOperator = 10 // Regular expression match
	ConditionOperator_CONDITION_OPERATOR_IS_EMPTY     ConditionOperator = 11 // Cell is empty
	ConditionOperator_CONDITION_OPERATOR_IS_NOT_EMPTY ConditionOperator = 12 // Cell is not empty
	ConditionOperator_CONDITION_OPERATOR_IN           ConditionOperator = 13 // Value is in list
	ConditionOperator_CONDITION_OPERATOR_NOT_IN       ConditionOperator = 14 // Value is not in list
)

// Enum value maps for ConditionOperator.
var (
	ConditionOperator_name = map[int32]string{
		0:  "CONDITION_OPERATOR_UNSPECIFIED",
		1:  "CONDITION_OPERATOR_EQ",
		2:  "CONDITION_OPERATOR_NEQ",
		3:  "CONDITION_OPERATOR_GT",
		4:  "CONDITION_OPERATOR_LT",
		5:  "CONDITION_OPERATOR_GTE",
		6:  "CONDITION_OPERATOR_LTE",
		7:  "CONDITION_OPERATOR_CONTAINS",
		8:  "CONDITION_OPERATOR_STARTS_WITH",
		9:  "CONDITION_OPERATOR_ENDS_WITH",
		10: "CONDITION_OPERATOR_REGEX",
		11: "CONDITION_OPERATOR_IS_EMPTY",
		12: "CONDITION_OPERATOR_IS_NOT_EMPTY",
		13: "CONDITION_OPERATOR_IN",
		14: "CONDITION_OPERATOR_NOT_IN",
	}
	ConditionOperator_value = map[string]int32{
		"CONDITION_OPERATOR_UNSPECIFIED":  0,
		"CONDITION_OPERATOR_EQ":           1,
		"CONDITION_OPERATOR_NEQ":          2,
		"CONDITION_OPERATOR_GT":           3,
		"CONDITION_OPERATOR_LT":           4,
		"CONDITION_OPERATOR_GTE":          5,
		"CONDITION_OPERATOR_LTE":          6,
		"CONDITION_OPERATOR_CONTAINS":     7,
		"CONDITION_OPERATOR_STARTS_WITH":  8,
		"CONDITION_OPERATOR_ENDS_WITH":    9,
		"CONDITION_OPERATOR_REGEX":        10,
		"CONDITION_OPERATOR_IS_EMPTY":     11,
		"CONDITION_OPERATOR_IS_NOT_EMPTY": 12,
		"CONDITION_OPERATOR_IN":           13,
		"CONDITION_OPERATOR_NOT_IN":       14,
	}
)

func (x ConditionOperator) Enum() *ConditionOperator {
	p := new(ConditionOperator)
	*p = x
	return p
}

func (x ConditionOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[3].Descriptor()
}

func (ConditionOperator) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[3]
}

func (x ConditionOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionOperator.Descriptor instead.
func (ConditionOperator) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{3}
}

// HorizontalAlignment represents horizontal text alignment
type HorizontalAlignment int32

const (
	HorizontalAlignment_HORIZONTAL_ALIGNMENT_UNSPECIFIED HorizontalAlignment = 0
	HorizontalAlignment_HORIZONTAL_ALIGNMENT_LEFT        HorizontalAlignment = 1
	HorizontalAlignment_HORIZONTAL_ALIGNMENT_CENTER      HorizontalAlignment = 2
	HorizontalAlignment_HORIZONTAL_ALIGNMENT_RIGHT       HorizontalAlignment = 3
)

// Enum value maps for HorizontalAlignment.
var (
	HorizontalAlignment_name = map[int32]string{
		0: "HORIZONTAL_ALIGNMENT_UNSPECIFIED",
		1: "HORIZONTAL_ALIGNMENT_LEFT",
		2: "HORIZONTAL_ALIGNMENT_CENTER",
		3: "HORIZONTAL_ALIGNMENT_RIGHT",
	}
	HorizontalAlignment_value = map[string]int32{
		"HORIZONTAL_ALIGNMENT_UNSPECIFIED": 0,
		"HORIZONTAL_ALIGNMENT_LEFT":        1,
		"HORIZONTAL_ALIGNMENT_CENTER":      2,
		"HORIZONTAL_ALIGNMENT_RIGHT":       3,
	}
)

func (x HorizontalAlignment) Enum() *HorizontalAlignment {
	p := new(HorizontalAlignment)
	*p = x
	return p
}

func (x HorizontalAlignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HorizontalAlignment) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[4].Descriptor()
}

func (HorizontalAlignment) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[4]
}

func (x HorizontalAlignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HorizontalAlignment.Descriptor instead.
func (HorizontalAlignment) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{4}
}

// VerticalAlignment represents vertical text alignment
type VerticalAlignment int32

const (
	VerticalAlignment_VERTICAL_ALIGNMENT_UNSPECIFIED VerticalAlignment = 0
	VerticalAlignment_VERTICAL_ALIGNMENT_TOP         VerticalAlignment = 1
	VerticalAlignment_VERTICAL_ALIGNMENT_MIDDLE      VerticalAlignment = 2
	VerticalAlignment_VERTICAL_ALIGNMENT_BOTTOM      VerticalAlignment = 3
)

// Enum value maps for VerticalAlignment.
var (
	VerticalAlignment_name = map[int32]string{
		0: "VERTICAL_ALIGNMENT_UNSPECIFIED",
		1: "VERTICAL_ALIGNMENT_TOP",
		2: "VERTICAL_ALIGNMENT_MIDDLE",
		3: "VERTICAL_ALIGNMENT_BOTTOM",
	}
	VerticalAlignment_value = map[string]int32{
		"VERTICAL_ALIGNMENT_UNSPECIFIED": 0,
		"VERTICAL_ALIGNMENT_TOP":         1,
		"VERTICAL_ALIGNMENT_MIDDLE":      2,
		"VERTICAL_ALIGNMENT_BOTTOM":      3,
	}
)

func (x VerticalAlignment) Enum() *VerticalAlignment {
	p := new(VerticalAlignment)
	*p = x
	return p
}

func (x VerticalAlignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerticalAlignment) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[5].Descriptor()
}

func (VerticalAlignment) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[5]
}

func (x VerticalAlignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerticalAlignment.Descriptor instead.
func (VerticalAlignment) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{5}
}

// WrapStrategy represents text wrapping behavior
type WrapStrategy int32

const (
	WrapStrategy_WRAP_STRATEGY_UNSPECIFIED WrapStrategy = 0
	WrapStrategy_WRAP_STRATEGY_OVERFLOW    WrapStrategy = 1 // Text overflows to adjacent cells
	WrapStrategy_WRAP_STRATEGY_WRAP        WrapStrategy = 2 // Text wraps within the cell
	WrapStrategy_WRAP_STRATEGY_CLIP        WrapStrategy = 3 // Text is clipped at cell boundary
)

// Enum value maps for WrapStrategy.
var (
	WrapStrategy_name = map[int32]string{
		0: "WRAP_STRATEGY_UNSPECIFIED",
		1: "WRAP_STRATEGY_OVERFLOW",
		2: "WRAP_STRATEGY_WRAP",
		3: "WRAP_STRATEGY_CLIP",
	}
	WrapStrategy_value = map[string]int32{
		"WRAP_STRATEGY_UNSPECIFIED": 0,
		"WRAP_STRATEGY_OVERFLOW":    1,
		"WRAP_STRATEGY_WRAP":        2,
		"WRAP_STRATEGY_CLIP":        3,
	}
)

func (x WrapStrategy) Enum() *WrapStrategy {
	p := new(WrapStrategy)
	*p = x
	return p
}

func (x WrapStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WrapStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[6].Descriptor()
}

func (WrapStrategy) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[6]
}

func (x WrapStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WrapStrategy.Descriptor instead.
func (WrapStrategy) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{6}
}

// LogicalOperator represents logical operators for combining conditions
type LogicalOperator int32

const (
	LogicalOperator_LOGICAL_OPERATOR_UNSPECIFIED LogicalOperator = 0
	LogicalOperator_LOGICAL_OPERATOR_AND         LogicalOperator = 1 // All conditions must match
	LogicalOperator_LOGICAL_OPERATOR_OR          LogicalOperator = 2 // Any condition must match
)

// Enum value maps for LogicalOperator.
var (
	LogicalOperator_name = map[int32]string{
		0: "LOGICAL_OPERATOR_UNSPECIFIED",
		1: "LOGICAL_OPERATOR_AND",
		2: "LOGICAL_OPERATOR_OR",
	}
	LogicalOperator_value = map[string]int32{
		"LOGICAL_OPERATOR_UNSPECIFIED": 0,
		"LOGICAL_OPERATOR_AND":         1,
		"LOGICAL_OPERATOR_OR":          2,
	}
)

func (x LogicalOperator) Enum() *LogicalOperator {
	p := new(LogicalOperator)
	*p = x
	return p
}

func (x LogicalOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[7].Descriptor()
}

func (LogicalOperator) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[7]
}

func (x LogicalOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalOperator.Descriptor instead.
func (LogicalOperator) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{7}
}

// SortOrder represents the sort direction
type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASCENDING   SortOrder = 1
	SortOrder_SORT_ORDER_DESCENDING  SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASCENDING",
		2: "SORT_ORDER_DESCENDING",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASCENDING":   1,
		"SORT_ORDER_DESCENDING":  2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[8].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[8]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{8}
}

// UpdateMode represents how to handle existing data during updates
type UpdateMode int32

const (
	UpdateMode_UPDATE_MODE_UNSPECIFIED UpdateMode = 0
	UpdateMode_UPDATE_MODE_OVERWRITE   UpdateMode = 1 // Replace existing values
	UpdateMode_UPDATE_MODE_APPEND      UpdateMode = 2 // Add after existing data
	UpdateMode_UPDATE_MODE_INSERT      UpdateMode = 3 // Insert at specific position, shifting existing
)

// Enum value maps for UpdateMode.
var (
	UpdateMode_name = map[int32]string{
		0: "UPDATE_MODE_UNSPECIFIED",
		1: "UPDATE_MODE_OVERWRITE",
		2: "UPDATE_MODE_APPEND",
		3: "UPDATE_MODE_INSERT",
	}
	UpdateMode_value = map[string]int32{
		"UPDATE_MODE_UNSPECIFIED": 0,
		"UPDATE_MODE_OVERWRITE":   1,
		"UPDATE_MODE_APPEND":      2,
		"UPDATE_MODE_INSERT":      3,
	}
)

func (x UpdateMode) Enum() *UpdateMode {
	p := new(UpdateMode)
	*p = x
	return p
}

func (x UpdateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[9].Descriptor()
}

func (UpdateMode) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[9]
}

func (x UpdateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateMode.Descriptor instead.
func (UpdateMode) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{9}
}

// ValueInputOption represents how input values should be interpreted
type ValueInputOption int32

const (
	ValueInputOption_VALUE_INPUT_OPTION_UNSPECIFIED  ValueInputOption = 0
	ValueInputOption_VALUE_INPUT_OPTION_RAW          ValueInputOption = 1 // Values are stored as-is
	ValueInputOption_VALUE_INPUT_OPTION_USER_ENTERED ValueInputOption = 2 // Values are parsed as if user typed them
)

// Enum value maps for ValueInputOption.
var (
	ValueInputOption_name = map[int32]string{
		0: "VALUE_INPUT_OPTION_UNSPECIFIED",
		1: "VALUE_INPUT_OPTION_RAW",
		2: "VALUE_INPUT_OPTION_USER_ENTERED",
	}
	ValueInputOption_value = map[string]int32{
		"VALUE_INPUT_OPTION_UNSPECIFIED":  0,
		"VALUE_INPUT_OPTION_RAW":          1,
		"VALUE_INPUT_OPTION_USER_ENTERED": 2,
	}
)

func (x ValueInputOption) Enum() *ValueInputOption {
	p := new(ValueInputOption)
	*p = x
	return p
}

func (x ValueInputOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueInputOption) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[10].Descriptor()
}

func (ValueInputOption) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[10]
}

func (x ValueInputOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueInputOption.Descriptor instead.
func (ValueInputOption) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{10}
}

// ValueRenderOption represents how values should be rendered in output
type ValueRenderOption int32

const (
	ValueRenderOption_VALUE_RENDER_OPTION_UNSPECIFIED ValueRenderOption = 0
	ValueRenderOption_VALUE_RENDER_OPTION_FORMATTED   ValueRenderOption = 1 // Return formatted display values
	ValueRenderOption_VALUE_RENDER_OPTION_UNFORMATTED ValueRenderOption = 2 // Return raw values without formatting
	ValueRenderOption_VALUE_RENDER_OPTION_FORMULA     ValueRenderOption = 3 // Return formulas instead of calculated values
)

// Enum value maps for ValueRenderOption.
var (
	ValueRenderOption_name = map[int32]string{
		0: "VALUE_RENDER_OPTION_UNSPECIFIED",
		1: "VALUE_RENDER_OPTION_FORMATTED",
		2: "VALUE_RENDER_OPTION_UNFORMATTED",
		3: "VALUE_RENDER_OPTION_FORMULA",
	}
	ValueRenderOption_value = map[string]int32{
		"VALUE_RENDER_OPTION_UNSPECIFIED": 0,
		"VALUE_RENDER_OPTION_FORMATTED":   1,
		"VALUE_RENDER_OPTION_UNFORMATTED": 2,
		"VALUE_RENDER_OPTION_FORMULA":     3,
	}
)

func (x ValueRenderOption) Enum() *ValueRenderOption {
	p := new(ValueRenderOption)
	*p = x
	return p
}

func (x ValueRenderOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueRenderOption) Descriptor() protoreflect.EnumDescriptor {
	return file_integration_datasheet_datasheet_proto_enumTypes[11].Descriptor()
}

func (ValueRenderOption) Type() protoreflect.EnumType {
	return &file_integration_datasheet_datasheet_proto_enumTypes[11]
}

func (x ValueRenderOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueRenderOption.Descriptor instead.
func (ValueRenderOption) EnumDescriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{11}
}

// CellValue represents the value of a cell with type information
type CellValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the value
	ValueType CellValueType `protobuf:"varint,1,opt,name=value_type,json=valueType,proto3,enum=integration.datasheet.v1.CellValueType" json:"value_type,omitempty"`
	// The actual value (one of the following)
	//
	// Types that are valid to be assigned to Value:
	//
	//	*CellValue_StringValue
	//	*CellValue_NumberValue
	//	*CellValue_BoolValue
	//	*CellValue_DateValue
	//	*CellValue_DatetimeValue
	//	*CellValue_FormulaValue
	//	*CellValue_ErrorValue
	Value isCellValue_Value `protobuf_oneof:"value"`
	// Original raw value as string (for display purposes)
	RawValue      string `protobuf:"bytes,9,opt,name=raw_value,json=rawValue,proto3" json:"raw_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellValue) Reset() {
	*x = CellValue{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellValue) ProtoMessage() {}

func (x *CellValue) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellValue.ProtoReflect.Descriptor instead.
func (*CellValue) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{0}
}

func (x *CellValue) GetValueType() CellValueType {
	if x != nil {
		return x.ValueType
	}
	return CellValueType_CELL_VALUE_TYPE_UNSPECIFIED
}

func (x *CellValue) GetValue() isCellValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CellValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*CellValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *CellValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*CellValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *CellValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*CellValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *CellValue) GetDateValue() string {
	if x != nil {
		if x, ok := x.Value.(*CellValue_DateValue); ok {
			return x.DateValue
		}
	}
	return ""
}

func (x *CellValue) GetDatetimeValue() string {
	if x != nil {
		if x, ok := x.Value.(*CellValue_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return ""
}

func (x *CellValue) GetFormulaValue() string {
	if x != nil {
		if x, ok := x.Value.(*CellValue_FormulaValue); ok {
			return x.FormulaValue
		}
	}
	return ""
}

func (x *CellValue) GetErrorValue() string {
	if x != nil {
		if x, ok := x.Value.(*CellValue_ErrorValue); ok {
			return x.ErrorValue
		}
	}
	return ""
}

func (x *CellValue) GetRawValue() string {
	if x != nil {
		return x.RawValue
	}
	return ""
}

type isCellValue_Value interface {
	isCellValue_Value()
}

type CellValue_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"` // String/text value
}

type CellValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"` // Numeric value
}

type CellValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"` // Boolean value
}

type CellValue_DateValue struct {
	DateValue string `protobuf:"bytes,5,opt,name=date_value,json=dateValue,proto3,oneof"` // ISO 8601 date string (YYYY-MM-DD)
}

type CellValue_DatetimeValue struct {
	DatetimeValue string `protobuf:"bytes,6,opt,name=datetime_value,json=datetimeValue,proto3,oneof"` // ISO 8601 datetime string
}

type CellValue_FormulaValue struct {
	FormulaValue string `protobuf:"bytes,7,opt,name=formula_value,json=formulaValue,proto3,oneof"` // Formula expression (e.g., "=SUM(A1:A10)")
}

type CellValue_ErrorValue struct {
	ErrorValue string `protobuf:"bytes,8,opt,name=error_value,json=errorValue,proto3,oneof"` // Error string (e.g., "#REF!", "#DIV/0!")
}

func (*CellValue_StringValue) isCellValue_Value() {}

func (*CellValue_NumberValue) isCellValue_Value() {}

func (*CellValue_BoolValue) isCellValue_Value() {}

func (*CellValue_DateValue) isCellValue_Value() {}

func (*CellValue_DatetimeValue) isCellValue_Value() {}

func (*CellValue_FormulaValue) isCellValue_Value() {}

func (*CellValue_ErrorValue) isCellValue_Value() {}

// Cell represents a single cell in a spreadsheet
type Cell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Row index (0-based)
	RowIndex int32 `protobuf:"varint,1,opt,name=row_index,json=rowIndex,proto3" json:"row_index,omitempty"`
	// Column index (0-based)
	ColumnIndex int32 `protobuf:"varint,2,opt,name=column_index,json=columnIndex,proto3" json:"column_index,omitempty"`
	// Cell value
	Value *CellValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Formatted/displayed value (after formatting applied)
	FormattedValue string `protobuf:"bytes,4,opt,name=formatted_value,json=formattedValue,proto3" json:"formatted_value,omitempty"`
	// Cell note/comment
	Note string `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	// Hyperlink URL (if cell contains a link)
	Hyperlink string `protobuf:"bytes,6,opt,name=hyperlink,proto3" json:"hyperlink,omitempty"`
	// Cell formatting information
	Format *CellFormat `protobuf:"bytes,7,opt,name=format,proto3" json:"format,omitempty"`
	// Cell address in A1 notation (e.g., "A1", "B2")
	Address string `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	// Additional cell metadata
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetRowIndex() int32 {
	if x != nil {
		return x.RowIndex
	}
	return 0
}

func (x *Cell) GetColumnIndex() int32 {
	if x != nil {
		return x.ColumnIndex
	}
	return 0
}

func (x *Cell) GetValue() *CellValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Cell) GetFormattedValue() string {
	if x != nil {
		return x.FormattedValue
	}
	return ""
}

func (x *Cell) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Cell) GetHyperlink() string {
	if x != nil {
		return x.Hyperlink
	}
	return ""
}

func (x *Cell) GetFormat() *CellFormat {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *Cell) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Cell) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CellFormat represents formatting options for a cell
type CellFormat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Background color (hex format, e.g., "#FFFFFF")
	BackgroundColor string `protobuf:"bytes,1,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	// Text color (hex format)
	TextColor string `protobuf:"bytes,2,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	// Font family
	FontFamily string `protobuf:"bytes,3,opt,name=font_family,json=fontFamily,proto3" json:"font_family,omitempty"`
	// Font size in points
	FontSize int32 `protobuf:"varint,4,opt,name=font_size,json=fontSize,proto3" json:"font_size,omitempty"`
	// Bold text
	Bold bool `protobuf:"varint,5,opt,name=bold,proto3" json:"bold,omitempty"`
	// Italic text
	Italic bool `protobuf:"varint,6,opt,name=italic,proto3" json:"italic,omitempty"`
	// Strikethrough text
	Strikethrough bool `protobuf:"varint,7,opt,name=strikethrough,proto3" json:"strikethrough,omitempty"`
	// Underline text
	Underline bool `protobuf:"varint,8,opt,name=underline,proto3" json:"underline,omitempty"`
	// Horizontal alignment
	HorizontalAlignment HorizontalAlignment `protobuf:"varint,9,opt,name=horizontal_alignment,json=horizontalAlignment,proto3,enum=integration.datasheet.v1.HorizontalAlignment" json:"horizontal_alignment,omitempty"`
	// Vertical alignment
	VerticalAlignment VerticalAlignment `protobuf:"varint,10,opt,name=vertical_alignment,json=verticalAlignment,proto3,enum=integration.datasheet.v1.VerticalAlignment" json:"vertical_alignment,omitempty"`
	// Text wrapping
	WrapStrategy WrapStrategy `protobuf:"varint,11,opt,name=wrap_strategy,json=wrapStrategy,proto3,enum=integration.datasheet.v1.WrapStrategy" json:"wrap_strategy,omitempty"`
	// Number format pattern (e.g., "#,##0.00", "0%")
	NumberFormat  string `protobuf:"bytes,12,opt,name=number_format,json=numberFormat,proto3" json:"number_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellFormat) Reset() {
	*x = CellFormat{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellFormat) ProtoMessage() {}

func (x *CellFormat) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellFormat.ProtoReflect.Descriptor instead.
func (*CellFormat) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{2}
}

func (x *CellFormat) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *CellFormat) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *CellFormat) GetFontFamily() string {
	if x != nil {
		return x.FontFamily
	}
	return ""
}

func (x *CellFormat) GetFontSize() int32 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

func (x *CellFormat) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *CellFormat) GetItalic() bool {
	if x != nil {
		return x.Italic
	}
	return false
}

func (x *CellFormat) GetStrikethrough() bool {
	if x != nil {
		return x.Strikethrough
	}
	return false
}

func (x *CellFormat) GetUnderline() bool {
	if x != nil {
		return x.Underline
	}
	return false
}

func (x *CellFormat) GetHorizontalAlignment() HorizontalAlignment {
	if x != nil {
		return x.HorizontalAlignment
	}
	return HorizontalAlignment_HORIZONTAL_ALIGNMENT_UNSPECIFIED
}

func (x *CellFormat) GetVerticalAlignment() VerticalAlignment {
	if x != nil {
		return x.VerticalAlignment
	}
	return VerticalAlignment_VERTICAL_ALIGNMENT_UNSPECIFIED
}

func (x *CellFormat) GetWrapStrategy() WrapStrategy {
	if x != nil {
		return x.WrapStrategy
	}
	return WrapStrategy_WRAP_STRATEGY_UNSPECIFIED
}

func (x *CellFormat) GetNumberFormat() string {
	if x != nil {
		return x.NumberFormat
	}
	return ""
}

// Row represents a row of cells in a spreadsheet
type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Row index (0-based)
	RowIndex int32 `protobuf:"varint,1,opt,name=row_index,json=rowIndex,proto3" json:"row_index,omitempty"`
	// Cells in this row
	Cells []*Cell `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	// Row height in pixels (if customized)
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Whether the row is hidden
	Hidden bool `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Row-level metadata
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetRowIndex() int32 {
	if x != nil {
		return x.RowIndex
	}
	return 0
}

func (x *Row) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *Row) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Row) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Row) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Column represents a column definition in a spreadsheet
type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column index (0-based)
	ColumnIndex int32 `protobuf:"varint,1,opt,name=column_index,json=columnIndex,proto3" json:"column_index,omitempty"`
	// Column header name/label
	HeaderName string `protobuf:"bytes,2,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	// Expected data type for this column
	DataType CellValueType `protobuf:"varint,3,opt,name=data_type,json=dataType,proto3,enum=integration.datasheet.v1.CellValueType" json:"data_type,omitempty"`
	// Column width in pixels
	Width int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	// Whether the column is hidden
	Hidden bool `protobuf:"varint,5,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Column letter (e.g., "A", "B", "AA")
	ColumnLetter string `protobuf:"bytes,6,opt,name=column_letter,json=columnLetter,proto3" json:"column_letter,omitempty"`
	// Column-level metadata
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{4}
}

func (x *Column) GetColumnIndex() int32 {
	if x != nil {
		return x.ColumnIndex
	}
	return 0
}

func (x *Column) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

func (x *Column) GetDataType() CellValueType {
	if x != nil {
		return x.DataType
	}
	return CellValueType_CELL_VALUE_TYPE_UNSPECIFIED
}

func (x *Column) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Column) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Column) GetColumnLetter() string {
	if x != nil {
		return x.ColumnLetter
	}
	return ""
}

func (x *Column) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Range represents a rectangular range of cells
type Range struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sheet name (required)
	SheetName string `protobuf:"bytes,1,opt,name=sheet_name,json=sheetName,proto3" json:"sheet_name,omitempty"`
	// Start row index (0-based, inclusive)
	StartRow int32 `protobuf:"varint,2,opt,name=start_row,json=startRow,proto3" json:"start_row,omitempty"`
	// Start column index (0-based, inclusive)
	StartColumn int32 `protobuf:"varint,3,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"`
	// End row index (0-based, inclusive)
	EndRow int32 `protobuf:"varint,4,opt,name=end_row,json=endRow,proto3" json:"end_row,omitempty"`
	// End column index (0-based, inclusive)
	EndColumn int32 `protobuf:"varint,5,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`
	// A1 notation representation (e.g., "Sheet1!A1:B10")
	A1Notation    string `protobuf:"bytes,6,opt,name=a1_notation,json=a1Notation,proto3" json:"a1_notation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{5}
}

func (x *Range) GetSheetName() string {
	if x != nil {
		return x.SheetName
	}
	return ""
}

func (x *Range) GetStartRow() int32 {
	if x != nil {
		return x.StartRow
	}
	return 0
}

func (x *Range) GetStartColumn() int32 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *Range) GetEndRow() int32 {
	if x != nil {
		return x.EndRow
	}
	return 0
}

func (x *Range) GetEndColumn() int32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

func (x *Range) GetA1Notation() string {
	if x != nil {
		return x.A1Notation
	}
	return ""
}

// Sheet represents a single sheet/tab within a spreadsheet
type Sheet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the sheet (provider-specific)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Sheet name/title
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Sheet index/position within the spreadsheet
	Index int32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// Column definitions (header row)
	Columns []*Column `protobuf:"bytes,4,rep,name=columns,proto3" json:"columns,omitempty"`
	// Total number of rows with data
	RowCount int32 `protobuf:"varint,5,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	// Total number of columns with data
	ColumnCount int32 `protobuf:"varint,6,opt,name=column_count,json=columnCount,proto3" json:"column_count,omitempty"`
	// Number of frozen rows (header rows)
	FrozenRows int32 `protobuf:"varint,7,opt,name=frozen_rows,json=frozenRows,proto3" json:"frozen_rows,omitempty"`
	// Number of frozen columns
	FrozenColumns int32 `protobuf:"varint,8,opt,name=frozen_columns,json=frozenColumns,proto3" json:"frozen_columns,omitempty"`
	// Whether the sheet is hidden
	Hidden bool `protobuf:"varint,9,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Sheet tab color (hex format)
	TabColor string `protobuf:"bytes,10,opt,name=tab_color,json=tabColor,proto3" json:"tab_color,omitempty"`
	// Sheet-level metadata
	Metadata map[string]string `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Provider-specific sheet data
	ProviderData  map[string]*anypb.Any `protobuf:"bytes,12,rep,name=provider_data,json=providerData,proto3" json:"provider_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sheet) Reset() {
	*x = Sheet{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sheet) ProtoMessage() {}

func (x *Sheet) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sheet.ProtoReflect.Descriptor instead.
func (*Sheet) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{6}
}

func (x *Sheet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sheet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sheet) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Sheet) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Sheet) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *Sheet) GetColumnCount() int32 {
	if x != nil {
		return x.ColumnCount
	}
	return 0
}

func (x *Sheet) GetFrozenRows() int32 {
	if x != nil {
		return x.FrozenRows
	}
	return 0
}

func (x *Sheet) GetFrozenColumns() int32 {
	if x != nil {
		return x.FrozenColumns
	}
	return 0
}

func (x *Sheet) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Sheet) GetTabColor() string {
	if x != nil {
		return x.TabColor
	}
	return ""
}

func (x *Sheet) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Sheet) GetProviderData() map[string]*anypb.Any {
	if x != nil {
		return x.ProviderData
	}
	return nil
}

// Spreadsheet represents a complete spreadsheet document
type Spreadsheet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the spreadsheet (provider-specific)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Spreadsheet name/title
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// URL to access the spreadsheet
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Sheets within this spreadsheet
	Sheets []*Sheet `protobuf:"bytes,4,rep,name=sheets,proto3" json:"sheets,omitempty"`
	// Default locale (e.g., "en_US")
	Locale string `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	// Time zone (e.g., "America/New_York")
	TimeZone string `protobuf:"bytes,6,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	// Spreadsheet owner email
	OwnerEmail string `protobuf:"bytes,7,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	// Creation timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Spreadsheet-level metadata
	Metadata map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Provider-specific spreadsheet data
	ProviderData  map[string]*anypb.Any `protobuf:"bytes,11,rep,name=provider_data,json=providerData,proto3" json:"provider_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spreadsheet) Reset() {
	*x = Spreadsheet{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spreadsheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spreadsheet) ProtoMessage() {}

func (x *Spreadsheet) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spreadsheet.ProtoReflect.Descriptor instead.
func (*Spreadsheet) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{7}
}

func (x *Spreadsheet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spreadsheet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spreadsheet) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Spreadsheet) GetSheets() []*Sheet {
	if x != nil {
		return x.Sheets
	}
	return nil
}

func (x *Spreadsheet) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Spreadsheet) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *Spreadsheet) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *Spreadsheet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Spreadsheet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Spreadsheet) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Spreadsheet) GetProviderData() map[string]*anypb.Any {
	if x != nil {
		return x.ProviderData
	}
	return nil
}

// Condition represents a filter/search condition
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column index to apply condition (0-based)
	ColumnIndex int32 `protobuf:"varint,1,opt,name=column_index,json=columnIndex,proto3" json:"column_index,omitempty"`
	// Column name (alternative to column_index)
	ColumnName string `protobuf:"bytes,2,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// Comparison operator
	Operator ConditionOperator `protobuf:"varint,3,opt,name=operator,proto3,enum=integration.datasheet.v1.ConditionOperator" json:"operator,omitempty"`
	// Value to compare against
	Value *CellValue `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// Multiple values for IN/NOT_IN operators
	Values []*CellValue `protobuf:"bytes,5,rep,name=values,proto3" json:"values,omitempty"`
	// Case-sensitive comparison (for string operations)
	CaseSensitive bool `protobuf:"varint,6,opt,name=case_sensitive,json=caseSensitive,proto3" json:"case_sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{8}
}

func (x *Condition) GetColumnIndex() int32 {
	if x != nil {
		return x.ColumnIndex
	}
	return 0
}

func (x *Condition) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *Condition) GetOperator() ConditionOperator {
	if x != nil {
		return x.Operator
	}
	return ConditionOperator_CONDITION_OPERATOR_UNSPECIFIED
}

func (x *Condition) GetValue() *CellValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Condition) GetValues() []*CellValue {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Condition) GetCaseSensitive() bool {
	if x != nil {
		return x.CaseSensitive
	}
	return false
}

// ConditionGroup represents a group of conditions with logical operators
type ConditionGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Individual conditions
	Conditions []*Condition `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// Logical operator to combine conditions
	LogicalOperator LogicalOperator `protobuf:"varint,2,opt,name=logical_operator,json=logicalOperator,proto3,enum=integration.datasheet.v1.LogicalOperator" json:"logical_operator,omitempty"`
	// Nested condition groups
	NestedGroups  []*ConditionGroup `protobuf:"bytes,3,rep,name=nested_groups,json=nestedGroups,proto3" json:"nested_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionGroup) Reset() {
	*x = ConditionGroup{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionGroup) ProtoMessage() {}

func (x *ConditionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionGroup.ProtoReflect.Descriptor instead.
func (*ConditionGroup) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{9}
}

func (x *ConditionGroup) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ConditionGroup) GetLogicalOperator() LogicalOperator {
	if x != nil {
		return x.LogicalOperator
	}
	return LogicalOperator_LOGICAL_OPERATOR_UNSPECIFIED
}

func (x *ConditionGroup) GetNestedGroups() []*ConditionGroup {
	if x != nil {
		return x.NestedGroups
	}
	return nil
}

// SortSpec represents sorting specification
type SortSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column index to sort by (0-based)
	ColumnIndex int32 `protobuf:"varint,1,opt,name=column_index,json=columnIndex,proto3" json:"column_index,omitempty"`
	// Column name (alternative to column_index)
	ColumnName string `protobuf:"bytes,2,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// Sort order
	SortOrder     SortOrder `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3,enum=integration.datasheet.v1.SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortSpec) Reset() {
	*x = SortSpec{}
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortSpec) ProtoMessage() {}

func (x *SortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_integration_datasheet_datasheet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortSpec.ProtoReflect.Descriptor instead.
func (*SortSpec) Descriptor() ([]byte, []int) {
	return file_integration_datasheet_datasheet_proto_rawDescGZIP(), []int{10}
}

func (x *SortSpec) GetColumnIndex() int32 {
	if x != nil {
		return x.ColumnIndex
	}
	return 0
}

func (x *SortSpec) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *SortSpec) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

var File_integration_datasheet_datasheet_proto protoreflect.FileDescriptor

const file_integration_datasheet_datasheet_proto_rawDesc = "" +
	"\n" +
	"%integration/datasheet/datasheet.proto\x12\x18integration.datasheet.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xf8\x02\n" +
	"\tCellValue\x12F\n" +
	"\n" +
	"value_type\x18\x01 \x01(\x0e2'.integration.datasheet.v1.CellValueTypeR\tvalueType\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x03 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\x05 \x01(\tH\x00R\tdateValue\x12'\n" +
	"\x0edatetime_value\x18\x06 \x01(\tH\x00R\rdatetimeValue\x12%\n" +
	"\rformula_value\x18\a \x01(\tH\x00R\fformulaValue\x12!\n" +
	"\verror_value\x18\b \x01(\tH\x00R\n" +
	"errorValue\x12\x1b\n" +
	"\traw_value\x18\t \x01(\tR\brawValueB\a\n" +
	"\x05value\"\xbb\x03\n" +
	"\x04Cell\x12\x1b\n" +
	"\trow_index\x18\x01 \x01(\x05R\browIndex\x12!\n" +
	"\fcolumn_index\x18\x02 \x01(\x05R\vcolumnIndex\x129\n" +
	"\x05value\x18\x03 \x01(\v2#.integration.datasheet.v1.CellValueR\x05value\x12'\n" +
	"\x0fformatted_value\x18\x04 \x01(\tR\x0eformattedValue\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x1c\n" +
	"\thyperlink\x18\x06 \x01(\tR\thyperlink\x12<\n" +
	"\x06format\x18\a \x01(\v2$.integration.datasheet.v1.CellFormatR\x06format\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12H\n" +
	"\bmetadata\x18\t \x03(\v2,.integration.datasheet.v1.Cell.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x04\n" +
	"\n" +
	"CellFormat\x12)\n" +
	"\x10background_color\x18\x01 \x01(\tR\x0fbackgroundColor\x12\x1d\n" +
	"\n" +
	"text_color\x18\x02 \x01(\tR\ttextColor\x12\x1f\n" +
	"\vfont_family\x18\x03 \x01(\tR\n" +
	"fontFamily\x12\x1b\n" +
	"\tfont_size\x18\x04 \x01(\x05R\bfontSize\x12\x12\n" +
	"\x04bold\x18\x05 \x01(\bR\x04bold\x12\x16\n" +
	"\x06italic\x18\x06 \x01(\bR\x06italic\x12$\n" +
	"\rstrikethrough\x18\a \x01(\bR\rstrikethrough\x12\x1c\n" +
	"\tunderline\x18\b \x01(\bR\tunderline\x12`\n" +
	"\x14horizontal_alignment\x18\t \x01(\x0e2-.integration.datasheet.v1.HorizontalAlignmentR\x13horizontalAlignment\x12Z\n" +
	"\x12vertical_alignment\x18\n" +
	" \x01(\x0e2+.integration.datasheet.v1.VerticalAlignmentR\x11verticalAlignment\x12K\n" +
	"\rwrap_strategy\x18\v \x01(\x0e2&.integration.datasheet.v1.WrapStrategyR\fwrapStrategy\x12#\n" +
	"\rnumber_format\x18\f \x01(\tR\fnumberFormat\"\x8e\x02\n" +
	"\x03Row\x12\x1b\n" +
	"\trow_index\x18\x01 \x01(\x05R\browIndex\x124\n" +
	"\x05cells\x18\x02 \x03(\v2\x1e.integration.datasheet.v1.CellR\x05cells\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x16\n" +
	"\x06hidden\x18\x04 \x01(\bR\x06hidden\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.integration.datasheet.v1.Row.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x02\n" +
	"\x06Column\x12!\n" +
	"\fcolumn_index\x18\x01 \x01(\x05R\vcolumnIndex\x12\x1f\n" +
	"\vheader_name\x18\x02 \x01(\tR\n" +
	"headerName\x12D\n" +
	"\tdata_type\x18\x03 \x01(\x0e2'.integration.datasheet.v1.CellValueTypeR\bdataType\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06hidden\x18\x05 \x01(\bR\x06hidden\x12#\n" +
	"\rcolumn_letter\x18\x06 \x01(\tR\fcolumnLetter\x12J\n" +
	"\bmetadata\x18\a \x03(\v2..integration.datasheet.v1.Column.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbf\x01\n" +
	"\x05Range\x12\x1d\n" +
	"\n" +
	"sheet_name\x18\x01 \x01(\tR\tsheetName\x12\x1b\n" +
	"\tstart_row\x18\x02 \x01(\x05R\bstartRow\x12!\n" +
	"\fstart_column\x18\x03 \x01(\x05R\vstartColumn\x12\x17\n" +
	"\aend_row\x18\x04 \x01(\x05R\x06endRow\x12\x1d\n" +
	"\n" +
	"end_column\x18\x05 \x01(\x05R\tendColumn\x12\x1f\n" +
	"\va1_notation\x18\x06 \x01(\tR\n" +
	"a1Notation\"\xf1\x04\n" +
	"\x05Sheet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12:\n" +
	"\acolumns\x18\x04 \x03(\v2 .integration.datasheet.v1.ColumnR\acolumns\x12\x1b\n" +
	"\trow_count\x18\x05 \x01(\x05R\browCount\x12!\n" +
	"\fcolumn_count\x18\x06 \x01(\x05R\vcolumnCount\x12\x1f\n" +
	"\vfrozen_rows\x18\a \x01(\x05R\n" +
	"frozenRows\x12%\n" +
	"\x0efrozen_columns\x18\b \x01(\x05R\rfrozenColumns\x12\x16\n" +
	"\x06hidden\x18\t \x01(\bR\x06hidden\x12\x1b\n" +
	"\ttab_color\x18\n" +
	" \x01(\tR\btabColor\x12I\n" +
	"\bmetadata\x18\v \x03(\v2-.integration.datasheet.v1.Sheet.MetadataEntryR\bmetadata\x12V\n" +
	"\rprovider_data\x18\f \x03(\v21.integration.datasheet.v1.Sheet.ProviderDataEntryR\fproviderData\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\x11ProviderDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x8b\x05\n" +
	"\vSpreadsheet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x127\n" +
	"\x06sheets\x18\x04 \x03(\v2\x1f.integration.datasheet.v1.SheetR\x06sheets\x12\x16\n" +
	"\x06locale\x18\x05 \x01(\tR\x06locale\x12\x1b\n" +
	"\ttime_zone\x18\x06 \x01(\tR\btimeZone\x12\x1f\n" +
	"\vowner_email\x18\a \x01(\tR\n" +
	"ownerEmail\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12O\n" +
	"\bmetadata\x18\n" +
	" \x03(\v23.integration.datasheet.v1.Spreadsheet.MetadataEntryR\bmetadata\x12\\\n" +
	"\rprovider_data\x18\v \x03(\v27.integration.datasheet.v1.Spreadsheet.ProviderDataEntryR\fproviderData\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aU\n" +
	"\x11ProviderDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xb7\x02\n" +
	"\tCondition\x12!\n" +
	"\fcolumn_index\x18\x01 \x01(\x05R\vcolumnIndex\x12\x1f\n" +
	"\vcolumn_name\x18\x02 \x01(\tR\n" +
	"columnName\x12G\n" +
	"\boperator\x18\x03 \x01(\x0e2+.integration.datasheet.v1.ConditionOperatorR\boperator\x129\n" +
	"\x05value\x18\x04 \x01(\v2#.integration.datasheet.v1.CellValueR\x05value\x12;\n" +
	"\x06values\x18\x05 \x03(\v2#.integration.datasheet.v1.CellValueR\x06values\x12%\n" +
	"\x0ecase_sensitive\x18\x06 \x01(\bR\rcaseSensitive\"\xfa\x01\n" +
	"\x0eConditionGroup\x12C\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2#.integration.datasheet.v1.ConditionR\n" +
	"conditions\x12T\n" +
	"\x10logical_operator\x18\x02 \x01(\x0e2).integration.datasheet.v1.LogicalOperatorR\x0flogicalOperator\x12M\n" +
	"\rnested_groups\x18\x03 \x03(\v2(.integration.datasheet.v1.ConditionGroupR\fnestedGroups\"\x92\x01\n" +
	"\bSortSpec\x12!\n" +
	"\fcolumn_index\x18\x01 \x01(\x05R\vcolumnIndex\x12\x1f\n" +
	"\vcolumn_name\x18\x02 \x01(\tR\n" +
	"columnName\x12B\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x0e2#.integration.datasheet.v1.SortOrderR\tsortOrder*\xdd\x01\n" +
	"\x15DatasheetProviderType\x12'\n" +
	"#DATASHEET_PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%DATASHEET_PROVIDER_TYPE_GOOGLE_SHEETS\x10\x01\x12(\n" +
	"$DATASHEET_PROVIDER_TYPE_EXCEL_ONLINE\x10\x02\x12$\n" +
	" DATASHEET_PROVIDER_TYPE_AIRTABLE\x10\x03\x12 \n" +
	"\x1cDATASHEET_PROVIDER_TYPE_MOCK\x10\x04*\xe6\x04\n" +
	"\x13DatasheetCapability\x12$\n" +
	" DATASHEET_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DATASHEET_CAPABILITY_READ\x10\x01\x12\x1e\n" +
	"\x1aDATASHEET_CAPABILITY_WRITE\x10\x02\x12%\n" +
	"!DATASHEET_CAPABILITY_BATCH_UPDATE\x10\x03\x12!\n" +
	"\x1dDATASHEET_CAPABILITY_FORMULAS\x10\x04\x12#\n" +
	"\x1fDATASHEET_CAPABILITY_FORMATTING\x10\x05\x12/\n" +
	"+DATASHEET_CAPABILITY_CONDITIONAL_FORMATTING\x10\x06\x12\x1f\n" +
	"\x1bDATASHEET_CAPABILITY_CHARTS\x10\a\x12%\n" +
	"!DATASHEET_CAPABILITY_PIVOT_TABLES\x10\b\x12\"\n" +
	"\x1eDATASHEET_CAPABILITY_FILTERING\x10\t\x12 \n" +
	"\x1cDATASHEET_CAPABILITY_SORTING\x10\n" +
	"\x12#\n" +
	"\x1fDATASHEET_CAPABILITY_VALIDATION\x10\v\x12!\n" +
	"\x1dDATASHEET_CAPABILITY_COMMENTS\x10\f\x12#\n" +
	"\x1fDATASHEET_CAPABILITY_PROTECTION\x10\r\x12%\n" +
	"!DATASHEET_CAPABILITY_NAMED_RANGES\x10\x0e\x12(\n" +
	"$DATASHEET_CAPABILITY_MULTIPLE_SHEETS\x10\x0f*\xcb\x02\n" +
	"\rCellValueType\x12\x1f\n" +
	"\x1bCELL_VALUE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CELL_VALUE_TYPE_STRING\x10\x01\x12\x1a\n" +
	"\x16CELL_VALUE_TYPE_NUMBER\x10\x02\x12\x1b\n" +
	"\x17CELL_VALUE_TYPE_BOOLEAN\x10\x03\x12\x18\n" +
	"\x14CELL_VALUE_TYPE_DATE\x10\x04\x12\x1c\n" +
	"\x18CELL_VALUE_TYPE_DATETIME\x10\x05\x12\x1b\n" +
	"\x17CELL_VALUE_TYPE_FORMULA\x10\x06\x12\x19\n" +
	"\x15CELL_VALUE_TYPE_ERROR\x10\a\x12\x19\n" +
	"\x15CELL_VALUE_TYPE_EMPTY\x10\b\x12\x1c\n" +
	"\x18CELL_VALUE_TYPE_CURRENCY\x10\t\x12\x1b\n" +
	"\x17CELL_VALUE_TYPE_PERCENT\x10\n" +
	"*\xe1\x03\n" +
	"\x11ConditionOperator\x12\"\n" +
	"\x1eCONDITION_OPERATOR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONDITION_OPERATOR_EQ\x10\x01\x12\x1a\n" +
	"\x16CONDITION_OPERATOR_NEQ\x10\x02\x12\x19\n" +
	"\x15CONDITION_OPERATOR_GT\x10\x03\x12\x19\n" +
	"\x15CONDITION_OPERATOR_LT\x10\x04\x12\x1a\n" +
	"\x16CONDITION_OPERATOR_GTE\x10\x05\x12\x1a\n" +
	"\x16CONDITION_OPERATOR_LTE\x10\x06\x12\x1f\n" +
	"\x1bCONDITION_OPERATOR_CONTAINS\x10\a\x12\"\n" +
	"\x1eCONDITION_OPERATOR_STARTS_WITH\x10\b\x12 \n" +
	"\x1cCONDITION_OPERATOR_ENDS_WITH\x10\t\x12\x1c\n" +
	"\x18CONDITION_OPERATOR_REGEX\x10\n" +
	"\x12\x1f\n" +
	"\x1bCONDITION_OPERATOR_IS_EMPTY\x10\v\x12#\n" +
	"\x1fCONDITION_OPERATOR_IS_NOT_EMPTY\x10\f\x12\x19\n" +
	"\x15CONDITION_OPERATOR_IN\x10\r\x12\x1d\n" +
	"\x19CONDITION_OPERATOR_NOT_IN\x10\x0e*\x9b\x01\n" +
	"\x13HorizontalAlignment\x12$\n" +
	" HORIZONTAL_ALIGNMENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19HORIZONTAL_ALIGNMENT_LEFT\x10\x01\x12\x1f\n" +
	"\x1bHORIZONTAL_ALIGNMENT_CENTER\x10\x02\x12\x1e\n" +
	"\x1aHORIZONTAL_ALIGNMENT_RIGHT\x10\x03*\x91\x01\n" +
	"\x11VerticalAlignment\x12\"\n" +
	"\x1eVERTICAL_ALIGNMENT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VERTICAL_ALIGNMENT_TOP\x10\x01\x12\x1d\n" +
	"\x19VERTICAL_ALIGNMENT_MIDDLE\x10\x02\x12\x1d\n" +
	"\x19VERTICAL_ALIGNMENT_BOTTOM\x10\x03*y\n" +
	"\fWrapStrategy\x12\x1d\n" +
	"\x19WRAP_STRATEGY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WRAP_STRATEGY_OVERFLOW\x10\x01\x12\x16\n" +
	"\x12WRAP_STRATEGY_WRAP\x10\x02\x12\x16\n" +
	"\x12WRAP_STRATEGY_CLIP\x10\x03*f\n" +
	"\x0fLogicalOperator\x12 \n" +
	"\x1cLOGICAL_OPERATOR_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LOGICAL_OPERATOR_AND\x10\x01\x12\x17\n" +
	"\x13LOGICAL_OPERATOR_OR\x10\x02*\\\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SORT_ORDER_ASCENDING\x10\x01\x12\x19\n" +
	"\x15SORT_ORDER_DESCENDING\x10\x02*t\n" +
	"\n" +
	"UpdateMode\x12\x1b\n" +
	"\x17UPDATE_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15UPDATE_MODE_OVERWRITE\x10\x01\x12\x16\n" +
	"\x12UPDATE_MODE_APPEND\x10\x02\x12\x16\n" +
	"\x12UPDATE_MODE_INSERT\x10\x03*w\n" +
	"\x10ValueInputOption\x12\"\n" +
	"\x1eVALUE_INPUT_OPTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16VALUE_INPUT_OPTION_RAW\x10\x01\x12#\n" +
	"\x1fVALUE_INPUT_OPTION_USER_ENTERED\x10\x02*\xa1\x01\n" +
	"\x11ValueRenderOption\x12#\n" +
	"\x1fVALUE_RENDER_OPTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dVALUE_RENDER_OPTION_FORMATTED\x10\x01\x12#\n" +
	"\x1fVALUE_RENDER_OPTION_UNFORMATTED\x10\x02\x12\x1f\n" +
	"\x1bVALUE_RENDER_OPTION_FORMULA\x10\x03B\xfa\x01\n" +
	"\x1ccom.integration.datasheet.v1B\x0eDatasheetProtoP\x01ZHgithub.com/erniealice/esqyma/golang/v1/integration/datasheet;datasheetv1\xa2\x02\x03IDX\xaa\x02\x18Integration.Datasheet.V1\xca\x02\x18Integration\\Datasheet\\V1\xe2\x02$Integration\\Datasheet\\V1\\GPBMetadata\xea\x02\x1aIntegration::Datasheet::V1b\x06proto3"

var (
	file_integration_datasheet_datasheet_proto_rawDescOnce sync.Once
	file_integration_datasheet_datasheet_proto_rawDescData []byte
)

func file_integration_datasheet_datasheet_proto_rawDescGZIP() []byte {
	file_integration_datasheet_datasheet_proto_rawDescOnce.Do(func() {
		file_integration_datasheet_datasheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_datasheet_datasheet_proto_rawDesc), len(file_integration_datasheet_datasheet_proto_rawDesc)))
	})
	return file_integration_datasheet_datasheet_proto_rawDescData
}

var file_integration_datasheet_datasheet_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_integration_datasheet_datasheet_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_integration_datasheet_datasheet_proto_goTypes = []any{
	(DatasheetProviderType)(0),    // 0: integration.datasheet.v1.DatasheetProviderType
	(DatasheetCapability)(0),      // 1: integration.datasheet.v1.DatasheetCapability
	(CellValueType)(0),            // 2: integration.datasheet.v1.CellValueType
	(ConditionOperator)(0),        // 3: integration.datasheet.v1.ConditionOperator
	(HorizontalAlignment)(0),      // 4: integration.datasheet.v1.HorizontalAlignment
	(VerticalAlignment)(0),        // 5: integration.datasheet.v1.VerticalAlignment
	(WrapStrategy)(0),             // 6: integration.datasheet.v1.WrapStrategy
	(LogicalOperator)(0),          // 7: integration.datasheet.v1.LogicalOperator
	(SortOrder)(0),                // 8: integration.datasheet.v1.SortOrder
	(UpdateMode)(0),               // 9: integration.datasheet.v1.UpdateMode
	(ValueInputOption)(0),         // 10: integration.datasheet.v1.ValueInputOption
	(ValueRenderOption)(0),        // 11: integration.datasheet.v1.ValueRenderOption
	(*CellValue)(nil),             // 12: integration.datasheet.v1.CellValue
	(*Cell)(nil),                  // 13: integration.datasheet.v1.Cell
	(*CellFormat)(nil),            // 14: integration.datasheet.v1.CellFormat
	(*Row)(nil),                   // 15: integration.datasheet.v1.Row
	(*Column)(nil),                // 16: integration.datasheet.v1.Column
	(*Range)(nil),                 // 17: integration.datasheet.v1.Range
	(*Sheet)(nil),                 // 18: integration.datasheet.v1.Sheet
	(*Spreadsheet)(nil),           // 19: integration.datasheet.v1.Spreadsheet
	(*Condition)(nil),             // 20: integration.datasheet.v1.Condition
	(*ConditionGroup)(nil),        // 21: integration.datasheet.v1.ConditionGroup
	(*SortSpec)(nil),              // 22: integration.datasheet.v1.SortSpec
	nil,                           // 23: integration.datasheet.v1.Cell.MetadataEntry
	nil,                           // 24: integration.datasheet.v1.Row.MetadataEntry
	nil,                           // 25: integration.datasheet.v1.Column.MetadataEntry
	nil,                           // 26: integration.datasheet.v1.Sheet.MetadataEntry
	nil,                           // 27: integration.datasheet.v1.Sheet.ProviderDataEntry
	nil,                           // 28: integration.datasheet.v1.Spreadsheet.MetadataEntry
	nil,                           // 29: integration.datasheet.v1.Spreadsheet.ProviderDataEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 31: google.protobuf.Any
}
var file_integration_datasheet_datasheet_proto_depIdxs = []int32{
	2,  // 0: integration.datasheet.v1.CellValue.value_type:type_name -> integration.datasheet.v1.CellValueType
	12, // 1: integration.datasheet.v1.Cell.value:type_name -> integration.datasheet.v1.CellValue
	14, // 2: integration.datasheet.v1.Cell.format:type_name -> integration.datasheet.v1.CellFormat
	23, // 3: integration.datasheet.v1.Cell.metadata:type_name -> integration.datasheet.v1.Cell.MetadataEntry
	4,  // 4: integration.datasheet.v1.CellFormat.horizontal_alignment:type_name -> integration.datasheet.v1.HorizontalAlignment
	5,  // 5: integration.datasheet.v1.CellFormat.vertical_alignment:type_name -> integration.datasheet.v1.VerticalAlignment
	6,  // 6: integration.datasheet.v1.CellFormat.wrap_strategy:type_name -> integration.datasheet.v1.WrapStrategy
	13, // 7: integration.datasheet.v1.Row.cells:type_name -> integration.datasheet.v1.Cell
	24, // 8: integration.datasheet.v1.Row.metadata:type_name -> integration.datasheet.v1.Row.MetadataEntry
	2,  // 9: integration.datasheet.v1.Column.data_type:type_name -> integration.datasheet.v1.CellValueType
	25, // 10: integration.datasheet.v1.Column.metadata:type_name -> integration.datasheet.v1.Column.MetadataEntry
	16, // 11: integration.datasheet.v1.Sheet.columns:type_name -> integration.datasheet.v1.Column
	26, // 12: integration.datasheet.v1.Sheet.metadata:type_name -> integration.datasheet.v1.Sheet.MetadataEntry
	27, // 13: integration.datasheet.v1.Sheet.provider_data:type_name -> integration.datasheet.v1.Sheet.ProviderDataEntry
	18, // 14: integration.datasheet.v1.Spreadsheet.sheets:type_name -> integration.datasheet.v1.Sheet
	30, // 15: integration.datasheet.v1.Spreadsheet.created_at:type_name -> google.protobuf.Timestamp
	30, // 16: integration.datasheet.v1.Spreadsheet.updated_at:type_name -> google.protobuf.Timestamp
	28, // 17: integration.datasheet.v1.Spreadsheet.metadata:type_name -> integration.datasheet.v1.Spreadsheet.MetadataEntry
	29, // 18: integration.datasheet.v1.Spreadsheet.provider_data:type_name -> integration.datasheet.v1.Spreadsheet.ProviderDataEntry
	3,  // 19: integration.datasheet.v1.Condition.operator:type_name -> integration.datasheet.v1.ConditionOperator
	12, // 20: integration.datasheet.v1.Condition.value:type_name -> integration.datasheet.v1.CellValue
	12, // 21: integration.datasheet.v1.Condition.values:type_name -> integration.datasheet.v1.CellValue
	20, // 22: integration.datasheet.v1.ConditionGroup.conditions:type_name -> integration.datasheet.v1.Condition
	7,  // 23: integration.datasheet.v1.ConditionGroup.logical_operator:type_name -> integration.datasheet.v1.LogicalOperator
	21, // 24: integration.datasheet.v1.ConditionGroup.nested_groups:type_name -> integration.datasheet.v1.ConditionGroup
	8,  // 25: integration.datasheet.v1.SortSpec.sort_order:type_name -> integration.datasheet.v1.SortOrder
	31, // 26: integration.datasheet.v1.Sheet.ProviderDataEntry.value:type_name -> google.protobuf.Any
	31, // 27: integration.datasheet.v1.Spreadsheet.ProviderDataEntry.value:type_name -> google.protobuf.Any
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_integration_datasheet_datasheet_proto_init() }
func file_integration_datasheet_datasheet_proto_init() {
	if File_integration_datasheet_datasheet_proto != nil {
		return
	}
	file_integration_datasheet_datasheet_proto_msgTypes[0].OneofWrappers = []any{
		(*CellValue_StringValue)(nil),
		(*CellValue_NumberValue)(nil),
		(*CellValue_BoolValue)(nil),
		(*CellValue_DateValue)(nil),
		(*CellValue_DatetimeValue)(nil),
		(*CellValue_FormulaValue)(nil),
		(*CellValue_ErrorValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_datasheet_datasheet_proto_rawDesc), len(file_integration_datasheet_datasheet_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integration_datasheet_datasheet_proto_goTypes,
		DependencyIndexes: file_integration_datasheet_datasheet_proto_depIdxs,
		EnumInfos:         file_integration_datasheet_datasheet_proto_enumTypes,
		MessageInfos:      file_integration_datasheet_datasheet_proto_msgTypes,
	}.Build()
	File_integration_datasheet_datasheet_proto = out.File
	file_integration_datasheet_datasheet_proto_goTypes = nil
	file_integration_datasheet_datasheet_proto_depIdxs = nil
}
