// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/workflow/activity_execution_log/activity_execution_log.proto

package workflowv1

import (
	common "github.com/erniealice/esqyma/pkg/schema/v1/domain/common"
	_ "github.com/erniealice/esqyma/pkg/schema/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActivityExecutionLog records the execution details of a workflow activity
type ActivityExecutionLog struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId         string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ActivityId         string                 `protobuf:"bytes,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityTemplateId string                 `protobuf:"bytes,4,opt,name=activity_template_id,json=activityTemplateId,proto3" json:"activity_template_id,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "success", "failed", "in_progress"
	StartTime          string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	InputSnapshotJson  string                 `protobuf:"bytes,8,opt,name=input_snapshot_json,json=inputSnapshotJson,proto3" json:"input_snapshot_json,omitempty"`
	OutputSnapshotJson string                 `protobuf:"bytes,9,opt,name=output_snapshot_json,json=outputSnapshotJson,proto3" json:"output_snapshot_json,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Standard audit fields
	CreatedBy          string `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	DateCreated        int64  `protobuf:"varint,12,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	DateCreatedString  string `protobuf:"bytes,13,opt,name=date_created_string,json=dateCreatedString,proto3" json:"date_created_string,omitempty"`
	DateModified       int64  `protobuf:"varint,14,opt,name=date_modified,json=dateModified,proto3" json:"date_modified,omitempty"`
	DateModifiedString string `protobuf:"bytes,15,opt,name=date_modified_string,json=dateModifiedString,proto3" json:"date_modified_string,omitempty"`
	Active             bool   `protobuf:"varint,16,opt,name=active,proto3" json:"active,omitempty"`
	WorkspaceId        string `protobuf:"bytes,17,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ActivityExecutionLog) Reset() {
	*x = ActivityExecutionLog{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityExecutionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityExecutionLog) ProtoMessage() {}

func (x *ActivityExecutionLog) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityExecutionLog.ProtoReflect.Descriptor instead.
func (*ActivityExecutionLog) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityExecutionLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActivityExecutionLog) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ActivityExecutionLog) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *ActivityExecutionLog) GetActivityTemplateId() string {
	if x != nil {
		return x.ActivityTemplateId
	}
	return ""
}

func (x *ActivityExecutionLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActivityExecutionLog) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ActivityExecutionLog) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ActivityExecutionLog) GetInputSnapshotJson() string {
	if x != nil {
		return x.InputSnapshotJson
	}
	return ""
}

func (x *ActivityExecutionLog) GetOutputSnapshotJson() string {
	if x != nil {
		return x.OutputSnapshotJson
	}
	return ""
}

func (x *ActivityExecutionLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ActivityExecutionLog) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ActivityExecutionLog) GetDateCreated() int64 {
	if x != nil {
		return x.DateCreated
	}
	return 0
}

func (x *ActivityExecutionLog) GetDateCreatedString() string {
	if x != nil {
		return x.DateCreatedString
	}
	return ""
}

func (x *ActivityExecutionLog) GetDateModified() int64 {
	if x != nil {
		return x.DateModified
	}
	return 0
}

func (x *ActivityExecutionLog) GetDateModifiedString() string {
	if x != nil {
		return x.DateModifiedString
	}
	return ""
}

func (x *ActivityExecutionLog) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ActivityExecutionLog) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// CreateActivityExecutionLogRequest
type CreateActivityExecutionLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ActivityExecutionLog  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityExecutionLogRequest) Reset() {
	*x = CreateActivityExecutionLogRequest{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityExecutionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityExecutionLogRequest) ProtoMessage() {}

func (x *CreateActivityExecutionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityExecutionLogRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityExecutionLogRequest) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{1}
}

func (x *CreateActivityExecutionLogRequest) GetData() *ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateActivityExecutionLogResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          []*ActivityExecutionLog `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                    `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error           `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityExecutionLogResponse) Reset() {
	*x = CreateActivityExecutionLogResponse{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityExecutionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityExecutionLogResponse) ProtoMessage() {}

func (x *CreateActivityExecutionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityExecutionLogResponse.ProtoReflect.Descriptor instead.
func (*CreateActivityExecutionLogResponse) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{2}
}

func (x *CreateActivityExecutionLogResponse) GetData() []*ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateActivityExecutionLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateActivityExecutionLogResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// ReadActivityExecutionLogRequest
type ReadActivityExecutionLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ActivityExecutionLog  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadActivityExecutionLogRequest) Reset() {
	*x = ReadActivityExecutionLogRequest{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadActivityExecutionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadActivityExecutionLogRequest) ProtoMessage() {}

func (x *ReadActivityExecutionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadActivityExecutionLogRequest.ProtoReflect.Descriptor instead.
func (*ReadActivityExecutionLogRequest) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{3}
}

func (x *ReadActivityExecutionLogRequest) GetData() *ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadActivityExecutionLogResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          []*ActivityExecutionLog `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                    `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error           `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadActivityExecutionLogResponse) Reset() {
	*x = ReadActivityExecutionLogResponse{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadActivityExecutionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadActivityExecutionLogResponse) ProtoMessage() {}

func (x *ReadActivityExecutionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadActivityExecutionLogResponse.ProtoReflect.Descriptor instead.
func (*ReadActivityExecutionLogResponse) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{4}
}

func (x *ReadActivityExecutionLogResponse) GetData() []*ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadActivityExecutionLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadActivityExecutionLogResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// UpdateActivityExecutionLogRequest
type UpdateActivityExecutionLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ActivityExecutionLog  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityExecutionLogRequest) Reset() {
	*x = UpdateActivityExecutionLogRequest{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityExecutionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityExecutionLogRequest) ProtoMessage() {}

func (x *UpdateActivityExecutionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityExecutionLogRequest.ProtoReflect.Descriptor instead.
func (*UpdateActivityExecutionLogRequest) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateActivityExecutionLogRequest) GetData() *ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateActivityExecutionLogResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          []*ActivityExecutionLog `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                    `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error           `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActivityExecutionLogResponse) Reset() {
	*x = UpdateActivityExecutionLogResponse{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityExecutionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityExecutionLogResponse) ProtoMessage() {}

func (x *UpdateActivityExecutionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityExecutionLogResponse.ProtoReflect.Descriptor instead.
func (*UpdateActivityExecutionLogResponse) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateActivityExecutionLogResponse) GetData() []*ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateActivityExecutionLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateActivityExecutionLogResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// DeleteActivityExecutionLogRequest
type DeleteActivityExecutionLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ActivityExecutionLog  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityExecutionLogRequest) Reset() {
	*x = DeleteActivityExecutionLogRequest{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityExecutionLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityExecutionLogRequest) ProtoMessage() {}

func (x *DeleteActivityExecutionLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityExecutionLogRequest.ProtoReflect.Descriptor instead.
func (*DeleteActivityExecutionLogRequest) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteActivityExecutionLogRequest) GetData() *ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteActivityExecutionLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityExecutionLogResponse) Reset() {
	*x = DeleteActivityExecutionLogResponse{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityExecutionLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityExecutionLogResponse) ProtoMessage() {}

func (x *DeleteActivityExecutionLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityExecutionLogResponse.ProtoReflect.Descriptor instead.
func (*DeleteActivityExecutionLogResponse) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteActivityExecutionLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteActivityExecutionLogResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// ListActivityExecutionLogsRequest
type ListActivityExecutionLogsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Search        *common.SearchRequest     `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Filters       *common.FilterRequest     `protobuf:"bytes,2,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	Sort          *common.SortRequest       `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityExecutionLogsRequest) Reset() {
	*x = ListActivityExecutionLogsRequest{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityExecutionLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityExecutionLogsRequest) ProtoMessage() {}

func (x *ListActivityExecutionLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityExecutionLogsRequest.ProtoReflect.Descriptor instead.
func (*ListActivityExecutionLogsRequest) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{9}
}

func (x *ListActivityExecutionLogsRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ListActivityExecutionLogsRequest) GetFilters() *common.FilterRequest {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListActivityExecutionLogsRequest) GetSort() *common.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListActivityExecutionLogsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListActivityExecutionLogsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          []*ActivityExecutionLog `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Success       bool                    `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         *common.Error           `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	NextPageToken *string                 `protobuf:"bytes,4,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivityExecutionLogsResponse) Reset() {
	*x = ListActivityExecutionLogsResponse{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivityExecutionLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityExecutionLogsResponse) ProtoMessage() {}

func (x *ListActivityExecutionLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityExecutionLogsResponse.ProtoReflect.Descriptor instead.
func (*ListActivityExecutionLogsResponse) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{10}
}

func (x *ListActivityExecutionLogsResponse) GetData() []*ActivityExecutionLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListActivityExecutionLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListActivityExecutionLogsResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ListActivityExecutionLogsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

// GetActivityExecutionLogListPageDataRequest
type GetActivityExecutionLogListPageDataRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	Filters       *common.FilterRequest     `protobuf:"bytes,2,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	Sort          *common.SortRequest       `protobuf:"bytes,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Search        *common.SearchRequest     `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityExecutionLogListPageDataRequest) Reset() {
	*x = GetActivityExecutionLogListPageDataRequest{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityExecutionLogListPageDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityExecutionLogListPageDataRequest) ProtoMessage() {}

func (x *GetActivityExecutionLogListPageDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityExecutionLogListPageDataRequest.ProtoReflect.Descriptor instead.
func (*GetActivityExecutionLogListPageDataRequest) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{11}
}

func (x *GetActivityExecutionLogListPageDataRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetActivityExecutionLogListPageDataRequest) GetFilters() *common.FilterRequest {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetActivityExecutionLogListPageDataRequest) GetSort() *common.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *GetActivityExecutionLogListPageDataRequest) GetSearch() *common.SearchRequest {
	if x != nil {
		return x.Search
	}
	return nil
}

type GetActivityExecutionLogListPageDataResponse struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	ActivityExecutionLogList []*ActivityExecutionLog    `protobuf:"bytes,1,rep,name=activity_execution_log_list,json=activityExecutionLogList,proto3" json:"activity_execution_log_list,omitempty"`
	Pagination               *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	SearchResults            []*common.SearchResult     `protobuf:"bytes,3,rep,name=search_results,json=searchResults,proto3" json:"search_results,omitempty"`
	Success                  bool                       `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error                    *common.Error              `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetActivityExecutionLogListPageDataResponse) Reset() {
	*x = GetActivityExecutionLogListPageDataResponse{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityExecutionLogListPageDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityExecutionLogListPageDataResponse) ProtoMessage() {}

func (x *GetActivityExecutionLogListPageDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityExecutionLogListPageDataResponse.ProtoReflect.Descriptor instead.
func (*GetActivityExecutionLogListPageDataResponse) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{12}
}

func (x *GetActivityExecutionLogListPageDataResponse) GetActivityExecutionLogList() []*ActivityExecutionLog {
	if x != nil {
		return x.ActivityExecutionLogList
	}
	return nil
}

func (x *GetActivityExecutionLogListPageDataResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetActivityExecutionLogListPageDataResponse) GetSearchResults() []*common.SearchResult {
	if x != nil {
		return x.SearchResults
	}
	return nil
}

func (x *GetActivityExecutionLogListPageDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetActivityExecutionLogListPageDataResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// GetActivityExecutionLogItemPageDataRequest
type GetActivityExecutionLogItemPageDataRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ActivityExecutionLogId string                 `protobuf:"bytes,1,opt,name=activity_execution_log_id,json=activityExecutionLogId,proto3" json:"activity_execution_log_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetActivityExecutionLogItemPageDataRequest) Reset() {
	*x = GetActivityExecutionLogItemPageDataRequest{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityExecutionLogItemPageDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityExecutionLogItemPageDataRequest) ProtoMessage() {}

func (x *GetActivityExecutionLogItemPageDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityExecutionLogItemPageDataRequest.ProtoReflect.Descriptor instead.
func (*GetActivityExecutionLogItemPageDataRequest) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{13}
}

func (x *GetActivityExecutionLogItemPageDataRequest) GetActivityExecutionLogId() string {
	if x != nil {
		return x.ActivityExecutionLogId
	}
	return ""
}

type GetActivityExecutionLogItemPageDataResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActivityExecutionLog *ActivityExecutionLog  `protobuf:"bytes,1,opt,name=activity_execution_log,json=activityExecutionLog,proto3,oneof" json:"activity_execution_log,omitempty"`
	Success              bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                *common.Error          `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetActivityExecutionLogItemPageDataResponse) Reset() {
	*x = GetActivityExecutionLogItemPageDataResponse{}
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityExecutionLogItemPageDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityExecutionLogItemPageDataResponse) ProtoMessage() {}

func (x *GetActivityExecutionLogItemPageDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityExecutionLogItemPageDataResponse.ProtoReflect.Descriptor instead.
func (*GetActivityExecutionLogItemPageDataResponse) Descriptor() ([]byte, []int) {
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP(), []int{14}
}

func (x *GetActivityExecutionLogItemPageDataResponse) GetActivityExecutionLog() *ActivityExecutionLog {
	if x != nil {
		return x.ActivityExecutionLog
	}
	return nil
}

func (x *GetActivityExecutionLogItemPageDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetActivityExecutionLogItemPageDataResponse) GetError() *common.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_domain_workflow_activity_execution_log_activity_execution_log_proto protoreflect.FileDescriptor

const file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDesc = "" +
	"\n" +
	"Cdomain/workflow/activity_execution_log/activity_execution_log.proto\x12\x12domain.workflow.v1\x1a\x19domain/common/error.proto\x1a\x1edomain/common/pagination.proto\x1a\x1adomain/common/filter.proto\x1a\x18domain/common/sort.proto\x1a\x1adomain/common/search.proto\x1a\x10options/db.proto\"\xdd\x05\n" +
	"\x14ActivityExecutionLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\vworkflow_id\x18\x02 \x01(\tB\x10\x82\xb5\x18\f\n" +
	"\bworkflow\x18\x01R\n" +
	"workflowId\x121\n" +
	"\vactivity_id\x18\x03 \x01(\tB\x10\x82\xb5\x18\f\n" +
	"\bactivity\x18\x01R\n" +
	"activityId\x12K\n" +
	"\x14activity_template_id\x18\x04 \x01(\tB\x19\x82\xb5\x18\x15\n" +
	"\x11activity_template\x18\x01R\x12activityTemplateId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12.\n" +
	"\x13input_snapshot_json\x18\b \x01(\tR\x11inputSnapshotJson\x120\n" +
	"\x14output_snapshot_json\x18\t \x01(\tR\x12outputSnapshotJson\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x12!\n" +
	"\fdate_created\x18\f \x01(\x03R\vdateCreated\x12.\n" +
	"\x13date_created_string\x18\r \x01(\tR\x11dateCreatedString\x12#\n" +
	"\rdate_modified\x18\x0e \x01(\x03R\fdateModified\x120\n" +
	"\x14date_modified_string\x18\x0f \x01(\tR\x12dateModifiedString\x12\"\n" +
	"\x06active\x18\x10 \x01(\bB\n" +
	"\x82\xb5\x18\x06\"\x04trueR\x06active\x124\n" +
	"\fworkspace_id\x18\x11 \x01(\tB\x11\x82\xb5\x18\r\n" +
	"\tworkspace\x18\x01R\vworkspaceId:\x06\x8a\xb5\x18\x02\b\x01\"a\n" +
	"!CreateActivityExecutionLogRequest\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\"\xba\x01\n" +
	"\"CreateActivityExecutionLogResponse\x12<\n" +
	"\x04data\x18\x01 \x03(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"_\n" +
	"\x1fReadActivityExecutionLogRequest\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\"\xb8\x01\n" +
	" ReadActivityExecutionLogResponse\x12<\n" +
	"\x04data\x18\x01 \x03(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"a\n" +
	"!UpdateActivityExecutionLogRequest\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\"\xba\x01\n" +
	"\"UpdateActivityExecutionLogResponse\x12<\n" +
	"\x04data\x18\x01 \x03(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"a\n" +
	"!DeleteActivityExecutionLogRequest\x12<\n" +
	"\x04data\x18\x01 \x01(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\"|\n" +
	"\"DeleteActivityExecutionLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xd1\x02\n" +
	" ListActivityExecutionLogsRequest\x12<\n" +
	"\x06search\x18\x01 \x01(\v2\x1f.domain.common.v1.SearchRequestH\x00R\x06search\x88\x01\x01\x12>\n" +
	"\afilters\x18\x02 \x01(\v2\x1f.domain.common.v1.FilterRequestH\x01R\afilters\x88\x01\x01\x126\n" +
	"\x04sort\x18\x03 \x01(\v2\x1d.domain.common.v1.SortRequestH\x02R\x04sort\x88\x01\x01\x12H\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2#.domain.common.v1.PaginationRequestH\x03R\n" +
	"pagination\x88\x01\x01B\t\n" +
	"\a_searchB\n" +
	"\n" +
	"\b_filtersB\a\n" +
	"\x05_sortB\r\n" +
	"\v_pagination\"\xfa\x01\n" +
	"!ListActivityExecutionLogsResponse\x12<\n" +
	"\x04data\x18\x01 \x03(\v2(.domain.workflow.v1.ActivityExecutionLogR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x00R\x05error\x88\x01\x01\x12+\n" +
	"\x0fnext_page_token\x18\x04 \x01(\tH\x01R\rnextPageToken\x88\x01\x01B\b\n" +
	"\x06_errorB\x12\n" +
	"\x10_next_page_token\"\xdb\x02\n" +
	"*GetActivityExecutionLogListPageDataRequest\x12H\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.domain.common.v1.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01\x12>\n" +
	"\afilters\x18\x02 \x01(\v2\x1f.domain.common.v1.FilterRequestH\x01R\afilters\x88\x01\x01\x126\n" +
	"\x04sort\x18\x03 \x01(\v2\x1d.domain.common.v1.SortRequestH\x02R\x04sort\x88\x01\x01\x12<\n" +
	"\x06search\x18\x04 \x01(\v2\x1f.domain.common.v1.SearchRequestH\x03R\x06search\x88\x01\x01B\r\n" +
	"\v_paginationB\n" +
	"\n" +
	"\b_filtersB\a\n" +
	"\x05_sortB\t\n" +
	"\a_search\"\x8f\x03\n" +
	"+GetActivityExecutionLogListPageDataResponse\x12g\n" +
	"\x1bactivity_execution_log_list\x18\x01 \x03(\v2(.domain.workflow.v1.ActivityExecutionLogR\x18activityExecutionLogList\x12I\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.domain.common.v1.PaginationResponseH\x00R\n" +
	"pagination\x88\x01\x01\x12E\n" +
	"\x0esearch_results\x18\x03 \x03(\v2\x1e.domain.common.v1.SearchResultR\rsearchResults\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x17.domain.common.v1.ErrorH\x01R\x05error\x88\x01\x01B\r\n" +
	"\v_paginationB\b\n" +
	"\x06_error\"g\n" +
	"*GetActivityExecutionLogItemPageDataRequest\x129\n" +
	"\x19activity_execution_log_id\x18\x01 \x01(\tR\x16activityExecutionLogId\"\x85\x02\n" +
	"+GetActivityExecutionLogItemPageDataResponse\x12c\n" +
	"\x16activity_execution_log\x18\x01 \x01(\v2(.domain.workflow.v1.ActivityExecutionLogH\x00R\x14activityExecutionLog\x88\x01\x01\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x122\n" +
	"\x05error\x18\x03 \x01(\v2\x17.domain.common.v1.ErrorH\x01R\x05error\x88\x01\x01B\x19\n" +
	"\x17_activity_execution_logB\b\n" +
	"\x06_error2\xb2\b\n" +
	"!ActivityExecutionLogDomainService\x12\x8b\x01\n" +
	"\x1aCreateActivityExecutionLog\x125.domain.workflow.v1.CreateActivityExecutionLogRequest\x1a6.domain.workflow.v1.CreateActivityExecutionLogResponse\x12\x85\x01\n" +
	"\x18ReadActivityExecutionLog\x123.domain.workflow.v1.ReadActivityExecutionLogRequest\x1a4.domain.workflow.v1.ReadActivityExecutionLogResponse\x12\x8b\x01\n" +
	"\x1aUpdateActivityExecutionLog\x125.domain.workflow.v1.UpdateActivityExecutionLogRequest\x1a6.domain.workflow.v1.UpdateActivityExecutionLogResponse\x12\x8b\x01\n" +
	"\x1aDeleteActivityExecutionLog\x125.domain.workflow.v1.DeleteActivityExecutionLogRequest\x1a6.domain.workflow.v1.DeleteActivityExecutionLogResponse\x12\x88\x01\n" +
	"\x19ListActivityExecutionLogs\x124.domain.workflow.v1.ListActivityExecutionLogsRequest\x1a5.domain.workflow.v1.ListActivityExecutionLogsResponse\x12\xa6\x01\n" +
	"#GetActivityExecutionLogListPageData\x12>.domain.workflow.v1.GetActivityExecutionLogListPageDataRequest\x1a?.domain.workflow.v1.GetActivityExecutionLogListPageDataResponse\x12\xa6\x01\n" +
	"#GetActivityExecutionLogItemPageData\x12>.domain.workflow.v1.GetActivityExecutionLogItemPageDataRequest\x1a?.domain.workflow.v1.GetActivityExecutionLogItemPageDataResponseB\xfb\x01\n" +
	"\x16com.domain.workflow.v1B\x19ActivityExecutionLogProtoP\x01Z\\github.com/erniealice/esqyma/pkg/schema/v1/domain/workflow/activity_execution_log;workflowv1\xa2\x02\x03DWX\xaa\x02\x12Domain.Workflow.V1\xca\x02\x12Domain\\Workflow\\V1\xe2\x02\x1eDomain\\Workflow\\V1\\GPBMetadata\xea\x02\x14Domain::Workflow::V1b\x06proto3"

var (
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescOnce sync.Once
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescData []byte
)

func file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescGZIP() []byte {
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescOnce.Do(func() {
		file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDesc), len(file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDesc)))
	})
	return file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDescData
}

var file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_domain_workflow_activity_execution_log_activity_execution_log_proto_goTypes = []any{
	(*ActivityExecutionLog)(nil),                        // 0: domain.workflow.v1.ActivityExecutionLog
	(*CreateActivityExecutionLogRequest)(nil),           // 1: domain.workflow.v1.CreateActivityExecutionLogRequest
	(*CreateActivityExecutionLogResponse)(nil),          // 2: domain.workflow.v1.CreateActivityExecutionLogResponse
	(*ReadActivityExecutionLogRequest)(nil),             // 3: domain.workflow.v1.ReadActivityExecutionLogRequest
	(*ReadActivityExecutionLogResponse)(nil),            // 4: domain.workflow.v1.ReadActivityExecutionLogResponse
	(*UpdateActivityExecutionLogRequest)(nil),           // 5: domain.workflow.v1.UpdateActivityExecutionLogRequest
	(*UpdateActivityExecutionLogResponse)(nil),          // 6: domain.workflow.v1.UpdateActivityExecutionLogResponse
	(*DeleteActivityExecutionLogRequest)(nil),           // 7: domain.workflow.v1.DeleteActivityExecutionLogRequest
	(*DeleteActivityExecutionLogResponse)(nil),          // 8: domain.workflow.v1.DeleteActivityExecutionLogResponse
	(*ListActivityExecutionLogsRequest)(nil),            // 9: domain.workflow.v1.ListActivityExecutionLogsRequest
	(*ListActivityExecutionLogsResponse)(nil),           // 10: domain.workflow.v1.ListActivityExecutionLogsResponse
	(*GetActivityExecutionLogListPageDataRequest)(nil),  // 11: domain.workflow.v1.GetActivityExecutionLogListPageDataRequest
	(*GetActivityExecutionLogListPageDataResponse)(nil), // 12: domain.workflow.v1.GetActivityExecutionLogListPageDataResponse
	(*GetActivityExecutionLogItemPageDataRequest)(nil),  // 13: domain.workflow.v1.GetActivityExecutionLogItemPageDataRequest
	(*GetActivityExecutionLogItemPageDataResponse)(nil), // 14: domain.workflow.v1.GetActivityExecutionLogItemPageDataResponse
	(*common.Error)(nil),                                // 15: domain.common.v1.Error
	(*common.SearchRequest)(nil),                        // 16: domain.common.v1.SearchRequest
	(*common.FilterRequest)(nil),                        // 17: domain.common.v1.FilterRequest
	(*common.SortRequest)(nil),                          // 18: domain.common.v1.SortRequest
	(*common.PaginationRequest)(nil),                    // 19: domain.common.v1.PaginationRequest
	(*common.PaginationResponse)(nil),                   // 20: domain.common.v1.PaginationResponse
	(*common.SearchResult)(nil),                         // 21: domain.common.v1.SearchResult
}
var file_domain_workflow_activity_execution_log_activity_execution_log_proto_depIdxs = []int32{
	0,  // 0: domain.workflow.v1.CreateActivityExecutionLogRequest.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	0,  // 1: domain.workflow.v1.CreateActivityExecutionLogResponse.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	15, // 2: domain.workflow.v1.CreateActivityExecutionLogResponse.error:type_name -> domain.common.v1.Error
	0,  // 3: domain.workflow.v1.ReadActivityExecutionLogRequest.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	0,  // 4: domain.workflow.v1.ReadActivityExecutionLogResponse.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	15, // 5: domain.workflow.v1.ReadActivityExecutionLogResponse.error:type_name -> domain.common.v1.Error
	0,  // 6: domain.workflow.v1.UpdateActivityExecutionLogRequest.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	0,  // 7: domain.workflow.v1.UpdateActivityExecutionLogResponse.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	15, // 8: domain.workflow.v1.UpdateActivityExecutionLogResponse.error:type_name -> domain.common.v1.Error
	0,  // 9: domain.workflow.v1.DeleteActivityExecutionLogRequest.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	15, // 10: domain.workflow.v1.DeleteActivityExecutionLogResponse.error:type_name -> domain.common.v1.Error
	16, // 11: domain.workflow.v1.ListActivityExecutionLogsRequest.search:type_name -> domain.common.v1.SearchRequest
	17, // 12: domain.workflow.v1.ListActivityExecutionLogsRequest.filters:type_name -> domain.common.v1.FilterRequest
	18, // 13: domain.workflow.v1.ListActivityExecutionLogsRequest.sort:type_name -> domain.common.v1.SortRequest
	19, // 14: domain.workflow.v1.ListActivityExecutionLogsRequest.pagination:type_name -> domain.common.v1.PaginationRequest
	0,  // 15: domain.workflow.v1.ListActivityExecutionLogsResponse.data:type_name -> domain.workflow.v1.ActivityExecutionLog
	15, // 16: domain.workflow.v1.ListActivityExecutionLogsResponse.error:type_name -> domain.common.v1.Error
	19, // 17: domain.workflow.v1.GetActivityExecutionLogListPageDataRequest.pagination:type_name -> domain.common.v1.PaginationRequest
	17, // 18: domain.workflow.v1.GetActivityExecutionLogListPageDataRequest.filters:type_name -> domain.common.v1.FilterRequest
	18, // 19: domain.workflow.v1.GetActivityExecutionLogListPageDataRequest.sort:type_name -> domain.common.v1.SortRequest
	16, // 20: domain.workflow.v1.GetActivityExecutionLogListPageDataRequest.search:type_name -> domain.common.v1.SearchRequest
	0,  // 21: domain.workflow.v1.GetActivityExecutionLogListPageDataResponse.activity_execution_log_list:type_name -> domain.workflow.v1.ActivityExecutionLog
	20, // 22: domain.workflow.v1.GetActivityExecutionLogListPageDataResponse.pagination:type_name -> domain.common.v1.PaginationResponse
	21, // 23: domain.workflow.v1.GetActivityExecutionLogListPageDataResponse.search_results:type_name -> domain.common.v1.SearchResult
	15, // 24: domain.workflow.v1.GetActivityExecutionLogListPageDataResponse.error:type_name -> domain.common.v1.Error
	0,  // 25: domain.workflow.v1.GetActivityExecutionLogItemPageDataResponse.activity_execution_log:type_name -> domain.workflow.v1.ActivityExecutionLog
	15, // 26: domain.workflow.v1.GetActivityExecutionLogItemPageDataResponse.error:type_name -> domain.common.v1.Error
	1,  // 27: domain.workflow.v1.ActivityExecutionLogDomainService.CreateActivityExecutionLog:input_type -> domain.workflow.v1.CreateActivityExecutionLogRequest
	3,  // 28: domain.workflow.v1.ActivityExecutionLogDomainService.ReadActivityExecutionLog:input_type -> domain.workflow.v1.ReadActivityExecutionLogRequest
	5,  // 29: domain.workflow.v1.ActivityExecutionLogDomainService.UpdateActivityExecutionLog:input_type -> domain.workflow.v1.UpdateActivityExecutionLogRequest
	7,  // 30: domain.workflow.v1.ActivityExecutionLogDomainService.DeleteActivityExecutionLog:input_type -> domain.workflow.v1.DeleteActivityExecutionLogRequest
	9,  // 31: domain.workflow.v1.ActivityExecutionLogDomainService.ListActivityExecutionLogs:input_type -> domain.workflow.v1.ListActivityExecutionLogsRequest
	11, // 32: domain.workflow.v1.ActivityExecutionLogDomainService.GetActivityExecutionLogListPageData:input_type -> domain.workflow.v1.GetActivityExecutionLogListPageDataRequest
	13, // 33: domain.workflow.v1.ActivityExecutionLogDomainService.GetActivityExecutionLogItemPageData:input_type -> domain.workflow.v1.GetActivityExecutionLogItemPageDataRequest
	2,  // 34: domain.workflow.v1.ActivityExecutionLogDomainService.CreateActivityExecutionLog:output_type -> domain.workflow.v1.CreateActivityExecutionLogResponse
	4,  // 35: domain.workflow.v1.ActivityExecutionLogDomainService.ReadActivityExecutionLog:output_type -> domain.workflow.v1.ReadActivityExecutionLogResponse
	6,  // 36: domain.workflow.v1.ActivityExecutionLogDomainService.UpdateActivityExecutionLog:output_type -> domain.workflow.v1.UpdateActivityExecutionLogResponse
	8,  // 37: domain.workflow.v1.ActivityExecutionLogDomainService.DeleteActivityExecutionLog:output_type -> domain.workflow.v1.DeleteActivityExecutionLogResponse
	10, // 38: domain.workflow.v1.ActivityExecutionLogDomainService.ListActivityExecutionLogs:output_type -> domain.workflow.v1.ListActivityExecutionLogsResponse
	12, // 39: domain.workflow.v1.ActivityExecutionLogDomainService.GetActivityExecutionLogListPageData:output_type -> domain.workflow.v1.GetActivityExecutionLogListPageDataResponse
	14, // 40: domain.workflow.v1.ActivityExecutionLogDomainService.GetActivityExecutionLogItemPageData:output_type -> domain.workflow.v1.GetActivityExecutionLogItemPageDataResponse
	34, // [34:41] is the sub-list for method output_type
	27, // [27:34] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_domain_workflow_activity_execution_log_activity_execution_log_proto_init() }
func file_domain_workflow_activity_execution_log_activity_execution_log_proto_init() {
	if File_domain_workflow_activity_execution_log_activity_execution_log_proto != nil {
		return
	}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[2].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[4].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[6].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[8].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[9].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[10].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[11].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[12].OneofWrappers = []any{}
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDesc), len(file_domain_workflow_activity_execution_log_activity_execution_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_workflow_activity_execution_log_activity_execution_log_proto_goTypes,
		DependencyIndexes: file_domain_workflow_activity_execution_log_activity_execution_log_proto_depIdxs,
		MessageInfos:      file_domain_workflow_activity_execution_log_activity_execution_log_proto_msgTypes,
	}.Build()
	File_domain_workflow_activity_execution_log_activity_execution_log_proto = out.File
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_goTypes = nil
	file_domain_workflow_activity_execution_log_activity_execution_log_proto_depIdxs = nil
}
