// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/audit_trail/audit_entry/audit_entry.proto

package audit_trailv1

import (
	enums "github.com/erniealice/esqyma/pkg/schema/v1/domain/audit_trail/enums"
	common "github.com/erniealice/esqyma/pkg/schema/v1/domain/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditEntry records a single audited operation against an entity.
type AuditEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Actor information
	ActorId        string          `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType      enums.ActorType `protobuf:"varint,4,opt,name=actor_type,json=actorType,proto3,enum=domain.audit_trail.v1.ActorType" json:"actor_type,omitempty"`
	ActorIp        string          `protobuf:"bytes,5,opt,name=actor_ip,json=actorIp,proto3" json:"actor_ip,omitempty"`
	ActorUserAgent string          `protobuf:"bytes,6,opt,name=actor_user_agent,json=actorUserAgent,proto3" json:"actor_user_agent,omitempty"`
	// Target entity
	EntityType string            `protobuf:"bytes,7,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId   string            `protobuf:"bytes,8,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Domain     string            `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	Action     enums.AuditAction `protobuf:"varint,10,opt,name=action,proto3,enum=domain.audit_trail.v1.AuditAction" json:"action,omitempty"`
	// Operation context
	PermissionCode string `protobuf:"bytes,11,opt,name=permission_code,json=permissionCode,proto3" json:"permission_code,omitempty"`
	UseCase        string `protobuf:"bytes,12,opt,name=use_case,json=useCase,proto3" json:"use_case,omitempty"`
	Reason         string `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	MethodName     string `protobuf:"bytes,14,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	// Request tracing
	RequestId     string                 `protobuf:"bytes,15,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TransactionId int64                  `protobuf:"varint,16,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FieldCount    int32                  `protobuf:"varint,17,opt,name=field_count,json=fieldCount,proto3" json:"field_count,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AuditEntry) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEntry) GetActorType() enums.ActorType {
	if x != nil {
		return x.ActorType
	}
	return enums.ActorType(0)
}

func (x *AuditEntry) GetActorIp() string {
	if x != nil {
		return x.ActorIp
	}
	return ""
}

func (x *AuditEntry) GetActorUserAgent() string {
	if x != nil {
		return x.ActorUserAgent
	}
	return ""
}

func (x *AuditEntry) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *AuditEntry) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *AuditEntry) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AuditEntry) GetAction() enums.AuditAction {
	if x != nil {
		return x.Action
	}
	return enums.AuditAction(0)
}

func (x *AuditEntry) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *AuditEntry) GetUseCase() string {
	if x != nil {
		return x.UseCase
	}
	return ""
}

func (x *AuditEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEntry) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *AuditEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AuditEntry) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *AuditEntry) GetFieldCount() int32 {
	if x != nil {
		return x.FieldCount
	}
	return 0
}

func (x *AuditEntry) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ListAuditEntriesRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	EntityType  string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId    string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Filters
	ActorId        string            `protobuf:"bytes,4,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	DomainFilter   string            `protobuf:"bytes,5,opt,name=domain_filter,json=domainFilter,proto3" json:"domain_filter,omitempty"`
	Action         enums.AuditAction `protobuf:"varint,6,opt,name=action,proto3,enum=domain.audit_trail.v1.AuditAction" json:"action,omitempty"`
	PermissionCode string            `protobuf:"bytes,7,opt,name=permission_code,json=permissionCode,proto3" json:"permission_code,omitempty"`
	UseCase        string            `protobuf:"bytes,8,opt,name=use_case,json=useCase,proto3" json:"use_case,omitempty"`
	FieldName      string            `protobuf:"bytes,9,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Date range
	From          *timestamppb.Timestamp    `protobuf:"bytes,10,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp    `protobuf:"bytes,11,opt,name=to,proto3" json:"to,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,12,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEntriesRequest) Reset() {
	*x = ListAuditEntriesRequest{}
	mi := &file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEntriesRequest) ProtoMessage() {}

func (x *ListAuditEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEntriesRequest) Descriptor() ([]byte, []int) {
	return file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuditEntriesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetDomainFilter() string {
	if x != nil {
		return x.DomainFilter
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetAction() enums.AuditAction {
	if x != nil {
		return x.Action
	}
	return enums.AuditAction(0)
}

func (x *ListAuditEntriesRequest) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetUseCase() string {
	if x != nil {
		return x.UseCase
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ListAuditEntriesRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListAuditEntriesRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListAuditEntriesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListAuditEntriesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Entries       []*AuditEntry              `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEntriesResponse) Reset() {
	*x = ListAuditEntriesResponse{}
	mi := &file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEntriesResponse) ProtoMessage() {}

func (x *ListAuditEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListAuditEntriesResponse) Descriptor() ([]byte, []int) {
	return file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuditEntriesResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListAuditEntriesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_domain_audit_trail_audit_entry_audit_entry_proto protoreflect.FileDescriptor

const file_domain_audit_trail_audit_entry_audit_entry_proto_rawDesc = "" +
	"\n" +
	"0domain/audit_trail/audit_entry/audit_entry.proto\x12\x15domain.audit_trail.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$domain/audit_trail/enums/enums.proto\x1a\x1edomain/common/pagination.proto\"\x93\x05\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12?\n" +
	"\n" +
	"actor_type\x18\x04 \x01(\x0e2 .domain.audit_trail.v1.ActorTypeR\tactorType\x12\x19\n" +
	"\bactor_ip\x18\x05 \x01(\tR\aactorIp\x12(\n" +
	"\x10actor_user_agent\x18\x06 \x01(\tR\x0eactorUserAgent\x12\x1f\n" +
	"\ventity_type\x18\a \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\b \x01(\tR\bentityId\x12\x16\n" +
	"\x06domain\x18\t \x01(\tR\x06domain\x12:\n" +
	"\x06action\x18\n" +
	" \x01(\x0e2\".domain.audit_trail.v1.AuditActionR\x06action\x12'\n" +
	"\x0fpermission_code\x18\v \x01(\tR\x0epermissionCode\x12\x19\n" +
	"\buse_case\x18\f \x01(\tR\auseCase\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12\x1f\n" +
	"\vmethod_name\x18\x0e \x01(\tR\n" +
	"methodName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x0f \x01(\tR\trequestId\x12%\n" +
	"\x0etransaction_id\x18\x10 \x01(\x03R\rtransactionId\x12\x1f\n" +
	"\vfield_count\x18\x11 \x01(\x05R\n" +
	"fieldCount\x12;\n" +
	"\voccurred_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xfa\x03\n" +
	"\x17ListAuditEntriesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x19\n" +
	"\bactor_id\x18\x04 \x01(\tR\aactorId\x12#\n" +
	"\rdomain_filter\x18\x05 \x01(\tR\fdomainFilter\x12:\n" +
	"\x06action\x18\x06 \x01(\x0e2\".domain.audit_trail.v1.AuditActionR\x06action\x12'\n" +
	"\x0fpermission_code\x18\a \x01(\tR\x0epermissionCode\x12\x19\n" +
	"\buse_case\x18\b \x01(\tR\auseCase\x12\x1d\n" +
	"\n" +
	"field_name\x18\t \x01(\tR\tfieldName\x12.\n" +
	"\x04from\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12C\n" +
	"\n" +
	"pagination\x18\f \x01(\v2#.domain.common.v1.PaginationRequestR\n" +
	"pagination\"\x9d\x01\n" +
	"\x18ListAuditEntriesResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.domain.audit_trail.v1.AuditEntryR\aentries\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.domain.common.v1.PaginationResponseR\n" +
	"paginationB\xf7\x01\n" +
	"\x19com.domain.audit_trail.v1B\x0fAuditEntryProtoP\x01ZWgithub.com/erniealice/esqyma/pkg/schema/v1/domain/audit_trail/audit_entry;audit_trailv1\xa2\x02\x03DAX\xaa\x02\x14Domain.AuditTrail.V1\xca\x02\x14Domain\\AuditTrail\\V1\xe2\x02 Domain\\AuditTrail\\V1\\GPBMetadata\xea\x02\x16Domain::AuditTrail::V1b\x06proto3"

var (
	file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescOnce sync.Once
	file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescData []byte
)

func file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescGZIP() []byte {
	file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescOnce.Do(func() {
		file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_audit_trail_audit_entry_audit_entry_proto_rawDesc), len(file_domain_audit_trail_audit_entry_audit_entry_proto_rawDesc)))
	})
	return file_domain_audit_trail_audit_entry_audit_entry_proto_rawDescData
}

var file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_audit_trail_audit_entry_audit_entry_proto_goTypes = []any{
	(*AuditEntry)(nil),                // 0: domain.audit_trail.v1.AuditEntry
	(*ListAuditEntriesRequest)(nil),   // 1: domain.audit_trail.v1.ListAuditEntriesRequest
	(*ListAuditEntriesResponse)(nil),  // 2: domain.audit_trail.v1.ListAuditEntriesResponse
	(enums.ActorType)(0),              // 3: domain.audit_trail.v1.ActorType
	(enums.AuditAction)(0),            // 4: domain.audit_trail.v1.AuditAction
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),  // 6: domain.common.v1.PaginationRequest
	(*common.PaginationResponse)(nil), // 7: domain.common.v1.PaginationResponse
}
var file_domain_audit_trail_audit_entry_audit_entry_proto_depIdxs = []int32{
	3, // 0: domain.audit_trail.v1.AuditEntry.actor_type:type_name -> domain.audit_trail.v1.ActorType
	4, // 1: domain.audit_trail.v1.AuditEntry.action:type_name -> domain.audit_trail.v1.AuditAction
	5, // 2: domain.audit_trail.v1.AuditEntry.occurred_at:type_name -> google.protobuf.Timestamp
	4, // 3: domain.audit_trail.v1.ListAuditEntriesRequest.action:type_name -> domain.audit_trail.v1.AuditAction
	5, // 4: domain.audit_trail.v1.ListAuditEntriesRequest.from:type_name -> google.protobuf.Timestamp
	5, // 5: domain.audit_trail.v1.ListAuditEntriesRequest.to:type_name -> google.protobuf.Timestamp
	6, // 6: domain.audit_trail.v1.ListAuditEntriesRequest.pagination:type_name -> domain.common.v1.PaginationRequest
	0, // 7: domain.audit_trail.v1.ListAuditEntriesResponse.entries:type_name -> domain.audit_trail.v1.AuditEntry
	7, // 8: domain.audit_trail.v1.ListAuditEntriesResponse.pagination:type_name -> domain.common.v1.PaginationResponse
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_domain_audit_trail_audit_entry_audit_entry_proto_init() }
func file_domain_audit_trail_audit_entry_audit_entry_proto_init() {
	if File_domain_audit_trail_audit_entry_audit_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_audit_trail_audit_entry_audit_entry_proto_rawDesc), len(file_domain_audit_trail_audit_entry_audit_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_audit_trail_audit_entry_audit_entry_proto_goTypes,
		DependencyIndexes: file_domain_audit_trail_audit_entry_audit_entry_proto_depIdxs,
		MessageInfos:      file_domain_audit_trail_audit_entry_audit_entry_proto_msgTypes,
	}.Build()
	File_domain_audit_trail_audit_entry_audit_entry_proto = out.File
	file_domain_audit_trail_audit_entry_audit_entry_proto_goTypes = nil
	file_domain_audit_trail_audit_entry_audit_entry_proto_depIdxs = nil
}
