// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: domain/ping/ping.proto

package pingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PingDomainService_CreatePing_FullMethodName = "/domain.ping.v1.PingDomainService/CreatePing"
	PingDomainService_ReadPing_FullMethodName   = "/domain.ping.v1.PingDomainService/ReadPing"
	PingDomainService_UpdatePing_FullMethodName = "/domain.ping.v1.PingDomainService/UpdatePing"
	PingDomainService_DeletePing_FullMethodName = "/domain.ping.v1.PingDomainService/DeletePing"
	PingDomainService_ListPings_FullMethodName  = "/domain.ping.v1.PingDomainService/ListPings"
	PingDomainService_SayPing_FullMethodName    = "/domain.ping.v1.PingDomainService/SayPing"
)

// PingDomainServiceClient is the client API for PingDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingDomainServiceClient interface {
	CreatePing(ctx context.Context, in *CreatePingRequest, opts ...grpc.CallOption) (*CreatePingResponse, error)
	ReadPing(ctx context.Context, in *ReadPingRequest, opts ...grpc.CallOption) (*ReadPingResponse, error)
	UpdatePing(ctx context.Context, in *UpdatePingRequest, opts ...grpc.CallOption) (*UpdatePingResponse, error)
	DeletePing(ctx context.Context, in *DeletePingRequest, opts ...grpc.CallOption) (*DeletePingResponse, error)
	ListPings(ctx context.Context, in *ListPingsRequest, opts ...grpc.CallOption) (*ListPingsResponse, error)
	SayPing(ctx context.Context, in *SayPingRequest, opts ...grpc.CallOption) (*SayPingResponse, error)
}

type pingDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingDomainServiceClient(cc grpc.ClientConnInterface) PingDomainServiceClient {
	return &pingDomainServiceClient{cc}
}

func (c *pingDomainServiceClient) CreatePing(ctx context.Context, in *CreatePingRequest, opts ...grpc.CallOption) (*CreatePingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePingResponse)
	err := c.cc.Invoke(ctx, PingDomainService_CreatePing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingDomainServiceClient) ReadPing(ctx context.Context, in *ReadPingRequest, opts ...grpc.CallOption) (*ReadPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPingResponse)
	err := c.cc.Invoke(ctx, PingDomainService_ReadPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingDomainServiceClient) UpdatePing(ctx context.Context, in *UpdatePingRequest, opts ...grpc.CallOption) (*UpdatePingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePingResponse)
	err := c.cc.Invoke(ctx, PingDomainService_UpdatePing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingDomainServiceClient) DeletePing(ctx context.Context, in *DeletePingRequest, opts ...grpc.CallOption) (*DeletePingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePingResponse)
	err := c.cc.Invoke(ctx, PingDomainService_DeletePing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingDomainServiceClient) ListPings(ctx context.Context, in *ListPingsRequest, opts ...grpc.CallOption) (*ListPingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPingsResponse)
	err := c.cc.Invoke(ctx, PingDomainService_ListPings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingDomainServiceClient) SayPing(ctx context.Context, in *SayPingRequest, opts ...grpc.CallOption) (*SayPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SayPingResponse)
	err := c.cc.Invoke(ctx, PingDomainService_SayPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingDomainServiceServer is the server API for PingDomainService service.
// All implementations must embed UnimplementedPingDomainServiceServer
// for forward compatibility.
type PingDomainServiceServer interface {
	CreatePing(context.Context, *CreatePingRequest) (*CreatePingResponse, error)
	ReadPing(context.Context, *ReadPingRequest) (*ReadPingResponse, error)
	UpdatePing(context.Context, *UpdatePingRequest) (*UpdatePingResponse, error)
	DeletePing(context.Context, *DeletePingRequest) (*DeletePingResponse, error)
	ListPings(context.Context, *ListPingsRequest) (*ListPingsResponse, error)
	SayPing(context.Context, *SayPingRequest) (*SayPingResponse, error)
	mustEmbedUnimplementedPingDomainServiceServer()
}

// UnimplementedPingDomainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingDomainServiceServer struct{}

func (UnimplementedPingDomainServiceServer) CreatePing(context.Context, *CreatePingRequest) (*CreatePingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePing not implemented")
}
func (UnimplementedPingDomainServiceServer) ReadPing(context.Context, *ReadPingRequest) (*ReadPingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadPing not implemented")
}
func (UnimplementedPingDomainServiceServer) UpdatePing(context.Context, *UpdatePingRequest) (*UpdatePingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePing not implemented")
}
func (UnimplementedPingDomainServiceServer) DeletePing(context.Context, *DeletePingRequest) (*DeletePingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePing not implemented")
}
func (UnimplementedPingDomainServiceServer) ListPings(context.Context, *ListPingsRequest) (*ListPingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPings not implemented")
}
func (UnimplementedPingDomainServiceServer) SayPing(context.Context, *SayPingRequest) (*SayPingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayPing not implemented")
}
func (UnimplementedPingDomainServiceServer) mustEmbedUnimplementedPingDomainServiceServer() {}
func (UnimplementedPingDomainServiceServer) testEmbeddedByValue()                           {}

// UnsafePingDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingDomainServiceServer will
// result in compilation errors.
type UnsafePingDomainServiceServer interface {
	mustEmbedUnimplementedPingDomainServiceServer()
}

func RegisterPingDomainServiceServer(s grpc.ServiceRegistrar, srv PingDomainServiceServer) {
	// If the following call panics, it indicates UnimplementedPingDomainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingDomainService_ServiceDesc, srv)
}

func _PingDomainService_CreatePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingDomainServiceServer).CreatePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingDomainService_CreatePing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingDomainServiceServer).CreatePing(ctx, req.(*CreatePingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingDomainService_ReadPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingDomainServiceServer).ReadPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingDomainService_ReadPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingDomainServiceServer).ReadPing(ctx, req.(*ReadPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingDomainService_UpdatePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingDomainServiceServer).UpdatePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingDomainService_UpdatePing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingDomainServiceServer).UpdatePing(ctx, req.(*UpdatePingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingDomainService_DeletePing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingDomainServiceServer).DeletePing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingDomainService_DeletePing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingDomainServiceServer).DeletePing(ctx, req.(*DeletePingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingDomainService_ListPings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingDomainServiceServer).ListPings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingDomainService_ListPings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingDomainServiceServer).ListPings(ctx, req.(*ListPingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingDomainService_SayPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingDomainServiceServer).SayPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PingDomainService_SayPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingDomainServiceServer).SayPing(ctx, req.(*SayPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PingDomainService_ServiceDesc is the grpc.ServiceDesc for PingDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "domain.ping.v1.PingDomainService",
	HandlerType: (*PingDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePing",
			Handler:    _PingDomainService_CreatePing_Handler,
		},
		{
			MethodName: "ReadPing",
			Handler:    _PingDomainService_ReadPing_Handler,
		},
		{
			MethodName: "UpdatePing",
			Handler:    _PingDomainService_UpdatePing_Handler,
		},
		{
			MethodName: "DeletePing",
			Handler:    _PingDomainService_DeletePing_Handler,
		},
		{
			MethodName: "ListPings",
			Handler:    _PingDomainService_ListPings_Handler,
		},
		{
			MethodName: "SayPing",
			Handler:    _PingDomainService_SayPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/ping/ping.proto",
}
